### ISSUE TITLE
Field array cannot be reusable?

### ISSUE THREAD

**Issue by aonzzung** [reduxframework/redux-extensions#112]
Hi guys,

I need your help to clarify this.

What I need is to define fields which can be reusable on different page templates. Let's say Home template and Portfolio template.

Here is just quick example, not all. Just to get the idea.
```
// field
    $fieldPortfolioDisplayMode = array(
        'id'        => 'berry-portfolio-section-display-mode',
        'type'      => 'button_set',
        'title'     => __('Portfolio Display Mode', 'tymberry-theme-options'),
        'subtitle'  => __('Select a display mode', 'tymberry-theme-options'),
        'options'   => array(
            'masonry' => __( 'Masonry', 'tymberry-theme-options' ),
            'grid'   => __( 'Grid', 'tymberry-theme-options' ),
            'metro'   => __( 'Metro', 'tymberry-theme-options' ),
        ), 
        'default'   => 'masonry'
    );
    
    // field
    $fieldPortfolioItemSize = array(
        'id'        => 'berry-portfolio-section-item-size',
        'type'      => 'button_set',
        'title'     => __('Portfolio Item Size', 'tymberry-theme-options'),
        'subtitle'  => __('Select an item size', 'tymberry-theme-options'),
        'required' => array(
            array('berry-portfolio-section-display-mode','equals', array('masonry','grid')),
        ),
        'options'   => array(
            'small' => __( 'Small', 'tymberry-theme-options' ),
            'medium'   => __( 'Medium', 'tymberry-theme-options' ),
            'big'   => __( 'Big', 'tymberry-theme-options' ),
        ), 
        'default'   => 'medium'
    );
    
    $boxSections[] = array(
       'icon'      => 'el-icon-website',
       'title'     => __('Portfolio Section', 'tymberry-theme-options'),
       'subsection' => true,
       'fields'    => array(
           $fieldPortfolioDisplayMode,
           $fieldPortfolioItemSize,
));
```

I also have reset ```$boxSections=array(); ``` as your example before re-assigning it to another metabox array (one metabox for Home, another metabox for Portfolio).

What I didn't expect is that Metabox still add everything into the DOM even though it's not configured to show on that page, but with "display:none". 

I think this can break my idea to make field arrays reusable since there are duplicated fields, elements with duplicated ID.

From the screenshot below, the first section (highlighted) must not be shown on this page template. The second section is the only thing I need to show on this page. But in the DOM, everything is there. The different is "display:none"
![screen shot 2557-10-08 at 10 33 23 pm](https://cloud.githubusercontent.com/assets/3109162/4562267/402a722c-4f03-11e4-9115-169115fa0367.png)

I tried again without using my reusable array but write it again in different IDs and it works as usual !!!
So, my assumption about the problem is correct.

Do you have any recommendation of how to make such a reusable variable to keep field array?

Am I missing something about configuring this?

Does it really have to be this way --- adding everything into the DOM and display:none what we don't need to show ?

NOTE
I think I cannot declare it with ``` 'page_template' => array('page-portfolio.php', 'page-home.php') ``` since elements in sections are NOT the same for each Portfolio and Home template. I have to declare it separately and assign different boxSections to each template.
```
$metaboxes[] = array(
        'id' => 'template-metabox',
        'title' => __('Options', 'theme-options'),
        'post_types' => array('page'),
        'page_template' => array('page-portfolio.php', 'page-home.php'),
        'position' => 'normal', // normal, advanced, side
        'priority' => 'high', // high, core, default, low
        'sections' => $boxSections
    );
```

It's quite a long reading. Please let me know if you need more explanation.
If I cannot make field reusable, it's really a pain when I need to maintain it. ;(

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
