### ISSUE TITLE
Bug Report : Metabox doesn't work with post_type = attachment

### ISSUE THREAD

**Issue by aonzzung** [reduxframework/redux-extensions#114]
Hi guys,

First, sorry for opening many issues here ;P 
I appreciate your time and effort and please don't fed up with me lol

However, this issue should have higher priority than any of my previous opened issues since I think it's a bug.

I want to make metabox show on media (Wordpress Media library).

Here is the array
```
$boxSections = array();
    $boxSections[] = array(
        'title' => __('Media Settings', 'theme-options'),
        'desc' => __('Specify media type and source', 'theme-options'),
        'icon' => 'el-icon-cog',
        'fields' => array(  
            array(
                'id'       => 'media-is-vimeo-youtube',
                'type'     => 'switch', 
                'title'    => __('Is Vimeo or Youtube ?', 'redux-framework-demo'),
                'subtitle' => __('Turn on to attach Vimeo or Youtube URL', 'redux-framework-demo'),
                'default'  => false,
            ),
            array(
                'id'        => 'media-vimeo-youtube-url',
                'type'      => 'text',
                'title'     => __('Vimeo or Youtube URL Source', 'theme-options'),
                'subtitle'  => __('Enter url', 'theme-options'),
                'desc'      => __('URL only', 'theme-options'),
                'validate'  => 'url',
                'placeholder'   => 'Enter URL source',
                'required'  => array('media-is-vimeo-youtube','equals','1'),
                'default'   => ''
            ),
        )    
    );
    $metaboxes[] = array(
        'id' => 'media-metabox',
        'title' => __('Options', 'theme-options'),
        'post_types' => array('attachment'),
        'position' => 'normal', // normal, advanced, side
        'priority' => 'default', // high, core, default, low
        'sections' => $boxSections
    );
```

After modify metabox option and click the update button, there is always a popup asking me to leave that page (which should not be shown)
![Image of Metabox](http://i.imgur.com/cjpOtMh.jpg )

Not matter what I click or close the popup, metabox data will never be saved.

I appreciate if you help take a look at this issue ;)

Thanks a lot for your help
Tym

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
