### ISSUE TITLE
Section Borders Can't Hide

### ISSUE THREAD

**Issue by webbudesign** [reduxframework/redux-extensions#118]
Hi,

I think there is an error on section end code. Because I am trying to use required att. and when section is hidden there is a line of border bottom can't hide. I think you solved this problem on the panel but metabox extension still can't hide non active indent section.

Screen 1:  https://www.dropbox.com/s/36kbfcyrn9xlrec/Screen%20Shot%202014-10-21%20at%2000.23.01.png?dl=0

HTML Code: https://www.dropbox.com/s/7fsb4x71bazkh1c/Screen%20Shot%202014-10-21%20at%2000.29.04.jpg?dl=0

Version: Redux Metabox 1.2.9
WP: v4.0

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
