### ISSUE TITLE
no more popup jQuery datebox with date field in Metaboxes

### ISSUE THREAD

**Issue by dimitrilongo** [ReduxFramework/redux-extensions#119]
hello

I have no more popup jQuery datebox with date field in Metaboxes (no error in console), works well with theme options.
thanks
---
Redux Framework v3.3.9.6
Metaboxes 1.2.9
Wordpress 4.0
Debug mode

**Comment by kprovance** [comment]
We've updated both Redux and Metaboxes.  Please download and apply those updates  I believe there was an issue with the date popup in Redux we solved a while back.
