### ISSUE TITLE
Metaboxes - Not working on website with activated ssl (https-protocol)

### ISSUE THREAD

**Issue by Ninos** [ReduxFramework/redux-extensions#124]
The metaboxes are not working with another protocol than http. This is because of following line (117):
```
 $this->base_url = 'http://' . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"];
 $this->post_id  = $this->url_to_postid( 'http://' . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] );
```

You can change it to following:
```
$this->base_url = ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"];
 $this->post_id  = $this->url_to_postid( ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] );
```

Also I found this comment from September, which describes the same problem:
https://github.com/ReduxFramework/redux-extensions/issues/95#issuecomment-55483018

But I wouldn't check for the protocol type, I would just use the slug from the permalink (See also following function: http://codex.wordpress.org/Function_Reference/get_page_by_path).

Thanks

**Comment by dovy** [comment]
This has been pushed in version 1.3.0 that's being uploaded now. Thanks!
