### ISSUE TITLE
Metabox - Color Rgba Won't Work

### ISSUE THREAD

**Issue by MorenoDiDomenico** [ReduxFramework/redux-extensions#129]
Hello,
the filed color_rgba won't work on metaboxes. On theme options it's fine.

I get this
![screen shot 2014-12-13 at 02 56 53](https://cloud.githubusercontent.com/assets/501663/5422097/0d07e948-8274-11e4-96d4-5631f39dcc05.png)

Can you check this?

Thanks.

**Comment by kprovance** [comment]
We updated the color_rgba field some time ago.  Does the issue still persist?

**Comment by kprovance** [comment]
Closing due to lack of response.  Please reopen if further issues persists.
