### ISSUE TITLE
Issues with metaboxes

### ISSUE THREAD

**Issue by PhilippSchreiber** [ReduxFramework/redux-extensions#131]
Hey there,

it seems like I'm not the only one who has problems with the premium extension metaboxes. The Redux Framework itself works perfectly and is indeed very cool. 

None of the "non standard" fields like "media", "slides" or "image_select" works properly. I think the metaboxes code is not enqueuing all the relevant js files for those fields. But that is just a "feeling" ;). 

I think, other open issues (#129, #126, #119) are related to to this issue.

I have the newest version of redux and metafields and Wordpress. Cannot send the theme but since it looks like a generic issue I'm looking forward to a fix :)

@dovy good luck with the moving.

Cheers
Philipp

**Comment by PhilippSchreiber** [comment]
Hey there,

with the new version (1.2.9) it works as expected. But I have to say, the the non support for a paid product is disappointing.

Cheers
Philipp

**Comment by dovy** [comment]
Wow, I didn't even see this. Sorry, I was moving as we sold our home. Do you have any other issues you need help with? My apologies.

**Comment by PhilippSchreiber** [comment]
ok, thanks for your reply. Right now everything works fine!

**Comment by dovy** [comment]
Truly am sorry. You can Skype me anytime at DovyDigital.  ;)
