### ISSUE TITLE
Installing Metaboxes

### ISSUE THREAD

**Issue by DannyOutlaw** [ReduxFramework/redux-extensions#132]
I have purchased redux metabox. But i don't know how to integrate it!

I have read documentations and other things too but its not very clear.

My process :
1. Purchased and Downloaded!
2. Read Documentation, and paste downloaded package to my theme directory called "theme-name/inc/metaboxes" 
3. Called loader.php in my functions.php
4. Changed opt_name in loader.php
5. But no luck, what am I missing?

My opt_name is authority i have changed this on loader.php file.

**Comment by kprovance** [comment]
Verification not provided.  Closing.  If you are in fact using an unpaid for copy of our metaboxes extension, we do expect you to, well, pay for it.
