### ISSUE TITLE
Issue with color scheme extension

### ISSUE THREAD

**Issue by MrHunter** [ReduxFramework/redux-extensions#135]
Hey there,

Our company recently purchased the color scheme extension and it's awesome, it was a breeze to integrate into our theme and am looking forward to having it fully functional!

Problem is when I save the option from the color scheme extension it won't save the selector field that I have set in my config file.

Here are my details according to the guidlines:
<table>
<tr><td>Redux Version:</td><td> 3.3.10.6</td></tr>
<tr><td>WordPress Version: </td><td> 4.1</td></tr>
<tr><td>Extension Version: </td><td> 2.0.0.0</td></tr>
<tr><td>dev_mode: </td><td> false</td></tr>
<tr><td>Field Code: </td><td> <a href="http://pastebin.com/bEWk4qns">http://pastebin.com/bEWk4qns</a></td></tr>
<tr><td>Using: </td><td> I have 2 option panels, 1 in a theme and 1 in a plugin, currently having troubles in the theme panel.</td></tr>
<tr><td>Redux Embedded: </td><td> Redux Embedded in my theme</td></tr>
<tr><td>Console Errors: </td><td> None</td></tr>
</table>

If you need some sort of purchase verification please let me know, I can get it for you.

Thanks.

**Comment by kprovance** [comment]
FIrst, please upgrade to v2.1.0 of the extension to see if that resolves the issue.  Significant changes were made between those versions.

**Comment by MrHunter** [comment]
Hey kprovance,

I updated the extension but I am still getting the same result.

Thanks.

**Comment by kprovance** [comment]
Okay, so I added your config to my config, and I looked at the database, the selector information is in there:  

```
s:18:"theme_color_scheme";a:12:{i:0;a:7:{s:2:"id";s:11:"site-header";s:5:"title";s:17:"Header Background";s:5:"color";s:7:"#000000";s:5:"alpha";d:0.65000000000000002220446049250313080847263336181640625;s:8:"selector";s:6:"header";s:4:"mode";s:16:"background-color";s:5:"group";s:6:"Header";}i:1;a:7:{s:2:"id";s:13:"toolbar-color";s:5:"title";s:12:"Toolbar Text";s:5:"color";s:7:"#FFFFFF";s:5:"alpha";i:1;s:8:"selector";s:8:".toolbar";s:4:"mode";s:5:"color";s:5:"group";s:6:"Header";}i:2;a:7:{s:2:"id";s:17:"header-menu-color";s:5:"title";s:22:"Header menu text color";s:5:"color";s:7:"#FFFFFF";s:5:"alpha";i:1;s:8:"selector";s:108:".bottom-header .navbar-default .navbar-nav>.active>a, header .bottom-header .navbar-default .navbar-nav>li>a";s:4:"mode";s:5:"color";s:5:"group";s:6:"Header";}i:3;a:7:{s:2:"id";s:18:"header-menu-active";s:5:"title";s:23:"Header menu active item";s:5:"color";s:7:"#c7081b";s:5:"alpha";i:1;s:8:"selector";s:59:"header .bottom-header .navbar-default .navbar-nav>.active>a";s:4:"mode";s:27:"background,background-color";s:5:"group";s:6:"Header";}i:4;a:7:{s:2:"id";s:17:"header-menu-hover";s:5:"title";s:22:"Header menu hover item";s:5:"color";s:7:"#c7081b";s:5:"alpha";i:1;s:8:"selector";s:55:".bottom-header .navbar-default .navbar-nav> li> a:hover";s:4:"mode";s:27:"background,background-color";s:5:"group";s:6:"Header";}i:5;a:7:{s:2:"id";s:20:"secondary-background";s:5:"title";s:20:"Secondary Background";s:5:"color";s:7:"#000000";s:5:"alpha";i:1;s:8:"selector";s:17:"#secondary-banner";s:4:"mode";s:16:"background-color";s:5:"group";s:9:"Secondary";}i:6;a:7:{s:2:"id";s:14:"secondary-text";s:5:"title";s:14:"Secondary Text";s:5:"color";s:7:"#FFFFFF";s:5:"alpha";i:1;s:8:"selector";s:17:"#secondary-banner";s:4:"mode";s:5:"color";s:5:"group";s:9:"Secondary";}i:7;a:7:{s:2:"id";s:15:"body-background";s:5:"title";s:15:"Body Background";s:5:"color";s:7:"#FFFFFF";s:5:"alpha";i:1;s:8:"selector";s:47:"section.content, .car-block-wrap, .welcome-wrap";s:4:"mode";s:16:"background-color";s:5:"group";s:4:"Body";}i:8;a:7:{s:2:"id";s:17:"footer-background";s:5:"title";s:17:"Footer Background";s:5:"color";s:7:"#3D3D3D";s:5:"alpha";i:1;s:8:"selector";s:6:"footer";s:4:"mode";s:16:"background-color";s:5:"group";s:6:"Footer";}i:9;a:7:{s:2:"id";s:11:"footer-text";s:5:"title";s:11:"Footer Text";s:5:"color";s:7:"#FFFFFF";s:5:"alpha";i:1;s:8:"selector";s:6:"footer";s:4:"mode";s:5:"color";s:5:"group";s:6:"Footer";}i:10;a:7:{s:2:"id";s:24:"bottom-footer-background";s:5:"title";s:24:"Bottom Footer Background";s:5:"color";s:7:"#3D3D3D";s:5:"alpha";i:1;s:8:"selector";s:15:".copyright-wrap";s:4:"mode";s:16:"background-color";s:5:"group";s:13:"Bottom Footer";}i:11;a:7:{s:2:"id";s:18:"bottom-footer-text";s:5:"title";s:18:"Bottom Footer Text";s:5:"color";s:7:"#FFFFFF";s:5:"alpha";i:1;s:8:"selector";s:15:".copyright-wrap";s:4:"mode";s:5:"color";s:5:"group";s:13:"Bottom Footer";}}}
```

Help me understand what exactly is NOT working.  Please be as descriptive as possible.  I need to be able to see on my end what you are (or aren't) seeing on yours.

**Comment by kprovance** [comment]
Output on the front end shows as thus:

```html
<style type="text/css" title="dynamic-css" class="options-output">header{background-color: rgba(0,0,0,0.65);} .toolbar{color: #FFFFFF;} .bottom-header .navbar-default .navbar-nav>.active>a, header .bottom-header .navbar-default .navbar-nav>li>a{color: #FFFFFF;} header .bottom-header .navbar-default .navbar-nav>.active>a{background,background-color: #c7081b;} .bottom-header .navbar-default .navbar-nav> li> a:hover{background,background-color: #c7081b;} #secondary-banner{background-color: #000000;} #secondary-banner{color: #FFFFFF;} section.content, .car-block-wrap, .welcome-wrap{background-color: #FFFFFF;} footer{background-color: #3D3D3D;} footer{color: #FFFFFF;} .copyright-wrap{background-color: #3D3D3D;} .copyright-wrap{color: #FFFFFF;} .css-selector{margin-top:5em;margin-bottom:20em;margin-left:3em;margin-right:10em;border-top:2px;border-radius:12px;border-color:#ff0000;border-style:solid;}body{background-color:#0000ff;}</style>
```

**Comment by MrHunter** [comment]
Is that the save result? I set the selector in my config file as you saw, but when I save the options and access the color scheme from my option name it contains all the values except it has empty selectors: 

[site-header] => Array
        (
            [id] => site-header
            [title] => Header Background
            [color] => #000000
            [alpha] => 0.65
            [selector] => 
            [mode] => color
            [important] => 
            [group] => Header
            [rgba] => rgba(0,0,0,0.65)
        )

**Comment by kprovance** [comment]
Oh boy.

I changed the first three colour blocks to blue, and this was the print_r:

Array
(
    [color_scheme_name] => Default
    [site-header] => Array
        (
            [id] => site-header
            [title] => Header Background
            [color] => #0000ff
            [alpha] => 1
            [selector] => header
            [mode] => background-color
            [important] => 
            [group] => Header
            [rgba] => rgba(0,0,255,1)
        )
    [toolbar-color] => Array
        (
            [id] => toolbar-color
            [title] => Toolbar Text
            [color] => #0000ff
            [alpha] => 1
            [selector] => .toolbar
            [mode] => color
            [important] => 
            [group] => Header
            [rgba] => rgba(0,0,255,1)
        )
    [header-menu-color] => Array
        (
            [id] => header-menu-color
            [title] => Header menu text color
            [color] => #0000ff
            [alpha] => 1
            [selector] => .bottom-header .navbar-default .navbar-nav>.active>a, header .bottom-header .navbar-default .navbar-nav>li>a
            [mode] => color
            [important] => 
            [group] => Header
            [rgba] => rgba(0,0,255,1)
        )
        [...]
)

The information in the DB and the front end output reflect the same.

So far, I am unable to reproduce.  Are you attempting to use more than one instance of the extension?  It's designed for one usage, meaning one cannot use it twice in the same project (as there wouldn't be much point to it).

**Comment by kprovance** [comment]
@Dovy, could you try MrHunter's config on your install and see if you are able to reproduce.  I'm at a loss here.

**Comment by MrHunter** [comment]
It's only on a single panel, yes.

Hmmm this is odd, is there perhaps an address I can email you at with our site login so you can view this? And maybe send you my whole config file?

**Comment by kprovance** [comment]
YOu mention using Redux in both a theme and plugin?  Are you using color schemes in both?  Do the two instances have separate opt_name, page_slug and config class names?

**Comment by MrHunter** [comment]
Yes they are completely separate, separate option names, slugs, and config names. Only the theme has the color scheme on it.

**Comment by kprovance** [comment]
I asked Dovy to try it on his side, to see if he can reproduce.  Shoulod know in >= 30 min.

**Comment by kprovance** [comment]
You're host isn;t GoDaddy is it?

**Comment by MrHunter** [comment]
Alright no worries, no way no GoDaddy for us!

**Comment by dovy** [comment]
Haha, took me much longer.  :(

@MrHunter , why don't you just send us your code?

support@reduxframework.com

**Comment by kprovance** [comment]
The config in and of itself isn't enough, I need to see the entire theme.  kevin@reduxframework.com

**Comment by MrHunter** [comment]
Whoops I'm sorry, would you prefer me sending a login to the WP site and a temp FTP login?

**Comment by kprovance** [comment]
I'm not real good at debugging on server, unless I know it's a server issue.  I'd rather try it locally to verify that, because if it's a server issue, that a whole different matter.

**Comment by MrHunter** [comment]
Ahh good call, I'll send the whole thing over theme over

**Comment by kprovance** [comment]
You might also ship over the plig-in that uses redux as well.  I'll need to check for code collision

**Comment by MrHunter** [comment]
The theme uses the TGM plugin activation to include our plugin so it should be there along inside the theme, it will give you a notice after installation

**Comment by kprovance** [comment]
Did you get your copy of Redux from our builder page?  Files are missing from the core, and I've seen these before in other cases.

**Comment by MrHunter** [comment]
Yes I first built it then, I converted it from SMOF originally

**Comment by kprovance** [comment]
Well, so far, I've not been able to reproduce anything close to this.  First, the ReduxCore in your theme and plugin are missing vendor files.  Not sure why.  I checked the builder, they are included.  I would download the Redux core from this git repo and manually install the core, so we can resolve the missing vendor files.

Next, I am getting this:
```
Notice: Undefined index: options in D:\xampp\apps\wordpress\htdocs\wp-content\plugins\automotive\functions.php on line 27
```
Not sure why.

Regardless, I banged on the color schemes fairly hard, changing the colors, and whatnot.  They all print out on the front end and print_r as expected.  I'm still at a loss.

**Comment by kprovance** [comment]
We found a flaw in color scheme, and thus pushed version 2.1.1.  Now, I'm not entirely sure this will take care of what you're reporting, as neither Dovy nor I could reproduce it.  But, since the Redux core in your theme was missing vendor files, who knows at this point.  So, please reinstall Redux using the ZIP from this repo and update to color scheme 2.1.1 and we'll go from there.  :)

**Comment by MrHunter** [comment]
Will do, thanks a lot for checking this out. I'll let you know what happens.

**Comment by MrHunter** [comment]
Hey Kevin,

Seems to be working on fresh installs, but I did notice this time what
causes the problem. It is when you save the options with a selector, then
update the selector in the config file and try saving the options again.
This causes it to keep the old saved selector.

Can you replicate the problem after doing this?

Thanks, Dan.

**Comment by MrHunter** [comment]
I can solve it by deleting the .json file in the redux uploads directory
and re-generating my options if this helps at all.

**Comment by dovy** [comment]
@kprovance Any ideas? Where is that code?

@MrHunter Try ADDING or REMOVING a new selector and then it should work.

It's hard for an extension to re-check every field for changes. It's not a very common use case.

**Comment by kprovance** [comment]
Ah, I see now.  Okay, so the extension checks itself for new color fields (via `count`) before forcing itself to update.  It's the nature of this particular beast, unfortunately.  It never checked the actual field values.  I can try adding `array_diff`, but that will happen on each load, and I'm not sure what the performance ramification may be, if any.  Otherwise, yes, each time an alteration is made in a color field, a reset is necessary - short of adding a dummy field each change, and then removing one for the next.

**Comment by MrHunter** [comment]
It's not a huge deal, the only time I can see it being a problem is if an author adds more selectors to an existing color and the users try updating the color and it doesn't work.

**Comment by kprovance** [comment]
@MrHunter, I have a modification for this issue.  Would it be okay for me to send you a ZIP of the modified code?  This process would go faster, versus me uploading, updated, etc, etc until I'm sure it functions as intended.  Let me know!

**Comment by MrHunter** [comment]
For sure send it over and I'll let you know how it works!

**Comment by kprovance** [comment]
Excellent.  Sent.  :)

**Comment by MrHunter** [comment]
Seems to be working perfectly when I change the selectors now, thanks a ton!

**Comment by kprovance** [comment]
Awesome.  :)
