### ISSUE TITLE
Repeater Demo

### ISSUE THREAD

**Issue by milojennings** [ReduxFramework/redux-extensions#136]
It would be great if the repeater field was available in the demo. I'd like to take it for a spin before I buy it. Can that be added to the demo install?

**Comment by dovy** [comment]
Yea, I just need to do that for every extension we have really. Haha.

I'll get to it tomorrow.

**Comment by c89williams** [comment]
I just found myself in the same boat. Love Redux and all it does, but now I really need a repeater. Would love to see a backend example of how it can be used.

**Comment by kprovance** [comment]
Let me see what I can do for you gents.  I'll post back a link for a quickie demo shortly.

**Comment by kprovance** [comment]
For those looking for a repeater demo, I set up an ad hoc version, until we can get a proper extensions demo running on the main site. For now, go here: http://redux.kevinprovance.com/wp-admin/ login: demo; pw: demo
