### ISSUE TITLE
Metabox Error if not set a Posts Page

### ISSUE THREAD

**Issue by Bluxart** [ReduxFramework/redux-extensions#137]
Hi Dovy, I found a little bug in metabox, I think.

Wordpress Version - 4.1
Redux Framework - 3.3.8.1
Metabox Extension - 1.2.9

I explain:

1. If I set a Front-Page and a Post Page the metaboxes work correctly. Infact I call a functions inside the index.php for get the value.

This is the example code:
```php
function az_page_header($postid) {
    global $options_alice, $post;
    $options_az = redux_post_meta( 'alice' , $postid );
        
    $check_title_header_settings = $options_az['az_title_header_display'];
}
```

Call the functions inside the index.php:
```php
<?php az_page_header(get_option('page_for_posts')); ?>
```
But this work only if I set a Front and a Post Page.

Infact if I don't set any static page to Settings -> Reading Settings ( Wordpress Interface ) I have an error.

If I use this syntax inside the index.php:
```php
<?php az_page_header(get_option('page_for_posts')); ?>
```
I have this error: <strong>Notice: Undefined index: az_title_header_display</strong>

Same error if use this:
```php
<?php az_page_header(get_option($post->ID)); ?>
```

I have a different error if I use this syntax:
```php
<?php az_page_header(get_option('show_on_front')); ?>
```
I have this error: <strong>
Notice: Trying to get property of non-object in /Applications/MAMP/htdocs/new_2/wp-content/themes/alice/framework/redux/extensions/metaboxes/extension_metaboxes.php on line 1007</strong>

For now I solved the problem by delete the page header function if the user don't set a Front Page and a Posts Page with this if statement.

```html
<?php if ( is_front_page() ) { ?>
    <div class="no-page-header"></div>
<?php } else { ?>
    <?php az_page_header(get_option('page_for_posts')); ?>
<?php } ?>
```
Exist a solution or I missed something?

Thanks

**Comment by dovy** [comment]
It's probably because WordPress is funny about loops and stuff. That's why I made this little function in my own class so I could access it at any time. You may want to adapt it to your needs. The $post object is not correct and you need to just pass the ID instead:

```
public static function get_the_ID() {
                if ( ! empty( self::$_post_id ) ) {
                    return self::$_post_id;
                }
                if ( in_the_loop() ) {
                    self::$_post_id = get_the_ID();
                } else {
                    /** @var $wp_query wp_query */
                    global $wp_query;
                    self::$_post_id = $wp_query->get_queried_object_id();
                }
                return self::$_post_id;
            }
```

I think that should do the trick. Let me know if you run into any problems.  ;)
