### ISSUE TITLE
Problem when I change an option in the metabox

### ISSUE THREAD

**Issue by nicolas92** [ReduxFramework/redux-extensions#138]
Hello, I have a little problem with the extension, when I change an option in the metabox and I click on "update" of the page, I have a popup that displays "Confirm Navigation", how do I to remove the popup when I change an option in the metabox?
If I have to give you information or I have to create an admin account on my website, can you give me your email and I'll give you all this in private.
Thank you very much.

**Comment by dovy** [comment]
Umm, what version of metaboxes do you have? That's a VERY old bug.

**Comment by nicolas92** [comment]
Oh, what an idiot, I downloaded version 1.1.3, I'm sorry, I installed the latest version and everything works, at least next time, I will not deceive me :)
Thank you.

**Comment by dovy** [comment]
WHEW. Glad to hear I didn't bring back an old bug. :)
