### ISSUE TITLE
Style in the metabox

### ISSUE THREAD

**Issue by nicolas92** [ReduxFramework/redux-extensions#139]
Hello, I have a question, is it possible to do as in the theme options panel for style?
For example, I want to customize my header in the panel I entered the following code and it works:

<pre>array(
	'id'			=> 'header_background',
	'type'			=> 'color',
	'title'			=> __( 'Header Background', 'Aktina' ), 
	'subtitle'		=> __( 'Select your custom hex color.', 'Aktina' ),
	'default'		=> '',
	'transparent'		=> false,
	'target_element'	=> '.head #site-header-inner',
	'target_style'		=> 'background-color',
),</pre>

I tried the following code in the metabox but it does not work:

<pre>array(
	'id'			=> 'ks_header_background',
	'type'			=> 'color',
	'title'			=> __( 'Header Background', 'Aktina' ), 
	'subtitle'		=> __( 'Select your custom hex color.', 'Aktina' ),
	'default'		=> '',
	'transparent'		=> false,
	'target_element'	=> '.head #site-header-inner',
	'target_style'		=> 'background-color',
),</pre>

I know how to fix this, I enter the code in a php file and call the class directly, but I have a lot of style that I would put in the metabox, it would embêttant, is it possible to do as in the theme options panel?
If not, how do I do for "link_color" in php?
For "type > color", I enter the following code, but I have not found for "type > link_color":

<pre>$header_bg = get_post_meta( $post_id, 'ks_header_background', true );
if ( $header_bg && $header_bg !== '#' ) {
	$css .= '.head #site-header-inner{background-color:'. $header_bg .' !important;}';
}</pre>

Can you help me?
Thank you very much.

**Comment by kprovance** [comment]
What color field are you using?  Ours does have `target_element` and `target_style` arguments.

**Comment by nicolas92** [comment]
Hello, this is good, my problem is solved :)
Thank you anyway.
By cons I noticed a small bug with metabox extension since the last release, when I add or remove an item from the metabox, I recharge my page in backend, the page remains in continuous loading.
Despite this little bug, the extension is great :)

**Comment by dovy** [comment]
That's odd. I've never seen that before. Can you reproduce it every time like that?

Glad we solved your issues.

**Comment by nicolas92** [comment]
Yes it happens every time when I add or remove a element of the file for the metabox, when I reload the page wordpress, the page remains continuous loading, I do not know at all how reproduce this bug.
This only happens to me?

**Comment by dovy** [comment]
Basically, ya. Send me your theme and tell me the file to modify. Dovy@reduxframework.com

**Comment by nicolas92** [comment]
I sent you an email :)
