### ISSUE TITLE
Problem typography with the metabox

### ISSUE THREAD

**Issue by nicolas92** [ReduxFramework/redux-extensions#141]
Hello, I have a little problem with the Metabox, I created a section "Typography", I created the same section in the theme options panel, the code works fine but when I remove the police of the Metabox, I would like the police chose in the panel is the one by default, but police panel is no longer taken into account, can you help me?

Here is my code:

Metabox:
<pre>array(
    'id'                => $prefix . 'body_font',
    'type'              => 'typography',
    'title'             => Body,
    'compiler'          => false,
    'output'            => false,
    'google'            => true,
    'font-backup'       => false,
    'font-style'        => true,
    'subsets'           => true,
    'font-size'         => true,
    'line-height'       => true,
    'word-spacing'      => false,
    'letter-spacing'    => false,
    'text-align'        => false,
    'color'             => true,
    'preview'           => true,
    'units'             => 'px',
    'all_styles'        => true,
    'subtitle'          => Select your custom typography options.,
    'default'           => array(
        'font-family'   => '',
        'font-size'     => '',
        'font-weight'   => '',
        'line-height'   => '',
    ),
    'font_family_clear' => true,
),</pre>

File to call the police:
<pre>$add_css = '';
$font = ks_option( 'body_font' );
$meta = get_post_meta( ks_get_the_id(), 'ks_body_font', true );
if ( ! empty( $meta ) ) {
	$font = $meta;
}

if ( ! empty( $font ) ) {
	
	// Vars
	$family = isset( $font['font-family'] ) ? $font['font-family'] : '';
	$size = isset( $font['font-size'] ) ? $font['font-size'] : '';
	$weight = isset( $font['font-weight'] ) ? $font['font-weight'] : '';
	$style = isset( $font['font-style'] ) ? $font['font-style'] : '';
	$color = isset( $font['color'] ) ? $font['color'] : '';
	$line_height = isset( $font['line-height'] ) ? $font['line-height'] : '';
	
	// Font family
	if ( ! empty( $family ) && 'inherit' != $family ) {
		$css .= '.button, input, textarea{font-family:'. $family .'}';
		$add_css .= 'font-family:'. $family .';';
		$load_google_fonts[] = $family;
	}
	
	// Font size
	if ( ! empty( $size ) && 'inherit' != $size ) {
		$add_css .= 'font-size:'. $size .';';
	}
	
	// Font weight
	if ( ! empty( $weight ) && 'inherit' != $weight ) {
		$add_css .= 'font-weight:'. $weight .';';
	}

	// Font Style
	if ( ! empty( $style ) && 'inherit' != $style ) {
		$add_css .= 'font-style:'. $style .';';
	}
	
	// Font color
	if ( ! empty( $color ) && 'inherit' != $color ) {
		$add_css .= 'color:'. $color .';';
	}

	// Line Height
	if ( ! empty( $line_height ) && 'inherit' != $line_height ) {
		$add_css .= 'line-height:'. $line_height .';';
	}
	
	
}

if( $add_css ) {
	$css .= 'body{'. $add_css .'}';
}</pre>

Thank you very much, great extension.

**Comment by kprovance** [comment]
Instead of get_post_meta, use redux_post_meta.

`redux_post_meta( $opt_name = "", $thePost = array(), $meta_key = "")`

**Comment by nicolas92** [comment]
Hi, thank you for your quick response.
I have an error, I probably entered the wrong code, I did:

<pre>$meta = redux_post_meta( ks_get_the_id(), 'ks_body_font', true );</pre>

What should I entered like code?
Thank you.

**Comment by kprovance** [comment]
Um, didn't I just post the function above your reply?  All I can do is repeat myself:

`redux_post_meta( $opt_name = "", $thePost = array(), $meta_key = "")`

**Comment by dovy** [comment]
So that's the function call id. Pass the post variable or id. Also pass in the Id you want. Nuke out the = declarations from the call.

**Comment by dovy** [comment]
And you forgot your opt_name and you don't need true.

**Comment by dovy** [comment]
$meta = redux_post_meta( 'opt_name', ks_get_the_id(), 'ks_body_font' );

**Comment by nicolas92** [comment]
Hi, it works but I have the same problem, when I remove the police from the metabox, I would like the police choose in the panel to be displayed, but it is not taken into account, sorry if you misunderstood me but I use google translate and sometimes mistranslated, if you give me an email, I can create an admin account for you so you can see the problem.

Here is the code for the police:

<pre>$font = ks_option( 'body_font' );
$meta = redux_post_meta( 'ks_options', ks_get_the_id(), 'ks_body_font' );
if ( ! empty( $meta ) ) {
	$font = $meta;
}</pre>

**Comment by dovy** [comment]
What do you mean police? You're not making sense...

**Comment by nicolas92** [comment]
Sorry I mean "font", in french "font" means "police" :)

**Comment by dovy** [comment]
If you want the panel options to be selected, then DO NOT set a default for the metaboxes, and the panel with the same ID will override the meta.  ;)

**Comment by nicolas92** [comment]
No, you misunderstood me :)
It does not matter, I deleted the section, you can close the subject, thank you anyway :)

**Comment by dovy** [comment]
Cool. Good luck.

**Comment by nicolas92** [comment]
By cons I have a problem with the select sidebar, I opened a new topic: https://github.com/ReduxFramework/redux-extensions/issues/142
