### ISSUE TITLE
Problem with the sidebar

### ISSUE THREAD

**Issue by nicolas92** [ReduxFramework/redux-extensions#142]
Hello, I have a little problem with the sidebar, I would will put the sidebar "Main Sidebar" like default sidebar, in backend it work, but in frontend the sidebar is not displayed, can you help me?

The code to select the sidebar:
<pre>$sidebar_options = array();
$sidebar_options[] = array(
    'fields'    => array(
        array(
            'id' => 'sidebar',
            'title' => __( 'Sidebar', 'Aktina' ),
            'desc' => 'Select the sidebar you want to display. Note: You must first create the sidebar under "Appearance > Sidebars".',
            'type' => 'select',
            'data' => 'sidebars',
            'default' => 'main_sidebar',
        ),
    ),
);</pre>

The code to call the sidebar:
<pre>get_sidebar();</pre>

Thank you very much.

**Comment by kprovance** [comment]
All `get_sidebar()` does it retrieve the sidebar.php template.  http://codex.wordpress.org/Function_Reference/get_sidebar.  I'm not understanding how this is a metabox issue?

**Comment by nicolas92** [comment]
Hi, here is my code in sidebar.php:

<pre><?php dynamic_sidebar(); ?></pre>

And that's a problem with the extension metabox because it is with this extension I select a sidebar in backend.
I just want the sidebar by default is "Main Sidebar" and it is visible in the front end, backend it works, but the sidebar is not visible in frontend.
Thank you.

**Comment by kprovance** [comment]
Okay, but all the ext does it store the chosen variable.  YOU have to do something with it.  These wordpress functions are not going to automatically read the selection from the metaboxes.

**Comment by nicolas92** [comment]
Yes, but it was only when I put a sidebar by default when I put a sidebar by default, the sidebar is not visible, all other sidebars are visible, so how do you put a sidebar by default?
I entered the id of the sidebar by default "main_sidebar", in backend, the sidebar is selected, but in front end, the sidebar is not visible, if I put "None" by default and I chose the sidebar "Main Sidebar", it is visible in the front end, so it's a problem with the selection by default.

**Comment by kprovance** [comment]
If you need help writing basic PHP code, then you're going to need to purchase some premium support.  You've not shown us any code where you are taking the option selected from the metabox and applied it to ANY sidebar code, and even so, I've yet to see where this is a metabox issue.  It seems more like an issue where you;re not writing the correct code.  I don't know, I've not seen any.  You can;t ask a mechanic to fix your car over the phone simply by saying 'it won't start'.  Same applies here.

**Comment by nicolas92** [comment]
I understand but my code should not be incorrect, if not all sidebars would not be visible, it's only when I put a sidebar by default.

**Comment by kprovance** [comment]
Okay, subtlety is no good here.  Either show the code that involves the options selected from the metabox and how it's applied to your sidebar logic, or close the ticket.  This piecemeal of incomplete information is wasting our collective time.  Okay?  Thanks.

**Comment by nicolas92** [comment]
Ok, here's the code to select the sidebar:

<pre>$sidebar_options = array();
$sidebar_options[] = array(
    'fields'    => array(
        array(
            'id' => 'sidebar',
            'title' => __( 'Sidebar', 'Aktina' ),
            'desc' => 'Select the sidebar you want to display. Note: You must first create the sidebar under "Appearance > Sidebars".',
            'type' => 'select',
            'data' => 'sidebars',
            'default' => 'main_sidebar',
        ),
    ),
);</pre>

Then the code in my file sidebar.php:

<pre>dynamic_sidebar( ks_get_sidebar() );</pre>

The code of the function "ks_get_sidebar":

<pre>if ( ! function_exists( 'ks_get_sidebar' ) ) {
	function ks_get_sidebar( $sidebar = 'sidebar' ) {

		// Search
		if ( is_search() && ks_option( 'search_custom_sidebar', '1' ) ) {
			$sidebar = 'search_sidebar';
		}

		// WooCommerce
		elseif ( class_exists( 'Woocommerce' ) ) {
			if ( ks_option( 'woo_custom_sidebar', '1' ) && is_woocommerce() ) {
				$sidebar = 'woo_sidebar';
			}
		}
		
		// bbPress
		elseif ( function_exists('is_bbpress') ) {
			if ( is_bbpress() && ks_option( 'bbpress_custom_sidebar', '1' ) ) {
				$sidebar = 'bbpress_sidebar';
			}
		}

		// Check meta option as fallback
		if ( $post_id = ks_get_the_id() ) {
			$sidebar_meta = get_post_meta( $post_id, 'sidebar', true );
			if ( '' != $sidebar_meta && is_active_sidebar( $sidebar_meta ) ) {
				$sidebar = $sidebar_meta;
			}
		}
		
		// Return the correct sidebar name & add useful hook
		$sidebar = apply_filters( 'ks_get_sidebar', $sidebar );
		return $sidebar;
		
	}
}</pre>

And finally the code of the function "ks_get_the_id":

<pre>if ( ! function_exists( 'ks_get_the_id' ) ) {
	function ks_get_the_id() {
		// If singular get_the_ID
		if ( is_singular() ) {
			return get_the_ID();
		}
		// Return nothing
		else {
			return NULL;
		}
	}
}</pre>

I bought the $124.99 extension, I did not want to pay $100 for a premium support. I think you understand.

**Comment by nicolas92** [comment]
It's good, I found a solution, you can close the subject, thank you.

**Comment by kprovance** [comment]
Support for the extension involves the extension only, not writing code to make things work outside the extension.

**Comment by dovy** [comment]
Otherwise we're debugging code we didn't write and that's beyond our job description unless you pay for Premium Support. Sorry, but we deal with a LOT of devs and we have to draw a line or we spend endless time on things that are not our fault.  :P

**Comment by nicolas92** [comment]
There is no problem :)
I just add a little bit of code and it works perfectly, thank you, this is a great extension :)

**Comment by dovy** [comment]
Glad you like it.  :)
