### ISSUE TITLE
Dependency for multiple elements not working in metabox

### ISSUE THREAD

**Issue by yawalkar** [reduxframework/redux-extensions#143]
Hi,

I have an issue with the dependencies given to the elements. I have set the dependency to a switch element from 5-6 elements. But, the first its working only for first two elements. Can you check this?

Awaiting your reply.

Regards,
Nitin

**Comment by dovy** [comment]
Need details beyond that.

What extension are you talking about? What version of Redux. Etc etc.

**Comment by yawalkar** [comment]
I am using the Redux version 3.3.9.6 and 
metaboxes extension version - 1.2.9

**Comment by kprovance** [comment]
What exactly do you mean by 'dependency'?  Are you talking about the `required` argument?  When Dovy asked for more details, he meant an example of the code you are attempting to use, plus anything else specified here:  https://github.com/ReduxFramework/redux-framework/issues/1975

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
