### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by shellycole** [ReduxFramework/redux-extensions#144]
I hate to bug you all again, but I've spent a couple of hours trying to get my extension to install/work on my site, and the documentation on installing the new extensions isn't very clear.

I've tried various methods (embedding it using the Github code only, then swapping to the plugin; using the builder and doing it without.)  My current setup is using the admin folder I got from the builder with the plugin.

My Structure is like so: 

theme/admin
theme/admin/redux-extensions/loader.php
theme/admin/redux-extensions/extensions/repeater

in my functions.php file, I have this:

    /**
     * Prepare theme options
     */
    require_once( dirname( __FILE__ ) . '/admin/redux-extensions/loader.php' );
    require_once( dirname( __FILE__ ) . '/admin/options-init.php' );

and in the loader.php file, at the bottom, I've replaced '{$redux_opt_name}' with 'repeater'.

I've used the example code found on the repeater extension documentation (located here: http://docs.reduxframework.com/extensions/repeater/) inside my theme/admin/options-init.php file, like so:

    // ACTUAL DECLARATION OF SECTIONS
            $this->sections[] = array(
                'id'         => 'repeater-field-id',
                'type'       => 'repeater',
                'title'      => __( 'Title', 'redux-framework-demo' ),
                'subtitle'   => __( '', 'redux-framework-demo' ),
                'desc'       => __( '', 'redux-framework-demo' ),
                //'group_values' => true, // Group all fields below within the repeater ID
                //'item_name' => '', // Add a repeater block name to the Add and Delete buttons
                //'bind_title' => '', // Bind the repeater block title to this field ID
                //'static'     => 2, // Set the number of repeater blocks to be output
                //'limit' => 2, // Limit the number of repeater blocks a user can create
                //'sortable' => false, // Allow the users to sort the repeater blocks or not
                'fields'     => array(
                    array(
                        'id'          => 'title_field',
                        'type'        => 'text',
                        'placeholder' => __( 'Title', 'redux-framework-demo' ),
                    ),
                    array(
                        'id'          => 'text_field',
                        'type'        => 'text',
                        'placeholder' => __( 'Text Field', 'redux-framework-demo' ),
                    ),
                    array(
                        'id'          => 'select_field',
                        'type'        => 'select',
                        'title' => __( 'Select Field', 'redux-framework-demo' ),
                        'options'     => array(
                            '1'             => __( 'Option 1', 'redux-framework-demo' ),
                            '2'             => __( 'Option 2', 'redux-framework-demo' ),
                            '3'             => __( 'Option 3', 'redux-framework-demo' ),
                        ),
                        'placeholder' => __( 'Listing Field', 'redux-framework-demo' ),
                    ),
                )
            );

All I'm seeing are two text fields and a dropdown, with nothing showing to make the field(s) repeatable.  I was looking through the files, and I saw this line in loader.php: 

    $extension_class = 'ReduxFramework_Extension_' . $folder;

But the actual class name for the extension has a lowercase "e", and I thought maybe that has something to do with it, but fixing that didn't make any change.  I'm still just seeing two text fields and a dropdown select box - there's just nothing in there that makes the field(s) repeatable.

Am I missing something?

**Comment by shellycole** [comment]
If anyone gets a chance, a little help would be really nice.  I've done everything I can possibly do to try and get this purchased extension working.  I've even done the "illegal" method of putting it right into the ReduxCore.  It *does* load the extension when I do that, but it doesn't load anything else - not even the field-repeater.php file (when I view the source code, *none* of the files are pulled in, save the actual extension_repeater.php file, which contains the actual class)

When I put the extensions outside the ReduxCore, it doesn't even pull in the extension class (I've done an "if(class_exists())" test, and it doesn't pull in the extension class at all). I've tried pulling in the loader.php file before the config file, as well as even before the framework is pulled in (as per instructions), and neither works. it does nothing, and the repeater fields are rendered as text fields.

If it helps, I've gotten rid of the plugin and admin files (from the builder), and went back to the newest Github repo, and and now pulling it in via my functions.php file (I've tried using the after_setup_theme hook, as well as just flat-out requiring the files).  Everything is up-to-date.  The way my theme is set up is:

theme/inc/redux
theme/inc/redux/ReduxCore
theme/inc/redux/extensions <--this holds the extension files
theme/inc/redux/loader.php

And I have changed the {$redux_opt_name} to "repeater" in the add_action part of the loader.php file.  I'm completely stuck at this point. A little help getting this installed would be greatly appreciated.

**Comment by kprovance** [comment]
`$redux_opt_name` needs to be whatever your opt_name variable is, not the field name

**Comment by shellycole** [comment]
Thank you for that :) 

Okay, I've changed the opt_name, and still ...nothing.  My config file is set as such:

    public function setArguments() {

                $theme = wp_get_theme(); // For use with some settings. Not necessary.

                $this->args = array(
                    // TYPICAL -> Change these values as you need/desire
                    'opt_name'             => 'redux_demo',

and I've changed the loader.php file to this:

    // Modify {$redux_opt_name} to match your opt_name
    add_action("redux/extensions/redux_demo/before", 'redux_register_custom_extension_loader', 0);


and in the sections array of the redux-config.php file, I have this:

    $this->sections[] = array(
                    'id'         => 'test',
                    'type'       => 'repeater',
                    'title'      => __( 'Title', 'text_domain' ),
                    'subtitle'   => __( '', 'text_domain' ),
                    'desc'       => __( '', 'text_domain' ),
                    'fields'     => array(
                            array(
                                'id'          => 'title_field',
                                'type'        => 'text',
                                'placeholder' => __( 'Title', 'text_domain' ),
                            ),
                        ),
                );

Still no-go. There are no repeating field or fields (the field is there, it's just showing up as a plain text field), and the extension class is still not being called in.  I've tried pulling the loader.php file in before the framework, as well as after the framework but before the redux-config.php file - neither works.  Is there something else I'm missing?

**Comment by dovy** [comment]
Shelly:
Send me your code. dovy@reduxframework.com

Also you can Skype me anytime: DovyDigital. 

We'll get you off and running.  :)

**Comment by dovy** [comment]
Thanks for the heads up here. I've updated the docs to reflect the issue you were having. It should be clear now.

Good luck!

http://docs.reduxframework.com/extensions/repeater/

**Comment by shellycole** [comment]
Thank you SO MUCH for your help with this!  I really appreciate it :)
