### ISSUE TITLE
Retrieving post meta

### ISSUE THREAD

**Issue by fireform** [ReduxFramework/redux-extensions#145]
Hi guys,
Just purchased Meta boxes for my upcoming theme. Stucked on this when trying to retrieve post meta:
<pre>
Fatal error: Call to a member function get_values() on a non-object in /Users/fireform/WordPress/wp-content/themes/maurus/functions/backend/options/metaboxes/extensions/metaboxes/extension_metaboxes.php on line 1394
</pre>

Post id is correct. I'm using redux_post_meta( 'my_opt', $post_id ).
Meta boxes - v. 1.2.9
Redux Framework - v. 3.4.1 (from WordPress repository)

Any help will be greatly appreciated.

Regards,
Evgeny

**Comment by kprovance** [comment]
Specifying a meta_key might be helpful.
```php
redux_post_meta( $opt_name = "", $thePost = array(), $meta_key = "")
```

**Comment by fireform** [comment]
Hi Kevin,
Thanks. Just realized that $opt_name isn't a "id" field :D
You did a great work. Keep it up!
