### ISSUE TITLE
Required argumetnt (Meta boxes)

### ISSUE THREAD

**Issue by fireform** [ReduxFramework/redux-extensions#146]
Hi,
Sorry to bother again.
<a href="http://docs.reduxframework.com/core/the-basics/required/">Required argument</a> works great in Redux Framework, but not working in Meta Boxes extension. Maybe you can check on your side?

Regards,
Evgeny

**Comment by kprovance** [comment]
My heme uses Metaboxes and required, so I know it does work.  However, you've not provided ANY sample code, at all.  So there is nothing more I can tell you.  We do have posting guidelines:  https://github.com/ReduxFramework/redux-framework

**Comment by fireform** [comment]
Thanks for your answer.
Here the code I'm using:
<pre>
'fields' => array(
                array(
                    'id'        => 'ef_home_slideshow',
                    'type'      => 'button_set',
                    'title'     => __('Content', EF_TDM),
                    'multi'     => false,
                    'options'   => array(
                        'portfolio-categories'  => __('Portfolio Categories', EF_TDM),
                        'portfolio-posts'       => __('Portfolio Posts', EF_TDM),
                        'custom-set'            => __('Custom Set', EF_TDM),
                        'video'                 => __('Video', EF_TDM),
                    ),
                    'default'   => 'portfolio-posts',
                ),
                array(
                    'id'        => 'section-media-start_',
                    'type'      => 'section',
                    'indent'    => true, // Indent all options below until the next 'section' option is set.
                    'required'  => array('ef_home_slideshow', "=", 'portfolio-categories'),
                ),
                    array(
                        'id'        => 'ef_cats_title',
                        'type'      => 'text',
                        'title'     => __('Title', EF_TDM),
                        'subtitle'  => __('Specify title.', EF_TDM),
                        'default'   => __('Category', EF_TDM),
                    ),
                    array(
                        'id'        => 'ef_general_home_cats',
                        'type'      => 'select',
                        'title'     => __('Categories', EF_TDM),
                        'subtitle'  => __('Select categories you want to include manually.', EF_TDM),
                        'data'      => 'terms',
                        'multi'     => true,
                        'args'      => array(
                            'taxonomies' => 'portfolio-category'
                        ),
                        'placeholder' => __('All categories', EF_TDM),
                    ),
                array(
                    'id'        => 'section-media-end_',
                    'type'      => 'section',
                    'indent'    => false, // Indent all options below until the next 'section' option is set.
                    'required'  => array('ef_home_slideshow', "=", 'portfolio-categories'),
                ),

                array(
                    'id'        => 'section-media-start1_',
                    'type'      => 'section',
                    'indent'    => true, // Indent all options below until the next 'section' option is set.
                    'required'  => array('ef_home_slideshow', "=", 'portfolio-posts'),
                ),
                    array(
                        'id'            => 'ef_portf_slideshow',
                        'type'          => 'slider',
                        'title'         => __('Number of posts', EF_TDM),
                        'title'         => __('Number of posts', EF_TDM),
                        'subtitle'      => __('Specify a number of recent posts to show in the slideshow.', EF_TDM),
                        'desc'          => __('Min: 1, max: 200, default: 20', EF_TDM),
                        'default'       => 20,
                        'min'           => 1,
                        'step'          => 1,
                        'max'           => 200,
                        'display_value' => 'text'
                    ),
                    array(
                        'id'        => 'ef_include_portf',
                        'type'      => 'select',
                        'title'     => __('Posts', EF_TDM),
                        'subtitle'  => __('Select posts you want to include manually ("Number of posts" option will be ignored).', EF_TDM),
                        'data'      => 'posts',
                        'multi'     => true,
                        'args'      => array(
                            'post_type'         => 'portfolios',
                            'meta_key'          => '_thumbnail_id',
                            'posts_per_page'    => -1
                        ),
                        'placeholder' => __('Show all posts', EF_TDM),
                    ),
                array(
                    'id'        => 'section-media-end1_',
                    'type'      => 'section',
                    'indent'    => false, // Indent all options below until the next 'section' option is set.
                    'required'  => array('ef_home_slideshow', "=", 'portfolio-posts'),
                ),
            )
</pre>

Thanks for your time.

**Comment by kprovance** [comment]
Okay, well, the code you provided shows posts on default, with the correct items loaded, which is expected behaviour.  I clicked categories, the post stuff hides ad the category stuff displays.  I saved, and when the page reloads, I see only category stuff.  Clicked portfolio, everything is still in sync.  Saved, everything is still in sync.  I don't know what version of things you are using, so make sure you have the latest ones.

**Comment by fireform** [comment]
Thanks, Kevin.
Will dig deeper :)

**Comment by fireform** [comment]
Hi again,
I created TwentyFifteen mod (sample Redux config + metaboxes) that reproduces the same problem. Maybe you're able to check it on your instance? How I can send it to you?
Thanks in advance!

**Comment by kprovance** [comment]
info@reduxframework.com

**Comment by fireform** [comment]
Sent :+1:

**Comment by kprovance** [comment]
Okay, well, first, the reason it worked based on the code you posted is because it was one box section.  With yours, having the second box section causes required to not work (comment it out and try it).  Why, I do not know.  I do know that in my theme my metaboxes has several sections, which use required, that work fine.  It also means I'll have to spend a bunch of hours attempting to figure out what the difference is, and right now, I don't have that time to spare.  Maybe next week.  Dovy seems to think it may be in one of the hooks, and it could well be since my theme loads them slightly differently that how it typically done.  Something to experiment with, I suspect.

**Comment by kprovance** [comment]
Ha, just as I was about to switch back to my project, I see this issue.  You're only using required on the section, not the fields within the section.  You need to add a required argument for each field you want to show/hide.  When I added those, everything works.

BUT, why the sections?  You're not dividing anything, only adding extra HR lines before and after.  I mean, if you want those extra lines in your design, that's your prerogative, but it's not needed.  It looks better when they're removed.  Anyways, that's how to fix it.

**Comment by fireform** [comment]
Hi Kevin,
Thanks a million for your efforts and sorry for bothering :)

Regards,
Evgeny

**Comment by fireform** [comment]
Hi Kevin,
Finally got it!!! :)
The problem with required argument occurs when the same set of settings doesn't exist in Redux Framework config. But it doesn't require us to use the same settings both in meta boxes and theme options I guess.

**Comment by fireform** [comment]
Hi Kevin,
Maybe you have some time to take a look? The problem is that I don't need same settings in Theme Options.

Regards,
Evgeny

**Comment by kprovance** [comment]
That's going to be more than a 'take a look' issue.  I spoke to Dovy about it.  It's a major bug that will take more than a few minutes to address and fix.  Since we're focusing on our theme's release, it's going to be a few weeks before it can be addressed.

**Comment by fireform** [comment]
Ok,
Thanks for clarification! I'll be waiting :)

Regards,
Evgeny

**Comment by fireform** [comment]
Hi,
Any news about "required" argument? It's might be very helpful for all theme developers using your great extension.
