### ISSUE TITLE
Custom Fonts extension issue

### ISSUE THREAD

**Issue by pseudonymus** [ReduxFramework/redux-extensions#147]
Hi guys:

**System information:**
WordPress 4.1
Redux Framework 3.4.1
Custom Fonts extension v1.0.2

I have an issue with the Custom Fonts extension: every time I upload a font file or multiple font files at once, a JavaScript issue freezes the screen to "Please wait". The error I get is "Uncaught SyntaxError: Unexpected token <", themes.php:1 - http://snag.gy/UTHMO.jpg

Did anyone encounter the problem in the past and found a way to get over it?

Thanks!
adalin

**Comment by kprovance** [comment]
It's never worked on my local install.  Something to do with the font converter and SSL certificate issues.  When I put it live, the problem never showed up again.  Not sure what the fix is for that, if any.  @Dovy?

**Comment by dovy** [comment]
The font converter can only do one font at a time. I need to make that more clear. Also I am making a proxy to fix the ssl issues.

**Comment by dovy** [comment]
I need to make that more obvious. I'll push an update as soon as I have the proxy setup.

**Comment by dovy** [comment]
About to push a new version. This resolves all issues as well as reduces dependency libraries.
