### ISSUE TITLE
'required' option isn't working

### ISSUE THREAD

**Issue by adrwen** [reduxframework/redux-extensions#150]
Hi,

I'm using the newest version of Redux (3.4.2.2) and Metaboxes (1.3.0). When you add **required** option in the Metaboxes and you are using the field with the same ID as in the panel the **required** options isn't working. I wanted to hide the settings from user if he don't want to change anything on the current page. Unfortunately the **required** works only if you add it in the panel config.

###### Panel options
```php
$this->sections[] = array(
    'icon'       => 'el-icon-website',
    'title'      => __( 'Styling Options', 'redux-framework-demo' ),
    'subsection' => true,
    'fields'     => array(
        array(
            'id'       => 'opt-background',
            'type'     => 'background',
            'output'   => array( 'body' ),
            'title'    => __( 'Body Background', 'redux-framework-demo' ),
            'subtitle' => __( 'Body background with image, color, etc.', 'redux-framework-demo' ),
            'default'  => array(
                'background-color'      => '',
                'background-repeat'     => '',
                'background-attachment' => '',
                'background-position'   => '',
                'background-image'      => '',
                'background-clip'       => '',
                'background-origin'     => '',
                'background-size'       => '',
                'media'                 => '',
            ),
        ),
    )
);
```

###### Metaboxes options
```php
$sections[] = array(
    'icon'       => 'el-icon-website',
    'title'      => __( 'Styling Options', 'redux-framework-demo' ),
    'subsection' => true,
    'fields'     => array(
        array(
            'id'       => 'overwrite-layout',
            'type'     => 'switch',
            'title'    => __( 'Custom Layout', 'mpc' ),
            'subtitle' => __( 'Switch to enable custom layout.', 'mpc' ),
            'default'  => 0,
        ),
        array(
            'id'       => 'opt-background',
            'type'     => 'background',
            'output'   => array( 'body' ),
            'title'    => __( 'Body Background', 'redux-framework-demo' ),
            'subtitle' => __( 'Body background with image, color, etc.', 'redux-framework-demo' ),
            'required' => array( 'overwrite-layout', '=', 1 ),
        ),
    )
);
```

**Comment by fireform** [comment]
Hi,
#146

**Comment by dovy** [comment]
Yes, this is a limitation in metaboxes. There's already required based in the panel. So REALLY hard to override that. Best to just leave it alone and let the required from the panel take effect or if there's a big enough demand I guess I can work on that. Just will require a full rewrite of required. Oy.

**Comment by adrwen** [comment]
Sorry about the duplication of the topic and thank you for the answers :)

The workaround I'm currently using:
1. Add the additional field to the panel with custom class.
2. Set the default value to display required fields.
3. Hide the field in the panel so user don't see it and can't change it.
4. Set the default value of field from metaboxes to hide required fields.
5. Check the current value of metaboxes field with _redux_post_meta_.

If you have some better ways of achieving that please share :)

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
