### ISSUE TITLE
Metaboxes Conflict

### ISSUE THREAD

**Issue by ghostpool** [ReduxFramework/redux-extensions#151]
Redux Framework: v3.4.2.6 (integrated)
WordPress v4.1
Metaboxes: v1.3.0

Hi guys,

Upon upgrading to BuddyPress v2.2 the following conflict occurs with the metaboxes extensions:

    Uncaught TypeError: Cannot read property 'contentDocument' of null - mentions.min.js?ver=2.2:2

**Comment by kprovance** [comment]
How do you know the conflict lies with us?  That library is not ours.

**Comment by dovy** [comment]
Yea, we have no such js file as mentions. If it's a conflict on our end I highly doubt it. Care to do more experimenting?

**Comment by ghostpool** [comment]
I removed the framework and the error disappeared and when restoring the framework the error returned. However the error is no longer showing up at all so I can only assume it wasn't an issue with the framework - possibly a file in the BP plugin that wasn't updated correctly or an old file that cached.

**Comment by dovy** [comment]
Whew. Glad you resolved it.
