### ISSUE TITLE
Color_Rgba Metabox Alpha Value

### ISSUE THREAD

**Issue by Bluxart** [reduxframework/redux-extensions#153]
Hi, the problem is simple with the last version available the alpha value for color_rgba don't save the value if changed it ( via color-picker ).

The problem appear if use color_rgba inside the metabox.

Redux Framework: 3.4.3.6
Redux Metabox: 1.3.0

In my metabox I use the color_rgba field:
```php
array(
    'id'            => 'title_header_mask_background',
    'type'          =>  'color_rgba',  
    'title'         =>  __( 'Color Mask', 'redux-framework-demo' ), 
    'subtitle'      =>  __( 'Optional. Select your custom hex color with opacity.', 'redux-framework-demo' ),
    'default'       =>  array( 'color' => '#000000', 'alpha' => '0.55' ),
    'validate'      =>  'colorrgba',
    'transparent'   =>  false,
),
```
Now I need call the post_meta
```php
$options_az = redux_post_meta( 'alice' , $postid );
$title_header_mask_color = $options_az['title_header_mask_background'];
```
The output with the default value of metabox is:
```php
<?php echo $title_header_mask_color['color']; ?>  /* #000000 */
<?php echo $title_header_mask_color['alpha']; ?> /* 0.55 */
<?php echo $title_header_mask_color['rgba']; ?>  /* Error: Undefined index: rgba
```
If change the value with the color-picker ( color-4f55cd and alpha-0.21 ) and save the new output is:
```php
<?php echo $title_header_mask_color['color']; ?>  /* #4f55cd */
<?php echo $title_header_mask_color['alpha']; ?> /* 0.55 */
<?php echo $title_header_mask_color['rgba']; ?>  /* Error: Undefined index: rgba
```
The metabox don't save the new alpha channel, remains always the 0.55 default value.

**Comment by kprovance** [comment]
I am still unable to reproduce.  Sorry.

**Comment by kprovance** [comment]
Also, turn off the `colorrgba` validation.  It does not not work.  it never has, properly.  Maybe that's part of the issue.

**Comment by Bluxart** [comment]
I removed the <pre>colorrgba</pre> validation. The Undefined index: rgba error disapper but not output any variable.

The color channel change and saved into metabox, but the alpha channel not remains the same. Remains the same variable set after the publication of the post/page.

I think the problem is the color_picker because first I used 3.3.8.1 Redux Framework version and the color_rgba work perfectly inside the metabox, but with new version not.

**Comment by kprovance** [comment]
Again, I cannot recreate this.  I cannot fix what I cannot break.  My theme uses RGBA color picker in Redux metaboxes, and there are no problems.

**Comment by Bluxart** [comment]
If you want I created a video for you, with the last version the color_rgba don't work.
I reset now the wordpress database and the problem persist.

Please let me know other steps, I work on local envoriment with MAMP, any js errors and php errors in wordpress admin area.

**Comment by dovy** [comment]
The only other option is for us to LOOK at your code. But alas, since it's not something we can produce we're pretty sure the problem is on your end. Would you be willing to purchase an hour of premium support for us to spend the time?

**Comment by Bluxart** [comment]
I integrated the last version of Redux Framework and Metabox into twentyfifteen theme, and the problem persist.

I use the default file of redux and the color_rgba don't work. simple.

I can insert here the link to the theme file for you see the code? Or take me an email and I send the zip privately.

**Comment by dovy** [comment]
support@reduxframework.com is our email. Again, we'd need you to support us for the time. I promise you it's working on our end...

**Comment by Bluxart** [comment]
If it is my mistake, I will donate $100 I don't have the problem about that.

**Comment by Bluxart** [comment]
Otherwise with Firefox console log I find the js error when I change via color-picker the color/alpha value

Errore: TypeError: redux.field_objects.color_scheme is undefined
http://localhost:8888/new_2/wp-content/themes/twentyfifteen/framework/ReduxCore/inc/fields/color_rgba/field_color_rgba.js?ver=1425082187
Line: 197

**Comment by kprovance** [comment]
I see the issue now.  It would have been helpful to have had information originally, that message.  We did ask you provide any that appeared in the information we ask of people when they post their issues.  It would have saved us BOTH a lot of time.  I'll work on it tomorrow.

**Comment by kprovance** [comment]
Resolve with Redux v.3.4.3.8

**Comment by dovy** [comment]
Thank you for the bug report. Please, in the future, let us know ALL error messages. Thanks!

**Comment by Bluxart** [comment]
Sorry but Chrome don't report any error message into console log. Firefox report me the error when click on choose. Sorry anyway for the mistake. Thanks
