### ISSUE TITLE
Metabox Subsection

### ISSUE THREAD

**Issue by Bluxart** [reduxframework/redux-extensions#154]
Hi guys, I don't know if this is a bug.

Redux Framework: v3.4.3.9
Metabox: v1.3.0

In the Redux Framework Theme Panel if the first section is empty but have two or more subsections work perfectly, but in the metabox extension if the first section is empty and add two or more subsections I can see only the first subsection.

It is normal? Possible the metabox extension has a different behaviour respect the theme panel.

This is a simple code for metaboxes:
```php

$team_settings[] = array(
    'title'     => __( 'Team', 'redux-framework-demo' ),
    'icon'      => 'el-icon-cog'
);

$team_settings[] = array(
    'title'     => __( 'Team Image', 'redux-framework-demo' ),
    'subsection' =>  true,
    'icon'      => 'el-icon-cog',
    'fields'    => array(

        array(
            'id'        =>  'team_single_creative_image',
            'type'      =>  'media', 
            'title'     =>  __('Single Team Mode: Image', 'redux-framework-demo'),
            'subtitle'  =>  __('Optional. Upload a image.', 'redux-framework-demo'),
            'default'   =>  '',
        ),

    ),
);

$team_settings[] = array(
    'title'     => __( 'Team Editor', 'redux-framework-demo' ),
    'subsection' =>  true,
    'icon'      => 'el-icon-cog',
    'fields'    => array(

        array(
            'id'        =>  'team_single_creative_output_text',
            'type'      =>  'editor',
            'title'     =>  __('Single Team Mode: Description', 'redux-framework-demo'), 
            'subtitle'  =>  __('Required. Enter a description.', 'redux-framework-demo'),
            'default'   =>  '',
            'args'   => array(
                'teeny'     => false,
                'wpautop'   => false
            )
        ),

    ),
);
```

**Comment by dovy** [comment]
Probably a bug. I'm tied for the next two weeks though. Is that an issue?

**Comment by Bluxart** [comment]
I find the problem. The sub_section is present but is outside the redux-main container. Like this image:

![schermata 2015-03-05 alle 17 43 34 2](https://cloud.githubusercontent.com/assets/975148/6509397/6585d180-c35f-11e4-9953-b4534f6ebcb4.png)

Don't worry anyway and thanks for support, if I resolve I send the solution here.

**Comment by dovy** [comment]
Thanks!

Yea, we need to move that redux-main class up then. Probably just in the JS declaration.

**Comment by Bluxart** [comment]
Resolved :)

You close the if statment before to close the div and this cause the error.

The file is <code>extension_metaboxes.php</code> 

The original file is this in the lines 1183 - 1887
```php
foreach ( $sections as $sKey => $section ) :
  if ( isset( $section['fields'] ) && ! empty( $section['fields'] ) ) {
    [...]
    // Line 1183 / 1187
  }
    //if ( $sidebar ) {
      echo '</div>';
    //}
  endforeach; ?>
```
The modded and correct file
```php
foreach ( $sections as $sKey => $section ) :
  if ( isset( $section['fields'] ) && ! empty( $section['fields'] ) ) {
    [...]
    // Line 1183 / 1187
  // Remove This }
    //if ( $sidebar ) {
      echo '</div>';
    //}
  } // Add here
  endforeach; ?>
```

**Comment by dovy** [comment]
@Bluxart what version of metaboxes were you using?

**Comment by dovy** [comment]
Hmmm. My line numbers are different than yours.

**Comment by dovy** [comment]
I've added to the field and will release a new version shortly. Thanks!
