### ISSUE TITLE
Icon select documentation access

### ISSUE THREAD

**Issue by jpcid** [reduxframework/redux-extensions#155]
Hi,

I've just bought icon select and I can't access to Icon Select documentation with my user, please check it, I bought it just to save time and I need access to the doc asap.

"This content is restricted to buyers of Icon Select."

My Redux User is jpcid and the ref id is 2486

Regards

**Comment by kprovance** [comment]
Are you able to view this page:  http://reduxframework.com/docs/icon_select/ ?

**Comment by jpcid** [comment]
No. I'm logged in and the response is the same than yesterday.

![icon_select_documentation_-_redux_framework](https://cloud.githubusercontent.com/assets/1781805/6543844/d80b35b2-c52e-11e4-8723-c4facc3e9081.png)

Finally we have programmed a new field with redux extension boilerplate, so this is no longer urgent for us. Anyway if I can help to solve this issue don't lose the chance of contact me in order to get more info to fix this issue for others.

**Comment by dovy** [comment]
http://docs.reduxframework.com/extensions/icon-select/

:)

Also, please note, there was one small change to the field. I've just pushed an update, v. 1.0.5.
