### ISSUE TITLE
Social Profiles jquery-ui-sortable dependency missing

### ISSUE THREAD

**Issue by silviulucian** [reduxframework/redux-extensions#156]
The Social Profiles extension uses jquery-ui-sortable but doesn't require it as a dependency which causes the field_social_profiles.js script to fail:

http://note.io/1BfRwbx

http://note.io/1A3BdK7

Dependency requirement missing:

http://note.io/1BfRYXo

This fixes it:

http://note.io/1BfSMvc

**Comment by kprovance** [comment]
I did fix that, but I haven't pushed the update yet, which also fixes other outstanding issues.  I'll do it later this afternoon.  :)

**Comment by kprovance** [comment]
Updated to version 1.0.2.  :)

**Comment by silviulucian** [comment]
Cheers for that Kevin!
