### ISSUE TITLE
Metaboxes extension assets path incorrect

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-extensions#158]
Hi,  I just purchased the Metaboxes extension, but had to modify it to get it to work.  The URL it is creating to load it's assets is incorrect for my site.
On my site the wp-content folder and the WP core files are in different locations, with different names.  This way the core Wordpress files are kept completely separate from the content and can be updated using git.  I've set the WP constants to reflect the new paths and everything works fine there.

The issue is in the Metaboxes class constructor, it's building its own URL to its assets by removing the value of ABSPATH from its current file path.  On my site ABSPATH and WP_CONTENT_DIR are different, so this doesn't work, and /var/www/public/wp/ ends up in the URL.

Here's what the values for these are on my site:

$this->_extension_dir  = /var/www/public/content/themes/sitetheme/redux/redux-extensions/extensions/metaboxes/

ABSPATH = /var/www/public/wp/

WP_CONTENT_URL = http://mysite.dev/content

WP_CONTENT_DIR = /var/www/public/content

Is there a way to get the extension to use the correct path w/o editing the extension directly?

**Comment by kprovance** [comment]
If memory serves, the loading paths for assets within the wp_enqueue calls in the extension_metaboxes.php use apply_filters, allowing you to use add_filter to specify your own load path.  Take a look at the enqueue() function of that file to get the filter names.  You can then specify your own path (also remembering to add the proper filesnames).

**Comment by Enchiridion** [comment]
You're right, I missed that in the source.
Thanks!
