### ISSUE TITLE
Repeater extension Add/Delete buttons not working

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-extensions#159]
HI, I just installed the Repeater extension and have it setup with the example config, however the Add/Delete buttons don't do anything.
I just posted an issue where the Metaboxes extension was generating an incorrect URL to it's assets, and this extension was doing the same thing, so I've temporarily fixed that.

Using Firebug, I've verified that all the assets are being loaded.  I uncommented a number of console.log() lines in the Redux framework and in the Repeater's js file and verified that both are being loaded and run, however the Repeater's .init() function is never called.

When I examine redux.field_objects, I can see the repeater in there along with its 2 methods, init and sort_repeaters.

**Comment by jamesdbruner** [comment]
I'm having this exact same issue.  I've loaded the metabox extension just fine and I thought maybe I had installed the repeater field extension incorrectly but the field shows up in the metabox, the add/delete buttons just don't do anything.  Is the repeater supposed to come with a config.php like the metabox extension?  At any rate it's not working...

**Comment by kprovance** [comment]
Please reply with ALL the information from this document, including PHP version,  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by jamesdbruner** [comment]
Ahhh, updating fixed the issue for me.  Thank you! :)

**Comment by Enchiridion** [comment]
Not sure exactly why, but it's working now.  I've changed how I'm using it quite a bit from before (from library to plugin), so can't compare. Anyways, thanks!

**Comment by dovy** [comment]
Glad you got it!
