### ISSUE TITLE
Add ability to filter Repeater extension css/js paths

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-extensions#160]
Hi,  Could you please add the ability to filter the paths for wp_enqueue_script and wp_enqueue_style in the Repeater extension just like you can in the Metaboxes extension?
Thanks!

**Comment by dovy** [comment]
Are you sure you're loading the extension properly? This should just work properly out of the box. Seems like something is odd.

**Comment by dovy** [comment]
I bet you're trying to just include the files rather than use the extension loader. Can you confirm?

**Comment by Enchiridion** [comment]
I'm using the extension loader that Redux Builder generated.
I currently have the Metaboxes extension working.  I added some debug lines to field_repeater.php and verified it is loading.
The issue is on line 63 of field_repeater.php:
$this->extension_url = ...
It isn't creating the correct path for where I have the framework, unfortunately just removing ABSPATH from extension_dir doesn't lead to right path.  In the Metaboxes extension I can add filters on wp_enqueue_script and wp_enqueue_style to change the path to the correct path for my site.

**Comment by kprovance** [comment]
I pushed an update for repeater, v1.0.3, which adds the same apply_filters to the asset enqueue files that metaboxes uses.

**Comment by Enchiridion** [comment]
Thanks, works great!
