### ISSUE TITLE
Metaboxes not working as advertised.

### ISSUE THREAD

**Issue by jh1551** [reduxframework/redux-extensions#161]
Redux Framework 3.3.6
Redux Metaboxes 1.3.0

I use a lot of metaboxes to change the styles for the header/page title/page background/etc. The user has the ability to set defaults in the options panel and then override them on a page by page basis using the metaboxes.  Metaboxes work fine on their own with unique IDs, and Redux options work fine on their own with unique IDs, but when I try giving an option field and a metabox field the same ID, I get nothing. That functionality is pretty much the sole reason I bought the plugin, but I can't get it to work.

Redux Panel Option Ex.
--------------------------------
                    array( 
                        'title'         => __('Header Height', 'Atx' ),
                        'id'            => 'atx_header_height',
                        'type'          => 'text',
                        'default'       => '120',
                        ),

Metabox for the same field (No default set)
-----------------------------------
                array( 
                        'title'         => __('Header Height', 'Atx' ),
                        'id'            => 'atx_header_height',
                        'type'          => 'text',
                        ),

To retrieve the value:
-------------------------------------
global $atx_options; <---(opt_name)
$atx_id = get_queried_object_id();

<header id="main-header" <?php atx_header_classes(); ?>  style="height:<?php echo redux_post_meta('atx_options', $atx_id, 'atx_header_height'); ?>px;">

The way I understand it is that Metaboxes is supposed to use the value chosen for that field on a page by page basis, and if no value is set, it should fall back to the default option set in the panel using the same ID. Is that correct?  That is not the behavior I experience with this plugin.

In fact, the options panel field isn't even recognized using $atx_options['atx_header_height'] for any field that has the same ID as a field in the metaboxes plugin. 

Am I missing something?

**Comment by kprovance** [comment]
The first thing you want to do is update Redux to the current version here in the repo, and see if the problem persists.  The version you have is outdated.

**Comment by jh1551** [comment]
Ok. That is the version the Redux Builder gave me in a new download last night. I Updated to 3.4.4.2 and the problem persists.

I can get the value of the metabox with either 
$opt_name['value'] 
or 
redux_post_meta('opt_name', $id, 'value') 

but both ways return empty if I leave the metabox empty and set the panel value with the same id.

**Comment by kprovance** [comment]
I cannot duplicate.  Dovy should be back my Monday.  He's better at figuring metabox issues out, as it's probably in the load order.

**Comment by jh1551** [comment]
Can I get some help with this issue please?

**Comment by dovy** [comment]
Sorry for the delay. As the docs state here: http://docs.reduxframework.com/extensions/metaboxes/

You should be using `$value = redux_post_meta( "OPT_NAME", "THE_POST", "META_KEY" )` to get the proper value.

Let me know if that resolves your issue.

**Comment by jh1551** [comment]
as in:
$value = redux_post_meta( 'atx_options', $post->ID, 'atx_meta_key' ) 

?

I can get my meta values just fine using that, but they don't fall back to my corresponding option panel values when the meta box is empty.

**Comment by jh1551** [comment]
I wiped my database and loaded a fresh install on a new db, everything seems to be working fine now.

**Comment by dovy** [comment]
AHH, what happened then was there was a saved empty value in the database. How very odd since we don't save those usually. In the future we'll have a "reset metaboxes" button. 

Glad you figured it out.
