### ISSUE TITLE
Color Scheme Extension

### ISSUE THREAD

**Issue by seancoreym** [reduxframework/redux-extensions#162]
Hi There,

I'm hoping to find more resources to better learn how to use the Color Scheme Extension. Is it possible for you to please share the code used to build the color scheme in the online demo?:
http://redux.kevinprovance.com/wp-admin/admin.php?page=2014_options&tab=0

I greatly appreciate it

**Comment by kprovance** [comment]
I thought I included that example in the actual package, in a folder called 'example'.  Is it not in there?

**Comment by seancoreym** [comment]
Hey Kevin. The example folder is not included. The 3 folders are img, inc, vendor

**Comment by kprovance** [comment]
Whoops.  I guess I forgot to include it.  Here is what I used on the demo site.  It only works with the twenty-thirteen theme:  https://gist.github.com/kprovance/a5ebcc2dc9aa88dbd01c

**Comment by seancoreym** [comment]
Awesome. Thanks so much.
