### ISSUE TITLE
Wordpress Screen Options stops working when metaboxes extension is active

### ISSUE THREAD

**Issue by frytaz** [reduxframework/redux-extensions#163]
If metabox extension is enabled i can not click on screen options with metaboxes on page or post page 

Using latest premium metabox extension and latest redux framework version
http://cl.ly/image/3h37111e0w1m

**Comment by kprovance** [comment]
I am unable to reproduce.  We require version info please.  Redux, Metabox, PHP, Wordpress, etc.  Plus the code you are attempting to us would be helpful.

**Comment by frytaz** [comment]
PHP: 5.5.15
Wordpress: 4.1.1
Latest redux-framework
Latest redux metabox extension

Let me know where i can send sample theme with redux and extensions where i can reproduce this issue.

**Comment by kprovance** [comment]
I'm sorry, but 'latest version' is not a proper answer.  Actual version numbers are required.

**Comment by frytaz** [comment]
All right i just cloned master of redux-framework and use 1.3.0 of redux metaboxes extension

**Comment by dovy** [comment]
Are you checking the error logs? Have you checked permissions?

We used to use WPEngine, so I know it's not something that regularly occurs. Cardinal (http://cardinal.swiftideas.com) and others are on WPEngine. It's something with your setup specifically.

**Comment by frytaz** [comment]
Its all fine, it was my mistake on internal styles...

**Comment by dovy** [comment]
Glad you figured it out.

If you like Redux, or the support we render, please do one or all of the following:
* Donate to keep us going: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=MMFMHWUPKHKPW
* Review us: http://wordpress.org/support/view/plugin-reviews/redux-framework
* Like us: http://facebook.com/ReduxFramework
* Follow us: http://twitter.com/ReduxFramework
