### ISSUE TITLE
Slides field showing the wrong cursor in metabox

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-extensions#165]
Hi,
When the Slides field is used in a metabox, it is showing a Text cursor instead of a Move cursor on the accordion titles.  It's showing the correct cursor when not used in a metabox.

There's a style in extension_metaboxes.css that's setting the Text cursor and overriding the Move cursor:
```css
.postbox .redux-main h3 {
    -moz-user-select: inherit !important;
    cursor: text !important;
    padding-left: 0 !important;
}

**Comment by dovy** [comment]
Can you suggest a CSS block that would allow that to remain while still giving the effect you need? I'll gladly add it to metaboxes.

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
