### ISSUE TITLE
Creating fields for custom post types

### ISSUE THREAD

**Issue by pgallastegui** [reduxframework/redux-extensions#167]
I am trying to create a set of fields, one per post type (including custom post types) each of which is of type select (the admin needs to select a few options for each post type).
At the time of creating the fields array WP's get_post_types only returns the default post types (Media, Pages, Posts), and not the custom ones.
Is there any way to add fields later on the lifecycle, or create a placeholder or callback of some sort?

**Comment by dovy** [comment]
Oh, that's a tough one. The only way would be to delay your Redux init until after those post types have been created. There's really no good way to do a callback for that...

**Comment by dovy** [comment]
You could transition to the new Redux API and it would auto-delay until init if you're using a theme:
http://docs.reduxframework.com/core/redux-api/

**Comment by pgallastegui** [comment]
Thank you very much, Dovy!

**Comment by dovy** [comment]
You're welcome.  :)
