### ISSUE TITLE
CSS Extension WP Setup

### ISSUE THREAD

**Issue by nasad76** [reduxframework/redux-extensions#169]
Hi there,

I just purchased the CSS extension. I am trying to upload the file through wp dashboard as a plugin but is not working.

I have already downloaded the Redux Framework plugin and I need help activating the CSS extension.

Please advise.

Thanks
nael

**Comment by kprovance** [comment]
Extensions are not plugins.  Install instructions are on the docs page:  http://docs.reduxframework.com/extensions/css-layout/
