### ISSUE TITLE
 Add ability to filter JS Button extension js paths

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-extensions#170]
Hi, Could you please add the ability to filter the paths for wp_enqueue_script in the JS Button extension just like you can in the Metaboxes extension?
Thanks!

**Comment by kprovance** [comment]
Replace line 161 with this:

```php
wp_enqueue_script(
    'redux-field-js-button-js',
    apply_filters( "redux/js_button/{$this->parent->args['opt_name']}/enqueue/redux-field-js-button-js", $this->extension_url . 'field_js_button' . $min . '.js' ),
    array('jquery'),
    time(),
    true
);
```

That will be the update I'll post, but probably not today, which is why I am giving it to you here.  :)

**Comment by Enchiridion** [comment]
Thanks, works great!
