### ISSUE TITLE
Redux Admin Notice Editor plugin appears, requires update, fails

### ISSUE THREAD

**Issue by tylerregas** [reduxframework/redux-extensions#171]
Here's a screenshot of the entry in the plugins: 

![](http://i.imgur.com/cSthJCx.png)

Unlike the last time when I could disable the Posts by Cat plugin and it would allow the update, this time it has no effect. Ideas?

**Comment by dovy** [comment]
Yea, please do a new update of Redux Framework to 3.5.3.1 and that will disappear. It was an issue with SVN not deleting a file... My bad.

**Comment by tylerregas** [comment]
Cool. 3.5.3 is still showing up as latest and loops updates, so 3.5.3.1 hasn't shown up yet. I'll try later and if I have any additional issues, I'll post :D Thanks! -TC

**Comment by dovy** [comment]
;)

https://wordpress.org/plugins/redux-framework/

It's up. Just delete Redux and re-install.

**Comment by tylerregas** [comment]
That got it :D Thanks again!! Yu rawk hard!!
