### ISSUE TITLE
Metaboxes - Not saving default values

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-extensions#172]
Could you please make the metaboxes extension respect the 'save_defaults' setting?
I'm currently working on a project with a dynamic default value which needs to be saved, but currently isn't.

Thanks!

**Comment by dovy** [comment]
Use redux_get_meta() to get the defaults even if it's not saved.  ;)

**Comment by dovy** [comment]
Whoops, updated the function name.  ;)

**Comment by Enchiridion** [comment]
I looked at the function, but it doesn't do what I need.

When the metaboxes are loaded I'm setting a default value, based on current conditions, which needs to be saved at that time.  When I call redux_post_meta() later, the default values will be different.

Not saving the default values to the database also requires me to extra logic to the templates and breaks querying for those meta values.  I understand that one of your reasons for not storing the default value is to save space in the database, but the actual storage savings is very small and doesn't IMHO outweigh all the extra work that has to be done on the UI site.

I looked through the extension_metaboxes.php source and patched it to add the ability to save the defaults if you want to.  It uses the existing 'save_defaults' value.  Hopefully you can integrate this in the next release.

extension_metaboxes.php
Line 1266
```
-                        $save = false;
+                        $save = $this->parent->args['save_defaults'];
```
