### ISSUE TITLE
Metaboxes value doesnt overwrite for post and custom type

### ISSUE THREAD

**Issue by KingsDen** [reduxframework/redux-extensions#173]
Hi Dovy
I am using redux metaboxes version 1.3.0 and i have an issue that Metaboxes post values not overwrite the defaults values. Metabox value on post and on custome type is ignored and global Redux option is returned. Any solution for this?

Thanks.

**Comment by KingsDen** [comment]
Actually all good with default permalinks but when I change permalinks to Post name they are not overwriting the global options.

**Comment by KingsDen** [comment]
as per same previous issues's comments i used this code and now all works.
$this->base_url = ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"];
$this->post_id  = url_to_postid( ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] );

**Comment by dovy** [comment]
Probably because you're within a loop or something like that. Use redux_post_meta to make it happen (http://docs.reduxframework.com/extensions/metaboxes/).

I would have to grab your code and/or have server access to debug further. My guess though is that it's an issue with the loop.  ;)
