### ISSUE TITLE
Have a problem in metaboxes extension

### ISSUE THREAD

**Issue by shamalli** [reduxframework/redux-extensions#177]
Warning: preg_match() [function.preg-match]: Unknown modifier ‘(’ in /home/smeasday/public_html/wp-content/themes/weeklynews/inc/redux/ReduxCore/extensions/metaboxes/extension_metaboxes.php on line 635

How can I fix this

**Comment by shamalli** [comment]
The same error in another WP theme

Message: Warning: preg_match(): Unknown modifier '(' in /wp-content/themes/gauge-theme 3.6/gauge/lib/metaboxes/extensions/metaboxes/extension_metaboxes.php on line 697

Do you support this payment extension after get money?

**Comment by dovy** [comment]
What version of metaboxes are you using?

**Comment by dovy** [comment]
Also please provide a support URL/hash as outlined on our docs. :)

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
