### ISSUE TITLE
Metaboxes - Text fields getting cut off

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-extensions#178]
When I use text fields or other field types based on textboxes, like the spinner control, they are too wide and are getting cutoff when used in the sidebar.

![untitled](https://cloud.githubusercontent.com/assets/1973445/7355408/c8e8f4e8-ecde-11e4-955b-b5dc33526cbc.png)

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
