### ISSUE TITLE
Metaboxes - Associating taxonomy terms to a post

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-extensions#179]
I have a select field that I'm populating with taxonomy terms that I want associated with the current post, however when I save, it's just saving the terms as post meta data and not actually creating the association between the post and the term. 

I saw issue #61 which is exactly what I'm trying to do, but with a select field.  I searched through the source code of both the core and extensions, but couldn't find any instances of the filters or actions you mentioned.  For example the ```before_save``` action doesn't exist anywhere at all.

Here's the field I'm using:
```
            'fields' => array(
              array(
                'id'          => 'region'
                'type'        => 'select',
                'title'       => '',
                'data'        => 'terms',
                'args'        =>  array('taxonomies' => array('region-taxonomy')),
              ),
            ),
```

It would be really great if I could just set another argument like ```'assoc_terms'  => true,``` and have the field read and write its data using the post's taxonomy terms instead of saving the data as meta data.

**Comment by Enchiridion** [comment]
Hey guys, just wondering if there's an update on this?  This is currently a blocking a project I'm working on.
Thanks!

**Comment by dovy** [comment]
This isn't in Redux Metaboxes natively, but I'll add it. Here's how you can do it now for yourself.

I'm not going to do the saving function for you, but I'll make the tools. Here's a filter I'm adding just above:
`$validate = $this->parent->_validate_values( $toSave, $toCompare, $this->sections );`
```
$validate = $this->parent->_validate_values( $toSave, $toCompare, $this->sections );
```

I also added this to just after: `$check = $this->post_type_fields[ $_POST['post_type'] ];`
```
$toSave = apply_filters('redux/metaboxes/save', $toSave, $toCompare, $this->sections );
```

Add that to your code and I'll push these changes in my next metabox release. Good luck!

**Comment by Enchiridion** [comment]
Thanks! With those changes I was able to hook onto the save action and manage the taxonomy data as I needed to.
I had to make a change in the core in order to show the correct taxonomy data when the form was shown again.  It's pull request #2328, a change which I think others could find useful.

**Comment by Enchiridion** [comment]
For anyone else who may view this post later, this is how I managed the taxonomy data.
Note: This only handles assigning 1 taxonomy term, it needs to be modified to handle multiple terms.

Add this to your fields to have a select field display the taxonomy terms:
```
array(
  'id'       => 'your_id_here',
  'type'     => 'select',
  'data'     => 'terms',
  'args'     =>  array('taxonomies' => array('taxonomy_name_here')),
),
```
Then add this to your plugin to handle associating the selected term:
```
add_filter( 'redux/metaboxes/save/before_validate', 'update_post_taxonomy_terms', 10, 3 );

function update_post_taxonomy_terms( $to_save, $to_compare, $sections ) {
  global $post_id;
  $to_save_item_name = 'your_redux_field_name_here';
  $taxonomy_name = 'taxonomy_name_here';

  if ( isset( $to_save[ $to_save_item_name ] ) ) {
    $term_id = (int)trim( $to_save[ $to_save_item_name ] );

    // Delete existing terms
    wp_delete_object_term_relationships( $post_id, $taxonomy_name );

    if ( $term_id > 0 ) {
      // Add new term
      wp_set_object_terms( $post_id, $term_id, $taxonomy_name, true );
    }

    // Don't save terms as metadata
    unset( $to_save[ $to_save_item_name ] );
  }

  return $to_save;
}
```
