### ISSUE TITLE
JS Button - Undefined index: class

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-extensions#180]
I'm getting JS Button setup and when I don't give the button a class property (which the docs says is optional) I get a PHP error "Notice: Undefined index: class".  I checked the source and the class item isn't being checked if it exists before trying to use it; it's a pretty simple fix.

field_js_button.php Line 90 should be:
```$button_class   = isset( $arr['class'] ) ? $arr['class'] : '';```

**Comment by kprovance** [comment]
For now, just add a blank class argument.  I'll fix it in the coming week.

**Comment by Enchiridion** [comment]
Thanks!
That's what I did for now.

Could you also make the ```'function'``` property optional too?  With how my Javascript is setup, it's works better for me to add a handler the
