### ISSUE TITLE
metaboxes - JS error with WP SEO

### ISSUE THREAD

**Issue by corradomatt** [reduxframework/redux-extensions#181]
WP SEO recently updated qTip and the metaboxes extension removed the qTip enqueued scripts because there was an issue with compatibility between the qTip version 1 and version 2. WP SEO updated their version of qTip to version 2 earlier this year (or maybe last year) and the extension no longer needs to dequeue these scripts.

1. In ```metaboxes/extension_metaboxes.php``` on lines 93 through 95 we can remove the actions
2. In the same file the callback function can also be removed between lines 365 and 369.

I experienced admin JS errors in post edit screens when WP SEO was installed and activated with the metaboxes extension.

**Comment by PayteR** [comment]
+1 truth to that

and just getting into issues because of this lines, because it dequeue qtip for EventON plugin and it breakes functionality in it

**Comment by dovy** [comment]
if (defined('WPSEO_VERSION') && version_compare(WPSEO_VERSION,'3.0.0','ge')) {
          add_action('wp_print_scripts', array($this, 'FIX_wp_seo'), 100);
          add_action('admin_enqueue_scripts', array($this, 'FIX_wp_seo'), 100);
}

**Comment by dovy** [comment]
Update the code to that.  :)

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
