### ISSUE TITLE
Redux Metabox values reset to default when clicking save from Visual composer in editor

### ISSUE THREAD

**Issue by algebres** [reduxframework/redux-extensions#183]
Hello
Guys

I have one issue with redux metabox. im using visual composer editor and redux metabox.

when i save the values from font end of visual composer i noticed that all the value of metabox i have previewslly entered are reseting to default values of metabox

In other words , from front end of visual composer , when clikcing of save , all the entered values for metabox i previewslly enter in the page are reset to default value of metabox

Will be great if you guys can help

Thank in aedvance

**Comment by jpcid** [comment]
Hi,

We have been fixed this issue by checking if current request has vc_inline post param

```php
// Check vc frontend editor
function meta_boxes_save( $post_id, $post ) {
    if ( isset($_POST['vc_inline']) && $_POST['vc_inline']){
        return $post_id;
    }
    ...
```
> Courtesy of @mariomka

Best

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
