### ISSUE TITLE
Color Scheme Extension not working

### ISSUE THREAD

**Issue by MrHunter** [reduxframework/redux-extensions#184]
A customer reported that the color scheme extension isn't working, I went in and noticed that the website cannot write files so my first though was to manually upload the .json file for the color scheme through FTP (as I've done this before in the past to get it working again) but when I did this still nothing... Then I went and tried to import a color scheme from a working site and I get the success message and hit "Ok" to refresh the page, but still nothing.

I'm really unsure what's going on here so any input would be appreciated! 

Thanks!

**Comment by kprovance** [comment]
Please obtain a support URL from your client and post it back here.  http://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by kprovance** [comment]
Also, just to let you know, I'll review the code to see if there is a bug in the wp_filesystem routines, but if it's an actual server error, meaning the PHP config is suspect, that doesn't fall under the scope of our support.  Also, if their host is GoDaddy, that a WHOLE different set of problems.  I'd also see if you can get your hands on their PHP error log

**Comment by MrHunter** [comment]
Ahh my bad, I forgot about that feature! http://support.redux.io/?id=QzU1E2IqTAiyGdBQJZEkZkqQ%2FOqkaTaM5rHWa%2FUZDcLxCsIOFlq2IhoG0uNf%2BLwg9qbwBm1hWDdh89DRL9OcSg%3D%3D

No worries if it's a server error, then it's also not under our support scope either! I don't think it's with GoDaddy or else there would of been a ton more tickets opened with our support.

I'll see if I can get a error log too.

**Comment by kprovance** [comment]
Well, the support data shows the data store as writable.  I found in the color scheme code usage of an old wp_filesystem call that isn't using our updated proxy routines.  Ping me your email address @ kevin@reduxframework.com and I'll email you an updated code base for color schemes after I update it, so you can test with it.  Also, I see the client has WP htaccess editor installed?  If they're tampering with .htaccess, you may want to look into that as well, especially if they don;t know what they are doing (I am merely making that assumption, I could be wrong).  If you can get that error log, that might also answer some Qs  :)

**Comment by kprovance** [comment]
Resolved.  Was a permission issue.

**Comment by MrHunter** [comment]
Thank you very much, I will be making a donation for this.

**Comment by dovy** [comment]
Thank you. Please contribute to the customizer project at http://ideas.reduxframework.com.

**Comment by MrHunter** [comment]
Done, thanks for the great product and support!

**Comment by ukvehicle** [comment]
Have had a similar issue . In my case the file color_scheme_extension.php file changes to color_scheme_extension.php.suspect. So when i reupload the color_scheme_extension.php it works for a while say a few hours but changes again to color_scheme_extension.php.suspect and the site cannot be accessed. I have now changed the permissions to 0444. Hope this will now sort the issue. Thanks for your info
