### ISSUE TITLE
Redux Metaboxes - redux_post_meta() function doesn't work during ajax call from the frontend

### ISSUE THREAD

**Issue by BillyKidThemes** [reduxframework/redux-extensions#185]
Hi,

Thanks for reduxframework and premium extensions - this is great timesaver. However I have one issue with redux metaboxes extensions. I use it in theme to store some values for custom post type 'portfolio' e.g hover image for thumb, size of thumb in portfolio grid and so on. During pageload it goes in loop through portfolios and gets stored values like described here:

http://docs.reduxframework.com/extensions/metaboxes

`$value = redux_post_meta( "OPT_NAME", "THE_POST", "META_KEY" )`

it all works fine and proper values that were stored during portfolio edit are returned.
The problem is with ajax callbacks. Like any other themes I have "Load More" button at the end of portfolio grid which loads more items when user clicks on it. Ajax callbacks itself are working fine and are coded according to wordpress codex standards:

https://codex.wordpress.org/AJAX_in_Plugins#Ajax_on_the_Viewer-Facing_Side

the problem is that redux_post_meta() function returns NULL ( Yes - I know about the fact that redux metaboxes do not store default values and those values are removed to free up the space ) instead of value stored for given portfolio/post. Post/portfolio loaded during regular loop (WP Query) on pageload returns proper value while the same post being loaded via ajax call returns NULL when `redux_post_meta( "OPT_NAME", "THE_POST", "META_KEY" )` is used. Please consider this pseudocode:

```php
add_action( 'wp_ajax_my_action', 'ajax_callback' );
add_action( 'wp_ajax_nopriv_my_action', 'ajax_callback' );

function ajax_callback() {
get_portfolios();
exit;
}

function get_portfolios() {
global $post; 
$query = new WP_Query( 'post_type=portfolio' );

while ( $query->have_posts() ) {
    $query->the_post();
    $value = redux_post_meta( "OPT_NAME", $post->ID, "META_KEY" );
}
wp_reset_postdata();
}
```

In the code above if function get_portfolios() is being executed during initial page load $value inside while loop is returned properly but if the same function is being executed via ajax_callback function which is triggered from the frontend after the page is fully loaded ( e.g ajax call after hitting "Load More" button ) it returns NULL instead of saved value for the same posts/portfolios. 

My question is:
Am I missing something?
Do You have the same issue and if so is it planned to be fixed in future?
If not do You have any workaround for getting proper values during ajax call for posts/portfolios stored by redux metaboxes?

Thanks in advance for response.

BR

**Comment by BillyKidThemes** [comment]
Generated support url with all details:

http://support.redux.io/?id=NdPM4oVc51i8MBTCDl%2Bv8lvyvl%2BQi%2FzC%2BaKqvCzIz%2F1i%2FMto5bWsy7JbQMXdyT3USPumB0hMdD9kLaA83lSYUQ%3D%3D

I'm developer and I'm using redux as a theme option panel/page/post/custom post type settings ( via redux metaboxes) bundled with my theme.

BR

**Comment by dovy** [comment]
Are you using the Redux API? If so, run this before you try the rest of your code:

```
Redux::init( 'OPT_NAME' );
```

**Comment by BillyKidThemes** [comment]
Hi,

Sorry for late response. Yes - I've switched to Redux API recently and rewritten my code to use it as described here:

https://github.com/reduxframework/redux-framework/blob/master/sample/sample-config.php

I also added:

`Redux::init( 'OPT_NAME' );`

in the proper place to force Redux Init ( at the top of ajax_callback function from the example below ):

```
add_action( 'wp_ajax_my_action', 'ajax_callback' );
add_action( 'wp_ajax_nopriv_my_action', 'ajax_callback' );

function ajax_callback() {
Redux::init( 'OPT_NAME' );
get_portfolios();
exit;
}

function get_portfolios() {
global $post; 
$query = new WP_Query( 'post_type=portfolio' );

while ( $query->have_posts() ) {
    $query->the_post();
    $value = redux_post_meta( "OPT_NAME", $post->ID, "META_KEY" );
}
wp_reset_postdata();
}
```

unfortunately still during ajax call redux_post_meta function returns null while for the same posts inside regular loops on pageload redux_post_meta returns proper values. 

After digging into the metaboxes code it turned out that during ajax call when redux_post_meta is used - and function ReduxFramework_extension_metaboxes->get_values() is called:

```
...
function get_values( $thePost, $meta_key = "", $def_val = "" ) {
                // Override these values if they differ from the admin panel defaults.  ;)
            	
            	if ( in_array( $thePost->post_type, $this->post_types ) ) {
...
```

variable `$this->post_types` is empty array instead of `array('portfolio')` like during normal loop during page load. Going further it turns out that function 
`ReduxFramework_extension_metaboxes->init()` is never reached because inside ReduxFramework_extension_metaboxes construct method there is a code which returns early

```
// Only run metaboxes on the pages/posts, not the front-end
                global $pagenow;
                if ( $pagenow !== "post-new.php" && $pagenow !== "post.php" ) {
                    if ( is_admin() ) {
                        return;
                    }
                }
```

but even commenting this piece of code out and allowing all hooks and init function to be triggered like during normal pageload doesn't fix the issue.

Any ideas or hints would be great.

BR

**Comment by dovy** [comment]
Great digging dude. I can look at it this moment, but maybe towards the end of the week. Send me your code as is and give me exact steps to duplicate. dovy@redux.io.

Thanks!

**Comment by sinzii** [comment]
Hi there,

Any update on this issue? I just faced this issue but don't know to what to do next.

Thanks,

**Comment by guicara** [comment]
Any update on this issue?

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!

**Comment by oliver-graetz** [comment]
This cannot work correctly in the current version. The code was changed from

```php
// correct implemenation
if ($pagenow !== "post-new.php" && $pagenow !== "post.php") {
    if (is_admin() && (!defined('DOING_AJAX') || !DOING_AJAX)) {
        return;
    }
}
```

to

```php
// broken implemenation
if ( is_admin() ) {
    if (defined('DOING_AJAX') && !DOING_AJAX) {
        return;
    }
    return;
}
```

which makes the inner `if` completely useless. Thie code is logically identical to the very old one that created this issue in the first place:

```php
if ( is_admin() ) {
    return;
}
```

meaning that the `DOING_AJAX` part currently adds no logic whatsoever. I think that the change in the code was meant to simplify the condition. But that turned out wrong. The older version was
the correct way to do this.

**Comment by kprovance** [comment]
I hate to disagree with you, but I wrote a theme that required ajax to work with metaboxes...and the way I fixed it works.  Look, if you have to change code so it works for your needs, go for it.  You also have to remod every future update.  The 'correct' implementation allows for other admin pages to get through.  There is a ticket here that talked about it.  I'm sorry, but U can't make this change, because it will break other themes who do this, but as I said, make the mode you want.  If other things break, you'll be on your own.  That's just how it works.

Wanna chime in on this, please, @dovy?

**Comment by oliver-graetz** [comment]
This code:

```php
if ( is_admin() ) {
    if (defined('DOING_AJAX') && !DOING_AJAX) {
        return;
    }
    return;
}
```

is logically IDENTICAL to:

```php
if ( is_admin() ) {
    return;
}
```

because whatever happens inside that if, it will always be a `return`. There is also no room for any side effects within `defined('DOING_AJAX') && !DOING_AJAX` because those a both read operations on immutable data. So whatever fixed your problem it is not this:

```php
if (defined('DOING_AJAX') && !DOING_AJAX) {
    return;
}
```

What could almost definitely have fixed the problem is this:

```php
if (is_admin() && (!defined('DOING_AJAX') || !DOING_AJAX)) {
    return;
}
```

Because that code will stop executing the metabox plugin init for all admin pages UNLESS the request is via AJAX.

**Comment by guicara** [comment]
Olivier, I agree with you. The "old" code was the only one that could fix this issue.

**Comment by dovy** [comment]
Hmm, I'll have to test this out.  ;)

**Comment by carmoreira** [comment]
It seems I can only get redux_post_meta() to work inside an ajax call in the frontend if I change that code back to

` if ($pagenow !== "post-new.php" && $pagenow !== "post.php") {
                    if (is_admin() && (!defined('DOING_AJAX') || !DOING_AJAX)) {
                        return;
                    }
                }`

**Comment by dovy** [comment]
So the change broke it for the front-end. Oy.

**Comment by kprovance** [comment]
Change it back and things are gonna break.  Don't say I didn't warn you.  ;)
