### ISSUE TITLE
Fields in Repeater aren't validating

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-extensions#187]
Hi,
I have a Repeater inside of a Metabox attached to a post that has fields with ```'validate' => 'not_empty'``` set, but when I save the post, the validator isn't being run.  I'm not getting any errors messages if the fields are empty.  If I take the field out of the Repeater and just put it in the Metabox, it works fine.

**Comment by dovy** [comment]
Probably correct. No validation can be run within the repeater. We COULD can add that in, but oy the complexity. It would be a lot of effort for a little gain.

Can you get by without it?
