### ISSUE TITLE
Output for color field not working within metabox on a custom post type

### ISSUE THREAD

**Issue by jamesdbruner** [reduxframework/redux-extensions#188]
I'm running into the same issue found here #95 but mine was not resolved in the updated version of the extension.  I've set `query_var => false` and I have the permalinks set to `/%postname%/`

Here's part of my options-init.php where I setup the color field
```
array(
'id'       => 'timer-color',
'type'     => 'color', 
'title'    => __('Timer Color', 'wpvegas'),
'transparent'   =>  false,
'output'   => array('background-color' => '.vegas-timer-progress'),
'validate' => 'color',
'default'  => '#FFFFFF',
),
```
This is what it outputs `<style type="text/css" title="dynamic-css" class="options-output">.vegas-timer-progress{background-color:#FFFFFF;}</style>`

Redux: v3.5.4.8
Metabox v1.3.0
WP v4.2.2

![example](https://cloud.githubusercontent.com/assets/1911608/7556450/a0f79008-f72d-11e4-81fc-62c07b9ea3db.png)
![example2](https://cloud.githubusercontent.com/assets/1911608/7556456/c6cc5b38-f72d-11e4-9947-94fca7cdbabd.png)

^ this clearly should not output #FFFFFF, any idea what I'm doing wrong?

**Comment by jamesdbruner** [comment]
Ahh sorry, I should have posted the support hash as well.  http://support.redux.io/?id=0NJ1K%2BvqvRVTLe4p3ya6UCZv0APpSNIWGuY8Ey0epfuUY6t%2Ff7cLNAbGYoabOp2L3Zz5y98ZLrepaEbeFWBknw%3D%3D

**Comment by jamesdbruner** [comment]
Any luck or am I on my own on this one?

**Comment by dovy** [comment]
Sorry, my wife is out of town and I'm taking care of our 5 kids under 7 on my own. Heh. I'll get to this as I am able. My apologies.

**Comment by jamesdbruner** [comment]
Oh don't worry about it man! I just noticed that it'd been almost a month without a response so I thought I'd check in.  I appreciate the work you guys put into redux, you're awesome.

**Comment by dovy** [comment]
Heh, yea. It's been crazy... https://ideas.reduxframework.com/campaigns/complete-customizer-integration/ 

That's been keeping me busy...

**Comment by jamesdbruner** [comment]
Possibly a stupid question about that, and I'm sorry this isn't on topic for this github issue but will that customize integration also be for plugins that are built with redux?  If so will there be a way to disable that?

**Comment by dovy** [comment]
Yup. There's a global arg for customizer. Set that to false and it's off. ;)

**Comment by taksu** [comment]
Hi, 
@jamesdbruner in case you didn't already got it work, this is what I did. Works at least with default post type.
In extension_metaboxes.php modify line 118 to:
<pre>
<code>               
if ( is_admin() ) {
      $this->post_id  = $this->url_to_postid( ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] );
} else {
      $this->post_id  = url_to_postid( ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] );
}
</code></pre>
Hope this works for you too!

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
