### ISSUE TITLE
Social profiles throws javascript error; customization box not displaying

### ISSUE THREAD

**Issue by jfc4** [reduxframework/redux-extensions#190]
Just purchased and installed the Social Profiles extension. Copied an example field to test it out, could see the icons I included, but got a javascript error upon activating an icon (when the class "enabled" was added. 

Also the customization box that should allow me to add a URL, change the icon color, etc. did not display, probably due to the error.

Error: `TypeError: el.find(...).spectrum is not a function`, referring to Line 264 of fields_social_profiles.js, which begins with:

`el.find( '.redux-social-profiles-color-picker-' + key ).spectrum(`

I'm wondering if a script for the spectrum library is missing.

**Comment by dovy** [comment]
@kprovance just saw that the other day and just needs to upload the new version.

Kevin, upload your update! Someone needs it.  :P

**Comment by kprovance** [comment]
Updated the extension to v1.0.3, which resolve this dep issue.  :)

**Comment by jfc4** [comment]
Unfortunately the social profiles aren't working at all now. I am unable to select any icons and the customization box still doesn't appear.

Never mind, I'm going to put in a request for a refund.

**Comment by dovy** [comment]
Umm, please be more patient here. Kevin will push a functioning release tomorrow.

**Comment by kprovance** [comment]
In order for us to begin debugging your issue, we need you to first generate a support URL. You can learn about how you generate that here: http://docs.reduxframework.com/core/generating-a-support-hash/  

Second, please open the javascript debug console and report back any errors that might appear there.

**Comment by jfc4** [comment]
Here's the support URL: http://support.redux.io/?id=35ddHJaPjCgWXGUx14sXtitdih%2BVdOE6fYv9EIlA26MG28td6qwz5ekiekj98j3RC26fc8XtJ10v04eWW%2FLPVQ%3D%3D

No errors on the js console

**Comment by kprovance** [comment]
Please upgrade to Redux v.3.5.4.9 from our repo.

**Comment by jfc4** [comment]
Sorry, I need to use the most recent stable version, not a development branch.

**Comment by dovy** [comment]
He's asking you to at least test it. Because it's working on our end, and we want to see if we changed something.

**Comment by jfc4** [comment]
@dovy I realize that. But I purchased this extension to save myself time; it has now cost me more in time to deal with these bugs.

I don't have any more time to put into this.

**Comment by dovy** [comment]
@jfc4 We cannot reproduce your issue. We're guessing it may be your environment. It shouldn't take you but a moment to replace your ReduxCore folder to see if the issue is there...

**Comment by jfc4** [comment]
@dovy The issue is resolved using the new Redux Core folder.

**Comment by dovy** [comment]
Ok then. Are you using this for ThemeForest or WP.org? Because the current beta is fully bulletproof.  ;)

Just uses CDN for some stuff instead of keeping it in the core.

**Comment by jfc4** [comment]
Neither. I'll be selling the theme myself. If you release a new stable version by the end of May then I should be all set.

**Comment by dovy** [comment]
We're for sure have it before then. We're just trying to work out the CDN requirements to comply with WP.org is all. Otherwise we would have released already as it's perfectly stable as is.  ;)

**Comment by jfc4** [comment]
Ok, thanks.

**Comment by girlscancode** [comment]
Hi there, I just purchased this extension, I am on ReduxFramework 3.5.6.1 - but the social icons are still not appearing - any idea about what I can do?

Best, 
Gabriela
