### ISSUE TITLE
Checkbox description field not lining up in Metabox

### ISSUE THREAD

**Issue by davidcasey** [reduxframework/redux-extensions#191]
The description (desc) is not lining up with the single checkbox as specified in the API. Rather, it is placing it below. (This is in a metabox.) I'd be happy to use a Multi Checkbox, which lines up correctly. However, I need to require it as checked, and apparently that is not supported: https://github.com/reduxframework/redux-framework/issues/1629
```
array(
    'id'       => 'opt_checkbox',
    'type'     => 'checkbox',
    'title'    => __('Checkbox Option', 'redux-framework-demo'),
    'subtitle' => __('No validation can be done on this field type', 'redux-framework-demo'),
    'desc'     => __('This is the description field, again good for additional info.', 'redux-framework-demo'),
    'default'  => '1'// 1 = on | 0 = off
)
```
![screen shot 2015-05-14 at 11 25 54 am](https://cloud.githubusercontent.com/assets/744677/7637633/891affa4-fa2c-11e4-9ddb-d98bd308d13a.png)

**Comment by dovy** [comment]
Descriptions are always below a field. If you would like to produce a label for a checkbox, you'd do:
```
array(
    'id'       => 'opt_checkbox',
    'type'     => 'checkbox',
    'title'    => __('Checkbox Option', 'redux-framework-demo'),
    'subtitle' => __('No validation can be done on this field type', 'redux-framework-demo'),
    'options' => array( 1 => 'Label' ),
    'desc'     => __('This is the description field, again good for additional info.', 'redux-framework-demo'),
    'default'  => '1'// 1 = on | 0 = off
)
```

At least I believe that would work. Give it a try, hah.

**Comment by davidcasey** [comment]
Yeah, that works for the label. But now we have entered into the Multi Checkbox and we can't assign required to it. (See answer to this issue: https://github.com/reduxframework/redux-framework/issues/1629 ) Your API here http://docs.reduxframework.com/core/fields/checkbox/ shows the description inline with the Single Checkbox.

I am building a  physical/mailing address metabox. Clicking this checkbox ("Mailing address different than physical address?") will allow the mailing form to become visible.

**Comment by dovy** [comment]
Set multi => false,

If that doesn't work use `contains` instead of `=` for your required test.  ;)

**Comment by davidcasey** [comment]
Neither worked (just `'multi' => false`, just `contains`, nor both together) I looked in field_checkbox.php and found `isset ( $this->field[ 'multi_layout' ] )` not sure what that does without really looking through the code, but I tried `'multi_layout' => false` just in case that was the key ... alas no joy.

**Comment by dovy** [comment]
Can you try in a typical panel? If not it's a bug in required.

**Comment by davidcasey** [comment]
I've confirmed, the bug occurs both in Metabox and the typical panel.
```
      array(
        'id'                => 'checkbox_require_test',
        'title'             => 'Metabox Checkboxes with options don\'t work with required.',
        'sections' => array(

          array(
            'id'              => 'foobar',
            'title'           => 'Required Checkbox Test',
            'fields' => array(
                array(
                  'id'       => 'opt_checkbox',
                  'type'     => 'checkbox',
                  'title'    => __('Checkbox with \'option\' set (Doesn\'t Work)', 'redux-framework-demo'),
                  'options'  => array( 1 => 'Label' ),
                  'multi'    => false,
                ),

                array(
                  'id'          => 'foo',
                  'required'    => array( 'opt_checkbox', 'contains', 1),
                  'type'        => 'text',
                  'title'       => __( 'foo' ),
                  'placeholder' => __( 'foo' ),
                ),

                array(
                    'id'       => 'opt_checkbox_2',
                    'type'     => 'checkbox',
                    'desc'     => 'Needs a label',
                    'title'    => __('Single Checkbox (This works)', 'redux-framework-demo'),
                ),

                array(
                  'id'          => 'bar',
                  'required'    => array( 'opt_checkbox_2', '=', 1),
                  'type'        => 'text',
                  'title'       => __( 'bar' ),
                  'placeholder' => __( 'bar' ),
                ),
            )
          )
        )
      )
```
