### ISSUE TITLE
about repeater

### ISSUE THREAD

**Issue by MutamizTeam** [reduxframework/redux-extensions#194]
sorry i'm beginner
if i buy the repeater extension i will include in theme will be sold on themeforest
is this legal

**Comment by dovy** [comment]
Correct!

We basically ask you to buy a copy of any extension you wish to use for each theme you wish to sell it in.

It's the same as an extended license on Code Canyon.  ;)

Best of luck!

**Comment by MutamizTeam** [comment]
thanks for help  just to clarify after buy this is there email permission to use it in my theme
