### ISSUE TITLE
repeater nested

### ISSUE THREAD

**Issue by MutamizTeam** [reduxframework/redux-extensions#195]
hello 
i'm purchase the repeater extension  today
i have small problem  need to set nested elements the required args not working
this is code ->>>
array(
            'id'         => 'repeater-field-id',
            'type'       => 'repeater',
            'title'      => __( 'Add new home block', 'redux-framework-demo' ),
            'subtitle'   => __( '', 'redux-framework-demo' ),
            'desc'       => __( '', 'redux-framework-demo' ),
            'fields'     => array(
                array(
                    'id'          => 'mut-hblock-title',
                    'type'        => 'text',
                    'placeholder' => __( 'Block Title', 'redux-framework-demo' ),
                   ),
          array(
            'id'       => 'opt-hblock-type',
            'type'     => 'button_set',
            'title'    => 'Choose Block Type',
            'options'  => array(
                'news-box'     => 'News Box',
                'button-textarea' => 'Show Textarea Field',
                'button-editor'   => 'Show WP Editor',
                'button-ace'      => 'Show ACE Editor'
            ),

            'default'  => 'button-text'
        ),
                array(
                    'id'          => 'text_field',
                    'type'        => 'text',
                    'placeholder' => __( 'Text Field', 'redux-framework-demo' ),
                    'required' => array( 'opt-hblock-type', 'equals', 'button-editor' ),
                ),

**Comment by kprovance** [comment]
The required feature does not work within the repeater fields.  This is by design.

**Comment by dovy** [comment]
Maybe some time in the future, but not now. Sorry.
