### ISSUE TITLE
Icon Select - stylesheet error - blank element +dropmenu idea

### ISSUE THREAD

**Issue by zagarskas** [reduxframework/redux-extensions#196]
To duplicate minify http://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css
and use that as follows 

    'stylesheet' => get_bloginfo('template_directory').'/css/fontawesome.css', 

has some issues, seems as if it does not want to parse the first lines of FontAwesome, or any minified CSS properly. causes no errors in error_log, just end up with this odd blank space at begenning, of course, selecting that blank space causes havoc on the front end...

![image](https://cloud.githubusercontent.com/assets/859427/7905639/b33520e2-07e9-11e5-867e-53284e7c04e7.png)

To my horror, this is whats dumping into the icon VALUE
![image](https://cloud.githubusercontent.com/assets/859427/7905663/2287f866-07ea-11e5-8023-4144be7e36cb.png)

PS: as a note of course I was easily able to fix this by removing the @font-face and .fa-stack lines, ect... and splitting it into 2 CSS files. I think there are only like 4 or 5 good icon sets, maybe just include them by default to prevent the fubar?

Other than that, really COOL, seriously neat extension, would be great to have a new option that lets us select between the "big box" and the elegant drop menu item here:
http://demo.redux.io/wp-admin/admin.php?page=_options&tab=35
Note how the Elusive Icons Select Option lets us use a simple "search" drop menu select/select2 feature. something like this would be good:

    'type' => 'icon_select_big_box', // choose between icon_select_select, icon_select_select2

![image](https://cloud.githubusercontent.com/assets/859427/7905711/54966f12-07eb-11e5-8358-13e42a88c366.png)

**Comment by kprovance** [comment]
Post back a support URL, please.  :)

**Comment by zagarskas** [comment]
I do not understand what you mean by this? There is no support URL I know of... 
To duplicate this issue please minify 
http://fortawesome.github.io/Font-Awesome/assets/font-awesome/css/font-awesome.css
and attempt to use it within the Icon Select extension as the style-sheet variable value.

On doing so you will see extra blank icon spaces at the top and bottom of the icon box.

Please elaborate if I need to provide more information.
I purchased the extension here:
https://reduxframework.com/extension/icon-select/
and the Support link on that page brought me here
https://github.com/reduxframework/redux-extensions

**Comment by dovy** [comment]
This is what we mean by support URL:

https://docs.reduxframework.com/core/generating-a-support-hash/

It helps us debug your issue.  :)

**Comment by zagarskas** [comment]
I understand. I resistant to generate a support hash for this issue as I feel it can easily be duplicated by following the scenario above and I have an interest to protect the anonymity of my clients for security reasons, however, if I must conform to such a request I will...
provided you can please confirm the following with Y/N:
Will generating this support hash include any specific information about the Redux install such as but not limited to the server IP or the domain?

If yes, then I will duplicate this issue somewhere I deem to be safe to disclose.
thank you for your consideration in this matter.

**Comment by dovy** [comment]
@zagarskas Look at the status tab inside the Redux menu item to see what is sent in addition to your Redux config.

We're not taking advantage of you here. There may be additional items you may not be sure of, and we'd like to save us all time debugging that.  ;)

**Comment by zagarskas** [comment]
I have reviewed the status tab and this is the kind of information I am under contract to do all I can to prevent from leaking onto the internet.

As of now my patch is working and I am writing my own mod to the 
elusive-icons.php and field_select.php fields as a custom extension to exceed my expectations of Icon Select

when the opportunity presents I will duplicate the site on a staging ground and send you the hash as requested.
thank you for your assistance, this is not a critical matter.

**Comment by dovy** [comment]
@zagarskas ok. Please do share your code when you have it. It will help others.  :)

We'll close this for now until then.
