### ISSUE TITLE
Instructions to install Redux extensions Mettaboxes (and others) - NOT ISSUE

### ISSUE THREAD

**Issue by zagarskas** [reduxframework/redux-extensions#197]
I was rather confused on the instructions to install the Metaboxes 
I thought this post might help someone. 

If I am putting these in the wrong place/folder please correct me.

today's date: 6/3/2015 (if this becomes deprecated I will delete this post)

Versions I am using:
REDUX: 3.5.4.3

This works for and has been tested on the following.
* metaboxes-1.3.0 
* icon_select-1.0.5
* social-profiles-1.0.3
* accordion-1.0.1
* icon_select-1.0.5
* repeater-1.0.3

----------------------------------------------------------
**1) I ignore instructions included within the extensions**
(I suspect they may be outdated, if not they confused the ASYNC out of me)

**2) Whenever I unzip an extension I grab only the folder**
I ignore the config and loader, I don't put those anywhere, especially not in the extensions folder
![image](https://cloud.githubusercontent.com/assets/859427/7952611/5665677a-0986-11e5-87ef-bb1098097c92.png)

**3) inside that folder I take this (for Mettabox)**

![image](https://cloud.githubusercontent.com/assets/859427/7952623/81a0a170-0986-11e5-974c-86f353c9a52b.png)

**In other extensions I take this folder AND this file**

![image](https://cloud.githubusercontent.com/assets/859427/7952626/9da862d6-0986-11e5-949c-3d6f8952bfd5.png)

**4) I grab those and drop them in here like this**

![image](https://cloud.githubusercontent.com/assets/859427/7952654/125bb2d6-0987-11e5-8d16-4af530cf10ff.png)

I Notice how /redux-extensions/ folder seems to not be used...
I Notice how metaboxes has only files while social_profiles has files AND a folder
I could not get any of the extensions to work any other way

Since I have received so much copy/paste from OS communities online I thought I would share

* A) **REDUX admin-init.php is included in the basic functions.php** file like so

```php
// Load the embedded Redux Framework
if (file_exists(dirname(__FILE__).'/redux-framework/framework.php')) {
    require_once( dirname(__FILE__).'/redux-framework/framework.php' );
}


// Load the theme/plugin options
if (file_exists(dirname(__FILE__).'/options-init.php')) {
    require_once( dirname(__FILE__).'/options-init.php' );
}
```
   
* B) the code below is included in the basic **functions.php file AFTER  admin-init.php**

```php
/////////////////////////////////////////////////// begin STANDARD WP CUSTOM POST TYPE
function create_acmeexample_post_type() {
	$labels = array(
		'name' => __( 'acmeexample Pages','my_theme'),
		'singular_name' => __( 'acmeexample Page','my_theme' ),
		'add_new' => __('Add New ','my_theme'),
		'add_new_item' => __('Add New acmeexample','my_theme'),
		'edit_item' => __('Edit acmeexample','my_theme'),
		'new_item' => __('New acmeexample ','my_theme'),
		'view_item' => __('View acmeexample ','my_theme'),
		'search_items' => __('Search acmeexamples','my_theme'),
		'not_found' =>  __('None found','my_theme'),
		'not_found_in_trash' => __('None found in Trash','my_theme'), 
		'parent_item_colon' => ''
	  );
	  $args = array(
		'labels' => $labels,
		'public' => true,
		'exclude_from_search' => false,
		'publicly_queryable' => true,
		'show_ui' => true, 
		'query_var' => true,
		'menu_icon' => 'dashicons-welcome-view-site',
		'capability_type' => 'page',
		'hierarchical' => false,
		'show_in_menu' => true,
		'menu_position' => 22,
		'supports' => array('title'),
		'rewrite' => array( 'slug' => __('my-url', 'my_theme') )
	  ); 
	  register_post_type('acmeexample',$args);
}
add_action( 'init', 'create_acmeexample_post_type' );
/////////////////////////////////////////////////// end STANDARD WP CUSTOM POST TYPE

	
/////////////////////////////////////////////////// begin REDUX METTA
if ( !function_exists( "redux_add_metaboxes" ) ):
    function redux_add_metaboxes($metaboxes) {
    $boxSections[] = array(
        'title' => __('Home Settings', 'my_theme'),
        'icon' => 'el-icon-home',
        'fields' => array(  
           
            array(
                'id'=>'switch-on',
                'type' => 'switch', 
                'title' => __('Switch On', 'my_theme'),
                'subtitle'=> __('Look, it\'s on!', 'my_theme'),
                "default"       => 1,
                ),  

            array(
                'id'=>'switch-off',
                'type' => 'switch', 
                'title' => __('Switch Off', 'my_theme'),
                'subtitle'=> __('Look, it\'s on!', 'my_theme'),
                "default"       => 0,
            ),  
        )
    );

    $boxSections[] = array(
        'title' => __('Home Layout', 'my_theme'),
        'icon' => 'el-icon-home',
        'fields' => array(  
            array(
                'id'=>'slides',
                'type' => 'slides',
                'title' => __('Slides Options', 'my_theme'),
                'subtitle'=> __('Unlimited slides with drag and drop sortings.', 'my_theme'),
                'desc' => __('This field will store all slides values into a multidimensional array to use into a foreach loop.', 'my_theme')
            ),        
           
                                                            
        ),
    );

    $metaboxes = array();

    $metaboxes[] = array(
        'id' => 'demo-layout',
        'title' => __('Cool Options', 'my_theme'),
        'post_types' => array('page','post', 'acmeexample'),
        'position' => 'normal', // normal, advanced, side
        'priority' => 'high', // high, core, default, low
        'sections' => $boxSections
    );
    $boxSections = array();
    $boxSections[] = array(
        'icon_class' => 'icon-large',
        'icon' => 'el-icon-home',
        'fields' => array(
            array(
                'title'     => __( 'Layout', 'my_theme' ),
                'desc'      => __( 'Select main content and sidebar arrangement. Choose between 1, 2 or 3 column layout.', 'my_theme' ),
                'id'        => 'layout',
                'default'   => 1,
                'type'      => 'image_select',
                'customizer'=> array(),
                'options'   => array( 
                0           => ReduxFramework::$_url . 'assets/img/1c.png',
                1           => ReduxFramework::$_url . 'assets/img/2cr.png',
                2           => ReduxFramework::$_url . 'assets/img/2cl.png',
                3           => ReduxFramework::$_url . 'assets/img/3cl.png',
                )
            ),
        )
    );
  
    $metaboxes[] = array(
        'id' => 'demo-layout2',
        'post_types' => array('page','post', 'acmeexample'),
        'position' => 'side', // normal, advanced, side
        'priority' => 'high', // high, core, default, low
        'sections' => $boxSections
    );


    $page_options = array();
    $page_options[] = array(
        'icon_class'    => 'icon-large',
        'icon'          => 'el-icon-home',
        'fields'        => array(
            array(
                'id' => 'sidebar',
                'title' => __( 'Sidebar', 'fusion-framework' ),
                'desc' => 'Please select the sidebar you would like to display on this page. Note: You must first create the sidebar under Appearance > Widgets.',
                'type' => 'select',
                'data' => 'sidebars',
                'default' => 'None',
            ),
        ),
    );

    $metaboxes[] = array(
        'id'            => 'page-options',
        'title'         => __( 'Page Options', 'fusion-framework' ),
        'post_types'    => array( 'page', 'post', 'demo_metaboxes' ),
        'position'      => 'normal', // normal, advanced, side
        'priority'      => 'high', // high, core, default, low
        'sidebar'       => false, // enable/disable the sidebar in the normal/advanced positions
        'sections'      => $page_options,
    );


    return $metaboxes;
  }
  add_action('redux/metaboxes/'.$opt_name.'/boxes', 'redux_add_metaboxes'); //<---------- update the $opt_name
endif;
/////////////////////////////////////////////////// end REDUX METTA
```

cheers.
I hope this saves someone time. Once I did that it was gravy.
I am very impressed with this system and somewhat baffled by docs.reduxframework.com

**Comment by kprovance** [comment]
You do understand that by putting those files inside the redux-framework folder - and if NOT using an embedded solution (meaning, Redux used as plugin), anything there will be removed on plugin update.  And, sorry you 'baffled' by our docs site.  Considering the hundreds of hours I put into most of it, offering cut and paste examples - dummy proofing it, if you will - I'll try not and take it personally.

**Comment by dovy** [comment]
But the included docs are very VERY much lacking. I need to fix that. ;)

**Comment by dovy** [comment]
Meaning in the zips.

**Comment by zagarskas** [comment]
kprovance
As an on-board developer I suspect that your knowledge of the documentation makes it easy for you, I would suggest the following exercises, I think they would be enlightening:

**proposed experiment**
A) pretend you know nothing of the system and only have agood knowledge of PHP, try to install Redux and the extensions following the documentation
B) have a fellow PHP developer who has never used REDUX before do it in front of you, say nothing, watch them read the documentation and offer no support, simply observe their behavior, what they read, and the end results.

**my experience**
Here is an example timeline to consider for someone who was new:
Please take a moment to recreate this experience, I prefer to think one may gain insight from it...

* On May 28th I downloaded Redux, it took me 3 hours to discover how to install it because this page
https://docs.reduxframework.com/
has no explanation on how to install.
* Click on "launch the redux builder" where does it take you?
This is where it takes me: https://build.reduxframework.com/?_ga=1.11112372.1249188586.1432806526?_ga=1.11112372.1249188586.1432806526
* When I did finally find out where the builder was and downloaded it only a few of the options I exported worked properly, for example, the demo mode I seleted as OFF, but it was ON. A quick fix, I simply read through the code. eventually I dumped the builder version and downloaded from GIT after other issues
* Several hours later after I cleared my PHP error logs from failed include statements I bought 5 plugins (one at a time) and to my dismay discovered paypal created yearly subscriptions which I immediately canceled as to not overdraft my bank account 1 year later...
* The first one I attempted to install was Social Profiles, where at no point in time on either of the following pages does it actually say where the heck to put the folder and files
    * https://reduxframework.com/extension/social-profiles/
    * https://docs.reduxframework.com/extensions/social-profiles/
* I then dug deeper and found this article, still, no clear file tree, video, or simple explanation as to where the extensions actually GO
    * https://docs.reduxframework.com/core/advanced/loading-extensions/
    * on this page above I follow the Getting started link, which takes me here
    * https://github.com/ReduxFramework/redux-extensions-loader
    * on that page I find misinformation and nothing to copy and paste, when I include "this" as per the instructions I get a blank WordPress admin screen with an error, so I removed the extension loader lines from admin-include and WP began to work again
    * this page also does not explain where ~/extensions IS, so, I began to read more... and more...
    * I added the loader.php and config.php files to the redux-extentions folder and WP crashed
    * I removed them and took the files in social_profiles out and moved them one level up, nogo
* this page was especially confusing: https://github.com/reduxframework/redux-extensions-loader/blob/master/README.md
because there is no such folder called: ~/ReduxCore/Extensions
either with that name nor that spelling

This process took approx 32 hours, at which time I was spent.
I slept and took another stab at it on 5/31
eventually I found the inc/extensions folder, and put them in there, things began to work...
Soon after I wrote a google_maps extension 
today I attempted to install the Mettabox extension, after a similar fail process I discovered what I assumed is the proper way, as shown above.

If this is not correct, please consider a video showing how to install the items, or, the proposed experiment above.

thank you for your consideration in this matter.

**Comment by JSW888** [comment]
Thank you, I spent about an hour trying to get this to work by following the documentation with no luck, this worked immediately. I agree that the documentation is very unclear when it comes to adding extensions. Since I'm embedding Redux directly, is there any downside to using this method?

**Comment by zagarskas** [comment]
I don't know, but I suspect (from what I have read) there is some potential incompatibility/override issue when another author uses REDUX in a plugin and we use it in the theme this way... directly embedded.

 I suppose one could test this like so:
+ embed directly into a theme (like this ^ at top)
+ make a wordpress plugin using redux and see if there are incompatibilities.

as stated above, I saw no other way to get the extensions working, so I am just assuming here...
worst case scenario one could always do a find and replace on the extension and add in a custom namespace just to make sure... very unorthodox but effective. (could also be a mess later)

**Comment by winwinwebdesign** [comment]
@kprovance If I might add, your docs are incredible! I've read through most of it and greatly appreciate the brilliant detail that goes into it.

I think these instructions are for embedding, which was a little tough since the generator link is broken.
