### ISSUE TITLE
Metaboxes cfg

### ISSUE THREAD

**Issue by Ronanzzzzzzzzzz** [reduxframework/redux-extensions#198]
Hi, i'm using a theme that use redux framework and i'm willing to add a post association with a post_type of my own.
So i've done it with page like that :
'fields' => array(
array(
'id' => 'post_association',
'type' => 'select',
'multi' => true,
'title' => __( 'Post Association', 'gp_lang' ),
'desc' => __( 'blabla bla.', 'gp_lang' ),
'data' => 'page',
'default' => ''
),

but when i replace 'page' to 'my_custom_posttype' i doesnt work, how should i do ?

**Comment by monstertheme** [comment]
Hey @Ronanzzzzzzzzzz and anyone who has this problem.

Post Types need to be assigned to the entire metabox, not a section.

So where you declare the metabox:

`$metaboxes[] = array(`
`        'id' => 'demo-layout',`
`        'title' => __('Options', 'unleash'),`
`        'post_types' => array('my_custom_posttype'),`
`        'position' => 'normal', // normal, advanced, side`
`        'priority' => 'high', // high, core, default, low`
`        'sections' => $boxSections`
`);`

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
