### ISSUE TITLE
Can I set the post_types used by metabox from the theme options?

### ISSUE THREAD

**Issue by liquidbook** [reduxframework/redux-extensions#199]
I am new to the reduxframework. Is there a way to set the supported post_types used by the config.php from a value set in the main ReduxFramework section array. 

I know that within $this->sections[] i can set a field value
array(
       'id'        => 'my-post-type-supported',
       'type'      => 'select',
       'data'      => 'post_type',
        'multi'     => true,
         'title'     => __('Post Type Supported', 'redux-framework-demo'),
),

Which lets me built an array of post_types. 
Can i then call this from within the config.php (metaboxes extension)? I can't use the global $opt-name['my-post-type-supported'] 

$metaboxes[] = array(
        'id'            => 'seo-options',
        'title'         => __( 'Page/Post Options', 'aq-framework' ),
        'post_types'    => $supported_post_types,
        'position'      => 'normal', /
        'priority'      => 'core', 
        'sidebar'       => false, 
        'sections'      => $page_options,
    );

—Thanks

**Comment by dovy** [comment]
You'd have to do a get_option to make that happen. It's entirely possible and shouldn't be too hard to do either.

**Comment by dovy** [comment]
Just grab the options and then the variable key before you declare the metabox.

**Comment by liquidbook** [comment]
Awesome dovy, that worked perfectly. Thanks for the fast reply.

Now a user can add the metabox that I have to their custom post_type — if needed. Here is my code for other readers.  

---in a field in options-init ----
array(
  'id'        => 'my-post-type-supported',
  'type'      => 'select',
  'data'      => 'post_type',
  'multi'     => true,
  'title'     => __('Post Type Supported', 'redux-framework'),
  'desc'      => __('This is the description field, again good for additional info.', 'redux-framework'),                      
  'default'   => array('post')
						),
--- at the start of the function in config.php ---
function redux_add_metaboxes($metaboxes) { 
    $my_options = get_option( 'opt-name'); //actually called something else
    $default_supported_types = array('post');
    $my_supported_types = ( is_array($my_options['my-post-type-supported'] ) ) ? $my_options['my-post-type-supported'] : $default_supported_types ;
...

--- metaboxes  setup in config.php ----
$metaboxes[] = array(
        'id'            => 'aq-post-options',
        'title'         => __( 'My Options', 'redux-framework' ), // called something else
        'post_types'    => $my_supported_types,
        'position'      => 'normal', // normal, advanced, side
        'priority'      => 'core', 
        'sidebar'       => false, 
        'sections'      => $postSections,
    );

**Comment by dovy** [comment]
Awesome.  :)
