### ISSUE TITLE
Can't download the custom fonts extension

### ISSUE THREAD

**Issue by guzun** [reduxframework/redux-extensions#202]
Hi there.

I've purchased custom fonts extension on April 21st.
Then I've canceled the subscription because the extension is for a friend and not for me.

We've integrated the extension into a theme and everything was working fine.

But now it always shows this error: "There was an error converting your font: You font could not be converted at this time. Please try again later."

I wanted to download the latest version maybe it solves the problem. But when I go to my account there is no download link.

Can you please send me the latest version (1.0.4) ?  

http://i.imgur.com/4KzwJeH.png

Thank you,
Alex

**Comment by kprovance** [comment]
Please contact me directly at kevin@reduxframework.com.  Please include the user ID you created when ordering the extension so I can verify.  I have an update, but it's not publicly available.  :)

**Comment by guzun** [comment]
I Kevin.
Thanks for getting back to me.

My user ID is alexg and the email is guzun.allex@gmail.com
The order ID is #2788



On Fri, Nov 20, 2015 at 7:35 PM, Kevin Provance <notifications@github.com>
wrote:

> Please contact me directly at kevin@reduxframework.com. Please include
> the user ID you created when ordering the extension so I can verify. I have
> an update, but it's not publicly available. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reduxframework/redux-extensions/issues/202#issuecomment-158468323>
> .
>



-- 
Best regards,
Alex

**Comment by kprovance** [comment]
You have to email ME.  It's a security thing.  :)
