### ISSUE TITLE
Step by Step extension install instructions

### ISSUE THREAD

**Issue by derekbvb** [reduxframework/redux-extensions#203]
Hi guys,

I have just purchased the Repeater extension.
As much as I have both read the instructions that are attached to the file and your documentation - 
I haven't found ANY easy to understand, copy-paste friendly instructions.
I got completely lost - where do I paste the loader.php ? Do I need to include it from my theme's functions.php (I am embedding redux in my theme) ?
What is {$redux_opt_name} ? the name of my variable ($redux_demo by default) ?
Anything else I need to do to finalize the installation?
All the explanations are SO fragmented and unclear.

Could you guys please provide a step-by-step, copy-pastable explanation?
I think it is both crucial and fair to anyone who buys an extension, to have that question comprehensively answered once and for all. 

Got the framework to work quickly and easily, but the extension installation process has been a nightmare so far.

Thank you! :-)

**Comment by kprovance** [comment]
Hi.  Please post extensions issues to the extension issue tracker here: https://github.com/reduxframework/redux-extensions/issues

Thanks.

**Comment by derekbvb** [comment]
Hi Kevin,
The link you have posted is exactly where this current message is appearing.
currently, under 'closed' tab.

**Comment by derekbvb** [comment]
OK got it to work :)
for anyone with the same issue - {$redux_opt_name} is "redux_demo" by default.
after you change that in loader.php,
include loader.php in your functions.php, right after including the framework, and right before  loading your config, like this:

// load the theme's framework
if ( !class_exists( 'ReduxFramework' ) && file_exists( dirname(__FILE__) . '/ReduxFramework/ReduxCore/framework.php' ) ) {
require_once( dirname(__FILE__) . '/ReduxFramework/ReduxCore/framework.php' );
}

if ( !isset( $redux_owd ) && file_exists( dirname(__FILE__) . '/ReduxFramework/sample/loader.php' ) ) {
require_once( dirname(__FILE__) . '/ReduxFramework/sample/loader.php' );
}

// load the theme's options 
if ( !isset( $redux_owd ) && file_exists( dirname(__FILE__) . '/ReduxFramework/sample/sample-config.php' ) ) {
require_once( dirname(__FILE__) . '/ReduxFramework/sample/sample-config.php' );
}



place your "extensions" folder in same folder as loader.php
I placed both in sample folder , as you can see above.

cheers.

**Comment by dovy** [comment]
You're right, we need to ship with better extension documentation! If you're using the new Redux API, it's TONS easier.

https://docs.reduxframework.com/core/redux-api/

```
Redux::setExtensions($opt_name, $path)
```

**Comment by derekbvb** [comment]
Hey @dovy the api way does sound easy :) didn't find it while searching for a solution though...
I have another question in regards to the Repeater -
How do I use the "required" argument on fields within a repeater?
I need some of the fields to only appear if a certain selection on a previous field has been made.
It is very crucial to my current project, and I believe is very much needed in general.

**Comment by dovy** [comment]
Required hasn't been built into the repeater field yet. I suppose it could be, but it hasn't had enough of a demand to warrant that effort yet I fear.  :(

**Comment by derekbvb** [comment]
@dovy 
Can I buy & incorporate the Accordion Extension into the repeater field, creating different inner field groups inside each element?

P.S. 
I really believe that the demand for the required option is there, people simply probably don't mention it (although I found a few posts here on the matter). Just think how invaluable this feature is in the general Redux use, so it is within this field (maybe even more than others, as with so many repeated elements the clutter of not having conditional fields may be worse :)

**Comment by kprovance** [comment]
Problem is, that would take a LOT of work, and we'd need financial backing since the extensions don't sell as well as we'd like.  Feel free to submit the idea to http://ideas.reduxframework.com  :)

Let me get back to you on the accordion question.  I need to give it a try and see.

**Comment by kprovance** [comment]
The answer is, they do not. Using extensions in the repeater field has been a tough issue, only a few work, and the ones that do needed a LOT of modification.
