### ISSUE TITLE
Required argument on fields within Repeater

### ISSUE THREAD

**Issue by derekbvb** [reduxframework/redux-extensions#204]
Opening a new thread solely for this question.

Hi Guys,

I have a question in regards to the Repeater -
How do I use the "required" argument on fields within a repeater?
I need some of the fields to only appear if a certain selection on a previous field (within same element) has been made.
It is very crucial to my current project, and I believe is very much needed in general.

**Comment by aonzzung** [comment]
This seems to be the same of my question here 
https://github.com/reduxframework/redux-extensions/issues/176

I think it doesn't support. Anyways, I haven't get any responses from the creators.

**Comment by dovy** [comment]
Oh sorry I haven't responded! My bad. Yes, it is not supported at this time due to the complexity.
