### ISSUE TITLE
New custom fields with Metaboxes extension for Taxonomy and User profile

### ISSUE THREAD

**Issue by PayteR** [reduxframework/redux-extensions#206]
Hi, its somehow possible to add metaboxes for taxonomy edit page (category, tag...) ? I need to add some new fields for tags. 

And its somehow possible add new fields to user profiles? For example CMB2 have this functionality https://github.com/WebDevStudios/CMB2/wiki/Adding-metaboxes-to-user-profile .

**Comment by kprovance** [comment]
At this time, metaboxes doesn't support these kinda of things.  It's been on our TODO list for sometimes, but as with all intense projects, it comes down to financial backing.  Dovy plans on doing it - at some point.  If we could get our community to back to to the tune of a few hundred bucks, it would happen WAY sooner, than later.  :)
