### ISSUE TITLE
Metabox fields doesn't generate custom css for custom post types or posts

### ISSUE THREAD

**Issue by jpcid** [reduxframework/redux-extensions#207]
Hi,

I've identified this issue by configuring in our theme a metabox for posts which allow to change navbar background color. If we try to access to the metabox field value, in any template, we get the modified value. But the fields which generate css are not adding the style to the page because url_to_postid function is returning 0 as post_id. However page post type generate custom css as expected.

I've changed url_to_postid implementation by the native one and works. Could you take a look to this? ~~$this->url_to_postid(...)~~ url_to_postid(...)

We are using version 1.2.9 because version 1.3.0 is not rendering correctly side metaboxes ... anyway same behaviour in 1.3.0.

I can send you a copy of our [theme](http://themeforest.net/item/themesy-responsive-multipurpose-wordpress-theme/10606401) if you want to reproduce this issues easily.

Best Regards Team

**Comment by kprovance** [comment]
How are you registering your post type?  Init hook?  If so, that's why (I just went through this with my theme).  Load the post type with the init hook.  Outputting will work then.

**Comment by jpcid** [comment]
Thx for your fast response :)

Yep we are registering our post types with Init hook. But posts ... that's native post type and we are having this issue with it too.
