### ISSUE TITLE
Trouble getting Redux Framework color scheme extension working

### ISSUE THREAD

**Issue by robbiereynolds** [reduxframework/redux-extensions#209]
I'm using Redux Framework embed in theme and used the Redux generator. My theme folder structure is as follows:

![redux_framework_folder_structure](https://cloud.githubusercontent.com/assets/1855428/8507586/e7fad608-2217-11e5-83fd-b6ae2fc2e793.PNG)

... and this is what is showing in options panel

![redux_framework_color_scheme_extension_not_showing](https://cloud.githubusercontent.com/assets/1855428/8507573/397a8060-2217-11e5-8dda-2cb36cb41736.png)

... and this is the code for the field

```php
array(
                'id'            => 'theme-color-scheme',
                'type'          => 'color_scheme',
                'title'         => 'Color Schemes',
                'subtitle'      => 'Save and load color schemes',
                'output'        => true,
                'compiler'      => true,
                'simple'        => false,
                'groups'   => array(
                    'Header' => array(
                        'desc'              => 'Set header and nav colors here. (Group open by default)',
                        'hidden'            => false,
                        'accordion_open'    => true
                    ),                    
                    'Body'   => 'Set body and content colors here.',
                    'Widget' => '',
                    ''       => 'These colors are not asigned to any group.'
                ),
                'default'       => array(
                    array(
                        'id'        => 'body-text', // ID
                        'title'     => 'body text', // Display text
                        'color'     => '#fdfdfd',   // Default colour
                        'alpha'     => 1,           // Default alpha
                        'selector'  => 'body',      // CSS selector
                        'mode'      => 'color',     // CSS mode
                        'important' => true,         // CSS important
                        'group'     => 'Body'       // Optional group name
                    ),
                    array(
                        'id'        => 'body-background',
                        'title'     => 'body background',
                        'color'     => '#ededed', 
                        'alpha'     => .5,
                        'selector'  => 'body',
                        'mode'      => 'background-color',
                        'important' => false,
                        'group'     => 'Body'
                    ),
                ),
            ),
```

**Comment by kprovance** [comment]
The folder structure is incorrect.  It needs to be setup like this:

![ext_folders](https://cloud.githubusercontent.com/assets/3412363/8509143/64cb00de-2260-11e5-908d-5af56db75c25.png)

**Comment by dovy** [comment]
We'll be adding better documentation soon.  :P

**Comment by robbiereynolds** [comment]
Now that I've got the extension to display in the options panel, it is not rendering the color picker, nor are the accordion tabs opening/closing. It's seems to be a JS issue, but there are no js errors in Chrome console.

![redux_framework_extensions_color_schemes_color_picker_not_showing](https://cloud.githubusercontent.com/assets/1855428/8510671/d17de7ca-22c2-11e5-8842-cc3810eb0869.png)

The suggested folder structure that was mentioned by kprovance still did not work for me. Here is the folder structure that ended up working.

![redux_framework_extension_color_schemes_folder_structure](https://cloud.githubusercontent.com/assets/1855428/8510690/e4e73626-22c3-11e5-8890-f5140b819e79.PNG)

**Comment by kprovance** [comment]
Updated your copy of Redux to the one from our git.  The current wp.org version is out of date.  And in the future, PLEASE include a support URL with your requests, so we can see these things for ourselves, otherwise it's all guesswork on our part.

**Comment by robbiereynolds** [comment]
Sure enough... updated Redux Framework core files from git repo and everything seems to be working as expected. Thanks for the excellent and speedy support!

I'm not clear on what you mean by support URL. I'm developing on localhost, if that makes any difference in this situation.

**Comment by dovy** [comment]
Support urls are the way we help devs debug. Look at our docs and read Generating a Support Hash. ;)
