### ISSUE TITLE
Pre sale question about icon select

### ISSUE THREAD

**Issue by dimitrilongo** [reduxframework/redux-extensions#210]
Hi,
Does it works with dashicons ?

Regards
Dimitri

**Comment by dimitrilongo** [comment]
so i bought it, it works, great job redux team !
just put path to dashicon stylesheet and change prefix and selector.
I was unable to have the dashicons stylesheet path included with WP 
like :
```/wp-includes/css/dashicons.min.css?ver=4.2.2&wp-mce-4109-20150505 ```

 so i add dashicon css in another folder but this question not related to redux, if someone have the answer ;-)

**Comment by dimitrilongo** [comment]
i answer to myself no need to have all the stuff (querystrings) ```?ver=4.2.2&wp-mce-4109-20150505``` just have ```/wp-includes/css/dashicons.min.css``` it's enough

```php
$include_path = includes_url(); 
$path = $include_path . '/css/dashicons.min.css';
```

**Comment by dovy** [comment]
:)  Glad you solved it and like it.
