### ISSUE TITLE
All options from metabox are reset after have_post() in single-product.php (woocommerce)

### ISSUE THREAD

**Issue by kisonic** [reduxframework/redux-extensions#211]
I have metabox option:
```
array(
	'id' => 'local',
	'type' => 'button_set',
	'options' => array(
		'1' => 'On',
		'0' => 'Off',
	),
	'default' => '0',
),
```
And in "Edit Product" page I change it to "1"

Part of file woocommerce/single-product.php in my theme
```
<?php while ( have_posts() ) : the_post(); ?>

	<?php wc_get_template_part( 'content', 'single-product' ); ?>
	<pre><?print_r($redux_demo["local"])?></pre>

<?php endwhile; // end of the loop. ?>

<pre><?print_r($redux_demo["local"])?></pre>
```

So in product page (where I change "0" to "1") I see this
```
Array
(
    [local] => 1
)
Array
(
    [local] => 0
)
```
That mean after "endwhile" $redux_demo has been reset.

That how I fix this problem:
```
<?php if ( have_posts() ) : the_post(); ?>

	<?php wc_get_template_part( 'content', 'single-product' ); ?>

<?php endif; // end of the loop. ?>
```
When I use "If" instead "while" $redux_demo not reset.

So problem in Woocommerce or in Redux Metaboxes?

Wordpress: 4.2.2

Redux Framework: 3.5.5.1

Woocommerce 2.3.13

Developer Mode Enabled

**Comment by dovy** [comment]
For metabox within loops, there's no reliable way to overload the global variable, especially with other products like WooCommerce.

So instead, use `redux_post_meta( "OPT_NAME", "THE_POST", "META_KEY" )` as outlined in the docs: https://docs.reduxframework.com/extensions/metaboxes/

Have a great day!
