### ISSUE TITLE
Metaboxes extension merging of section

### ISSUE THREAD

**Issue by PayteR** [reduxframework/redux-extensions#213]
Hi, i have spent 2 days for fixing the issues with validation in metaboxes. When there are more than one section it will validate only the last one. Its because sections array is rewritten with new array. 

extension_metaboxes.php line 138

    $this->sections = $box['sections'];

and it must be 

    $this->sections = array_merge($this->sections, $box['sections']);

please include this fix to the new version, thx

**Comment by dovy** [comment]
I'll add that in, but you can also ensure you're just adding to the boxes via $boxes[] instead of doing a new $boxes = array() at the top.

But I do think it is a good idea to do array merge.

Spoiler, soon the Metaboxes API will be released and this pain will be a thing of the past.  ;)

**Comment by PayteR** [comment]
Yes, im sure,  example here

    function im_metaboxes_settings($metaboxes)
    {
            $metaboxes[] = array(
            .
            .
            .
            .
            );

            // Kind of overkill, but ahh well.  ;)
            return $metaboxes;
    }

    add_action('redux/metaboxes/im_settings/boxes', 'im_metaboxes_settings');

**Comment by dovy** [comment]
Yup. That will solve your issue.   ;)
