### ISSUE TITLE
Metaboxes - Sections issue

### ISSUE THREAD

**Issue by pootato** [reduxframework/redux-extensions#215]
Hey @dovy and @kprovance !

I love this extension so much, thanks for making it! I'll try to make this simple.

<hr>

In Options, creating a Section (without a type) adds a tab that links to the first sub-section.

In Metabox, creating a Section (without a type) throws up the error:

`Notice: Undefined index: type in extension_metaboxes.php on line 1162`

Here is the code I used to start the section:

`$boxSections[] = array(`
`	'title' => __( 'Section' ),`
`        'id'    => 'sections',`
`        'icon'  => 'el el-home',`
`        'fields'     => array(`
`			array(`
`				'title' => __( 'Settings' ),`
`				'id'    => 'settings',`
`				'icon'  => 'el el-home'`
`			),`
`        )`
`    );`

Just wondering if I'm doing something wrong. :dizzy_face:

**Comment by kprovance** [comment]
You're missing the 'type' argument in your field array.  You know, the argument that specifies which field to display?  It's required.  :)

**Comment by monstertheme** [comment]
Hah! Yea I know, but do Metabox sections function differently than the Options? 

In the options panel I am able to create a blank tab that links to the first sub-section using:

`Redux::setSection( $opt_name, array(`
`        'title' => __( 'Home Settings' ),`
`        'id'    => 'home-settings',`
`        'icon'  => 'el el-home'`
`    ) );`

which creates the section that automatically links to:

`	Redux::setSection( $opt_name, array(`
`        'title'      => __( 'Manager' ),`
`	'desc' => __('Choose and sort your layout options for the homepage.'),`
`        'id'         => 'manager',`
`        'subsection' => true,`
`        'fields'     => array(`
`            array (`
`				'id' => 'layout',`
`				'type' => 'sorter',`
`				'title' => __('<h2>Manager</h2>'),`
`				'options' => array (`
`					'enabled' => array (`
`						'placebo' => 'placebo',`
`					),`
`					'disabled' => array (`
`						'placebo' => 'placebo',`
`					),`
`				),`
`			),	`
`        )`
`    ) );`

**Comment by kprovance** [comment]
Yeah, I don't know.  A type argument is required.  That's about all I know.  Maybe @Dovy will chime in at some point.  He would know better than I.

**Comment by monstertheme** [comment]
Sounds good, thanks for stopping by.

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
