### ISSUE TITLE
Can not get "Metboxes" installed

### ISSUE THREAD

**Issue by ericwallen** [reduxframework/redux-extensions#216]
Guys, for the life of my I can not install metaboxes on my site. Can I provide you with my FTP details so that you can load them up for me. Once I have a working code example I will be fine. My site has redux installed as plugin and the admin-init.php called in from the functions.php. The main options are called in.

I really need this help. Can you please do this for me?

**Comment by kprovance** [comment]
Use the Redux API (https://docs.reduxframework.com/core/redux-api/)

Redux::setExtensions(<opt_name>,<dir path to the extensions folder>);

Obviously, you replace those two parameters with your proper data.

**Comment by ericwallen** [comment]
Ok, I looked it over last night. Let me try and figure it out again. I have been spending a lot of time on trying to figure this so I am feeling tired. On the upside I am sure i am learning something through all this. I still have yet to make it 50 pages in on my php book so i am lacking in knowledge no doubt. Sad but true. I am going to try and work through this again today after I complete all the urgent tasks I have. 

Thanks. 

FYI nothing in the metabox extension "docs" point to the new API that I saw. Just your message.

**Comment by dovy** [comment]
@ericwallen did I not upload the new build of metaboxes? That would be the issue here... The new docs have it, hah. Whoops. Let me get that up soon.

**Comment by monstertheme** [comment]
Oooo a new Metaboxes update? Can't wait! :+1:

**Comment by ericwallen** [comment]
Hi, sorry I was slammed the other day and could not make it back to respond. Are they updated now?

I have my mind set on trying to figure this out again.

**Comment by ericwallen** [comment]
yes..no?

**Comment by ericwallen** [comment]
I spent $125 on this and have not been able to use it. I also have the premium support. I asked for help getting it installed several time only to get convoluted answers. Now, a year later I still have not been able to successfully used my product. Can I please get a refund?

I would be happy to repurchase once you have a stable release and documentation I can follow to install.

**Comment by kprovance** [comment]
I was under the assumption Dovy was handling this.  Guess not?  You'll have to email me FTP login info and wp-admin access.

**Comment by kprovance** [comment]
kevin@reduxframework.com.

**Comment by kprovance** [comment]
For the record, you made a payment for a one time use of premium support in Nov of 2014, BEFORE you purchased metaboxes.  Premium support is not cart blanche.  I did give you the Redux API to set extensions, but never heard back about it, all you said was something about a php book.

**Comment by ericwallen** [comment]
Last said was Dovy...updated something or other. He never responded...sending info now.

**Comment by kprovance** [comment]
Still don't have it.  Not in spam folder.

**Comment by ericwallen** [comment]
resent. Hopefully you can see it now.

**Comment by kprovance** [comment]
I don't see where metaboxes is even installed in your theme.  Where did you install it?

**Comment by ericwallen** [comment]
This is getting ridiculous. That's what I have been asking you for over a
year now. Instructions on how to install it. The documentation is BS. Even
dovy said he needed to update it with the real information. He never did
that.

What exactly did you think you were logging in to my site to do....create
some options or something?

I have no idea how to speak any more clearly than I already have.

**Comment by ericwallen** [comment]
The very first line in the thread:

"Guys, for the life of my I can not install metaboxes on my site."

The NAME of this thread is "Can not get "Metboxes" installed"

Seriously?
Seriously?
Seriously?

**Comment by kprovance** [comment]
<blockquote>
What exactly did you think you were logging in to my site to do....create some options or something?
</blockquote>

To do you a favour, actually, since what I was going to do is technically considered premium support.  Instead, I'm just going to send you a sample theme with metaboxes installed and working.  It was generated with https://build.reduxframework.com (which, btw, is what the docs suggested you do to begin with). Hopefully, by looking at that example, you should be able to figure out how to install it in your own theme.  Good luck.

**Comment by ericwallen** [comment]
I have downloaded and have installed through your builder and used "require" so that it prompts to install redux through repository.

Everything is in working order.

I see a file inside the redux-extensions directory called extensions-init.php

Inside that file it says: All extensions placed within the extensions directory will be auto-loaded for your Redux instance.

So I place my metabox directory inside that folder ignoring the loader.php but I took the config.php and copied it to the directory configs inside redux-extensions directory. A that point I have a php error.

I am sure all of this could be solved if i knew how I am supposed to include extensions when creating a build from the redux builder. Kevin, you said you did that last time? How?

I was in my account and see that it says I have metaboxes for a year. Does that mean support expires after a yaer or you guys try to charge my card again? $125 should be good for life, right? It's confusing verbage. 

I have still yet to use the metaboxes because I simply can not get it installed.

Can you please give me a clear breakdown of how I am supposed to do this? Everything I see keeps talking about the loader.php such as here https://github.com/ReduxFramework/redux-extensions-loader

Thanks,

Eric
