### ISSUE TITLE
Cannot save color_rgba field within repeater extension

### ISSUE THREAD

**Issue by aonzzung** [reduxframework/redux-extensions#217]
I'm using ordinary color_rgba within a repeater but after trying to save, the color_rgba values cannot be saved and it always shows default value.
```
// Repeatable
            array(
                'id'           => 'xxx',
                'type'         => 'repeater',
                'title'        => 'yyy',
                'subtitle'     => 'zzz',
                'group_values' => true,
                'groupname'    => 'kkk',
                'fields'    => array(
array(
                        'id'        => 'four-cells-style-cell1-color-overlay',
                        'type'      => 'color_rgba',
                        'title'     => __('Color Overlay', 'theme-options'),
                        'subtitle'  => __('', 'theme-options'),
                        'default'  => array(
                           'color' => '#000', 
                           'alpha' => '0.6'
                        ),
                    ),
...
..
..
```

Other fields (including 'color' fields) within my repeater can be saved correctly except for color_rgba fields.

--------------------------------------------------------------------
WP4.2.2
Repeater 1.0.4
Redux Framework 3.5.4.23

**Comment by dovy** [comment]
@kprovance probably a "prefix" issue.  ;)   Care to look into it?

**Comment by kprovance** [comment]
Please update to Redux v3.5.6.2 from the repo.  The fix in it should resolve this.

**Comment by aonzzung** [comment]
Wow! Thanks @kprovance 
It works perfectly now. :)

**Comment by dovy** [comment]
Glad to hear it.  :)
