### ISSUE TITLE
Metaboxes - Saving changes causes Notification

### ISSUE THREAD

**Issue by monstertheme** [reduxframework/redux-extensions#219]
Saving Metaboxes (using the Update button in the Sidebar) causes the usual notification:

<code>You have changes that are not saved. Would you like to save them now?

Are you sure you want to leave this page?</code>

If you click "Stay on this Page" the Update button gets disabled and gets stuck loading.

<hr>

I know you can fix by turning off notifications or AJAX save, but I would like to have these turned on.

Any known workaround?

**Comment by kprovance** [comment]
I've been working metaboxes all night, and haven't seen any behaviour like this.  Metaboxes does not use ajax_save, so that's not even a concern.  Seems clicking the Update button should save Redux settings before saving the page and navigating away.

Let's start with you supplying us with a support URL, so we can look at your config, since I really don;t want to play 20 questions extracting this data one message at a time.  :)

**Comment by monstertheme** [comment]
http://support.redux.io/?id=li8MMkgW14v9V4tA12IztyYLI5CT19bzzqWpSai8n%2FNau1TYssraMucMW0NZV%2FjL4iN3bk7LwOC1Mscgeka%2FNg%3D%3D

**Comment by kprovance** [comment]
I don't see Redux installed as a plugin, and I don;t see the path anywhere to the Redux core.  How exactly is Redux installed?  What is the full path to the framework.php?

**Comment by kprovance** [comment]
And what is this global argument I see, `page_parent_post_type`?  This is not part of our core.

**Comment by monstertheme** [comment]
I used the Redux builder. (Which seems to be down at the moment.)

The full path is /admin/framework.php

Not sure where that argument came from, but I'll remove it.

**Comment by kprovance** [comment]
Where is the ReduxCore folder?  If this is a custom job you did yourself, you may be out of luck.  We don't support those who tamper with the core.  The builder outputs `admin-folder\admin\redux-framework\ReduxCore`.  if that order is changed, it's considered white branding, which is unsupported.

**Comment by monstertheme** [comment]
I seemed to have fixed it with a fresh Sample Config, I'll try and build from there.

Thank you magical sir!

**Comment by kprovance** [comment]
Okay, good enough.
