### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by newgraphicses** [reduxframework/redux-extensions#220]
Hi, 
Since implementing an SSL certificate the data entered in the metabox are not more interpreted from the site. How can I solve the problem?
Thank you

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
