### ISSUE TITLE
Issues embedding extensions on multiple Redux instances

### ISSUE THREAD

**Issue by oitentaecinco** [reduxframework/redux-extensions#221]
I'm having issues embedding extensions on multiple redux instances. This is what I have:

**one custom plugin with the framework of my theme**

*Besides other shared functions, on this plugin I have the redux-framework embedded and also the redux-extensions (for example the repeater extension). This plugin doesn't create any instance of the Redux Framework.*

**one custom plugin for custom post types**

*Besides registering the post types and dealing with other stuff, this plugin creates an instance of the Redux Framework to handle the options of the plugin. And also, it loads the repeater extension. So I can use it on the options panel.*

**the theme**

*The theme also crestes a new instance of the Redux Framework to handle the options of the theme. And since the $opt_id is different from the redux instance created by the plugin, I'm also loading the repeater extension.*

The problem...:

The repeater extension is only working on the plugin options, and not on the theme options.
However, if I disable the plugin, the extension works on the theme options.

So, I can't have the extension working on both redux instances (plugin & theme). It seems that I can't load the extension twice. 

But it is supposed, right? 

I least I think so, because to load the extensions, we have to use an action that is specific for each $opt_id:

**add_action( 'redux/extensions/' . $opt_id . '/before', '........' , 0 );**

Do you have any ideas about what might be happening?
If you need any specific detail, let me know.

Thanks in advance.

**Comment by dovy** [comment]
Are you using the Redux API?

**Comment by oitentaecinco** [comment]
I'm using this extension loader: https://reduxframework.com/docs/extensions-loader/

**Comment by dovy** [comment]
Transition to the Redux API and load extensions that way. This problem will be resolved.  ;)

**Comment by oitentaecinco** [comment]
It worked, mate. Thanks!

**Comment by dovy** [comment]
Glad to hear it.  :)
