### ISSUE TITLE
Social Profiles deprecation notice in WP 4.3.0

### ISSUE THREAD

**Issue by silviulucian** [reduxframework/redux-extensions#223]
```
Notice: The called constructor method for WP_Widget is <strong>deprecated</strong> since version 4.3.0! Use <pre>__construct()</pre>
````
Screenshot of backtrace: http://screencast.com/t/VgBecUXmna

WordPress 4.3.0
ReduxFramework 3.5.4.25
Social Profiles 1.0.3

Also here's a support URL for good measure: http://support.redux.io/?id=ZR5rky5DgQQGefkBMvXFdPcCgWHd54uqL57lEbb6nijXbdY9sCCJD9XDBHkgINk6UCuwE9ijAm6eH7Iy8PgJ%2Fw%3D%3D (had to disable Social Profiles to generate it, just fyi in case that doesn't show up in there).

**Comment by kprovance** [comment]
Actually, I fixed it ages ago, but forgot to upload it!  :(

Will do it today.  :)

**Comment by silviulucian** [comment]
Cheers Kevin!

**Comment by kprovance** [comment]
1.0.4 update posted.   :)
