### ISSUE TITLE
Repeater not working with two plugins installed.

### ISSUE THREAD

**Issue by peterkaer** [reduxframework/redux-extensions#225]
Hi

When I activate two plugins both using the repeater field, the field doesn't show in one of the plugins. Anyone figured out why? :-)

Thanks

**Comment by dovy** [comment]
Using the Redux API or the old extensions loader?

**Comment by dovy** [comment]
IE, this has been fixed with the Redux API I believe...

**Comment by peterkaer** [comment]
Just changed to Redux API, and it's working. :-)

Thanks

**Comment by dovy** [comment]
I really need to take down the extension loader repo. Haha.
