### ISSUE TITLE
Metaboxes - Error Path after update of the Redux Framework

### ISSUE THREAD

**Issue by visualmodo** [reduxframework/redux-extensions#226]
Hi!

After the last update Redux Framework a new folder was added "/ configs". This file contains the latest a call to the Loader.php file where the line is "require_once (dirname (__ FILE __) '/ Loader.php'.)" after the update that way does not work anymore! I changed to "require_once (dirname (__ FILE __) '.. / .. / Loader.php'.)" and everything went back to work. So it's not really a support I'm asking but an observation that the file Loader.php need a small correction. Thanks!

Redux Framework Version: 3.5.7.2

https://reduxframework.com/docs/extensions-loader/

Current: 'require_once (dirname (__ FILE __).' / Loader.php ');'

Change to 'require_once (dirname (__ FILE __).' .. / .. / Loader.php ');'

**Comment by pootato** [comment]
Not having an issue with Redux Extension Loader.

Try copy pasting the content of loader.php into your functions.php and change the path.

**Comment by dovy** [comment]
We no longer use the loader. Use the Redux API instead. It makes it so more than one instance can use extensions at a time.  ;)

**Comment by pootato** [comment]
I tried using the API first using the examples in the docs but can't seem to get metaboxes working.

From options-init:
<code>$ext_path = dirname( __FILE__ ) . '/extensions/';
Redux::setExtensions($opt_name, $ext_path);</code>

**Comment by dovy** [comment]
Are you loading the rest of your config through the API, or the old way?  ;)   That would be why.

**Comment by pootato** [comment]
I used the Redux builder so I'm guessing API. :P
