### ISSUE TITLE
Color Scheme Extension Enqueue

### ISSUE THREAD

**Issue by MrHunter** [reduxframework/redux-extensions#229]
Had a customer that is having some odd troubles with the color scheme extension, I've narrowed it down to in the __contruct function and something in the "extension_url" var. It seems to link the styles and scripts like this "http://www.example.com/wp-contentthemesautomotiveReduxFrameworkextensionscolor_schemecolor_schemefield_color_scheme.css". Here is the support hash: http://support.redux.io/?id=UB6CiOYe4zdWSHlrYEiA7a1tMj%2F4wkPqx%2ByVM4jKc84q24UYuqiwqyB5qMVk0q%2FHTsYdDz51d8lyzstRUUk59g%3D%3D

I can also provide a WP or FTP login if needed.

Thanks, Dan.

**Comment by kprovance** [comment]
ASBPATH is returning '//' instead of an absolute path, that's why.  And they're using PHP 5.2, BOO!  I'm not sure why ASBPATH would be empty like that.  Seems WP shouldn't function at all in that case.

**Comment by MrHunter** [comment]
Well they definitely need to update PHP then before anything else happens or is investigated, I will forward this onto them. 

Thanks a lot Kevin!

**Comment by MrHunter** [comment]
I've been told they have upgraded to PHP 5.4.4-14 and still are having the problem, I generated a new support hash for you to verify: http://support.redux.io/?id=UB6CiOYe4zdWSHlrYEiA7a1tMj%2F4wkPqx%2ByVM4jKc84q24UYuqiwqyB5qMVk0q%2FHTsYdDz51d8lyzstRUUk59g%3D%3D

Thanks, Dan.

**Comment by kprovance** [comment]
Again, the ABSPATH is empty.  Can you determine why that is on that server?

**Comment by MrHunter** [comment]
I can't see any reason why it's returning an empty variable, I had them disable all plugins except for ours which uses the panel. Does this sound like something server side that the host should be notified about?

Shouldn't the enqueue path still have slashes though even if the ABSPATH is empty?

Thanks, Dan.

**Comment by kprovance** [comment]
I don't know.  I googled this issue and can find nothing about it.  ABSPATH is defined within the WP core with this:
```php
define( 'ABSPATH', dirname( dirname( __FILE__ ) ) . '/' );
```

If that call is returning a single slah (with the second one added at the suffix), the question becomes why does that fail.  It *has* to be something on the server.  Or, is this individual installing WP in some unconventional way?
