### ISSUE TITLE
Repeater Field CSS conflicts with Swift Ideas Themes

### ISSUE THREAD

**Issue by peterkaer** [reduxframework/redux-extensions#230]
Hi

Themes from Swift Ideas, http://swiftideas.com/, has CSS for "h3.ui-accordion-header" which conflicts with the header on repeater fields, and no header is shown.

Maybe change "ui-accordion-header" to "redux-ui-accordion-header" or something? :-)

Thanks

**Comment by kprovance** [comment]
ui-accordion-header is from the jQuery UI library.  Why are we obligated to change it and possibly break backward compatibility with other users?

I'll ask Ed about it.

**Comment by peterkaer** [comment]
Hi
I don't think you are obligated to change anything if you don't want to. :-)
Just a friendly observation that the repeater field might look strange for users with a Swift Ideas theme.

Thanks
