### ISSUE TITLE
Metaboxes extension hides Yoast SEO content

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-extensions#231]
Redux embedded
Redux 3.5.7.10
WordPress 4.3.1
Metaboxes 1.3.0

Hi guys,

There is a conflict between the Redux metaboxes extension and Yoast SEO. In the Yoast SEO panel on any page or post when you click the Page Analysis tab the analysis data is hidden. Looking at the source code I can see all the < tr > tags are set to "display: none". Disabling the metaboxes extension resolves this issue (image attached).

The error console reports the following error:

Uncaught ReferenceError: replacedVars is not defined
wp-seo-metabox.min.js:1 

But I don't think this is related as this error also occurs when the metaboxes extension is removed.

![screen shot 2015-09-28 at 10 12 09](https://cloud.githubusercontent.com/assets/3200083/10131908/75febc16-65cb-11e5-9116-80bf8e321871.png)

**Comment by kprovance** [comment]
Well, here's the problem.  No code exists in the field_metabox.js that modifies the TR tag.  If it's in the Redux core, I can't find it.  My time is very limited to work on this, currently.  If you'd like to pokje around for it, that's be great.  Otherwise, I'll get it it as time allows.

**Comment by kprovance** [comment]
Also, that javascript error, that's their issue.  Not ours.  :)

**Comment by kprovance** [comment]
See #85.  Bit of a hack, but will fix it in the interim.

**Comment by ghostpool** [comment]
Thanks for the hack.

I suspect the issue is coming from one of the JS files from the core framework. The metaboxes extension is loading these files on posts and pages which it wouldn't usually do, so this is why it's only occurring with this extension installed. There are a number of references to hiding < tr > tags in redux.js, but uncommenting them didn't fix the issue.
