### ISSUE TITLE
my purchase history is empty 

### ISSUE THREAD

**Issue by danielwebguy** [reduxframework/redux-extensions#232]
Hi,
I already bought an extension, and also funded $200 for the customizer but I can't see my extensions in the purchase history.
Daniel
![2015-10-06_2235](https://cloud.githubusercontent.com/assets/15003148/10320135/901735aa-6c7a-11e5-8da9-d0d01a33af13.png)
![2015-10-06_2236](https://cloud.githubusercontent.com/assets/15003148/10320160/b4ed5ada-6c7a-11e5-83ea-6c8359af8e83.png)
![image](https://cloud.githubusercontent.com/assets/15003148/10320170/c9483cc0-6c7a-11e5-8ca6-f7f9a5cabd0e.png)

**Comment by kprovance** [comment]
There's something wrong with the ideas site that still hasn't been resolved.    Send me an email kevin@reduxframework.com and I'll get you that download link.
