### ISSUE TITLE
Textarea Gets Wiped When Moving Repeater Position

### ISSUE THREAD

**Issue by coleh33** [reduxframework/redux-extensions#237]
When moving one of the repeater boxes above or below another box, any text that is inside the textarea get completely removed.

Can you confirm the same issue when using the textarea inside a repeater box and moving it's position?

Thank You.

**Comment by kprovance** [comment]
I didn't write the repeater extensions, and I have little to no clue how the javascript works.  The author who did has a demanding day job.  I am unable to confirm this issues, as you provided no field code or version information.  You can;t just tell me something doesn't work and not how to reproduce it.

See here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by coleh33** [comment]
Thanks for the response.  The only thing I did was use the following code to create the textarea inside the repeater.

    array(
      'id' => 'module-custom-code',
      'type' => 'textarea',
       'title' => 'Custom Code',
       'desc' => 'Place any custom code here that you want to appear in the module.',
    ),

Inside the repeater, I will put some sort of text or code embed into the text area and save.  If I create other repeater sections and move the position of the repeater box and hit save, the text that was in the repeater text area will be deleted upon reloading the page.
