### ISSUE TITLE
Can't figure how to load my color sheme extension in redux. Please help!

### ISSUE THREAD

**Issue by ObviousMarketing** [reduxframework/redux-extensions#238]

**Comment by kprovance** [comment]
Understand, using Redux and it's extensions require more than a passing knowledge of PHP.  If the instructions on our docs page (https://docs.reduxframework.com/extensions/color-schemes/) isn't good enough, I would recommend using the Redux Builder (https://build.reduxframework.com) to generate an admin install.  Once you've downloaded that and install it on your server, place the color_schemes folder inside the redux-extensions folder.

You then include the admin.init.php in your theme, and place all your Redux option arrays in the options-init.php
