### ISSUE TITLE
Accordion Extension Not working

### ISSUE THREAD

**Issue by distincthq** [reduxframework/redux-extensions#239]
HI There, 

Purchased and installed the Accordion extension, 
I'm using the code example from the extension page (link to extension page: http://bit.ly/1l91Vkp )
and it doesn't seem to work i get the accordion bar for each section but the fields are shown below. clicking the + doesn't expand or collapse the accordion panel.Each section has a 'position'  => 'start', 
and 'position'  => 'end', 

Javascript & CSS is loading fine

in Firebug console i get this error:
ReferenceError: redux is not defined
redux.field_objects = redux.field_objects || {};

Thanks for your help in advance

**Comment by kprovance** [comment]
You're going to have to show your field code.  I am unable to reproduc eon my own.  In fact, I need everything outlined here:   https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by distincthq** [comment]
Hi, Thanks for your reply, 

I'll try to answer each in order of appearance in your link...

1. Developer using Redux in own project (including in plugin)
2. Using latest version Redux Framework v3.5.8.7
3. developing on localhost
4.installed two extensions metaboxes & accordion (dropped them into ReduxCore/inc/extensions directory as i tried for hours to get them to work using your adding extension instructions without any results. metaboxes extension is working fine no issues. accordion as stated is loading the .js and .css but issue is as described above. 
5. full error message showing in console is 
```
ReferenceError: redux is not defined
redux.field_objects = redux.field_objects || {};
field_a...8044062 (line 10, col 5)
```
code I've added to my main config file is: 

```
     Redux::setSection( $opt_name, array(
        'title'  => __( 'Accordion Field', 'redux-framework-demo' ),
        'heading' => __('Accordion Field: <a href="http://docs.reduxframework.com/premium-extensions/accordion">Documentation</a> | <a href="http://reduxframework.com/extension/accordion" title="Accordion Field" target="_blank">Purchase</a>', 'redux-framework-demo'),
        //'desc'   => __( '<strong>Documentation: </strong><a href="http://docs.reduxframework.com/premium-extensions/accordion">http://docs.reduxframework.com/premium-extensions/accordion</a><br/><strong>Purchase: </strong><a href="http://reduxframework.com/extension/accordion" title="Accordion" target="_blank">http://reduxframework.com/extension/accordion</a>', 'redux-framework-demo' ),
        'id'    => 'business-accordion',
        'icon'   => 'el-icon-lines',
        'fields' => array(
                        array(
                            'id'        => 'opt-accordion-begin-1',
                            'type'      => 'accordion',
                            'title'     => 'Accordion Section One',
                            'subtitle'  => 'Section one with subtitle',
                            'position'  => 'start',   
                        ),
                            array(
                                'id'       => 'opt-blank-text-1',
                                'type'     => 'text',
                                'title'    => 'Textbox for some noble purpose.',
                                'subtitle' => 'Frailty, thy name is woman!',
                            ),
                            array(
                                'id'       => 'opt-blank-text-2',
                                'type'     => 'switch',
                                'title'    => 'Switch, for some other important task!',
                                'subtitle' => 'Physician, heal thyself!',
                            ),             
                        array(
                            'id'        => 'opt-accordion-end-1',
                            'type'      => 'accordion',
                            'position'  => 'end',
                        ),
                        array(
                            'id'       => 'opt-accordion-begin-2',
                            'type'     => 'accordion',
                            'title'    => 'Accordion Section Two (no subtitle)',
                            'position'  => 'start',
                        ),
                            array(
                                'id'       => 'opt-blank-text-3',
                                'type'     => 'text',
                                'title'    => 'Look, another sample textbox.',
                                'subtitle' => 'The tartness of his face sours ripe grapes.',
                            ),
                            array(
                                'id'       => 'opt-blank-text-4',
                                'type'     => 'switch',
                                'title'    => 'Yes, another switch, but you\'re free to use any field you like.',
                                'subtitle' => 'I scorn you, scurvy companion!',
                            ),             
                        array(
                            'id'        => 'opt-accordion-end-2',
                            'type'      => 'accordion',
                            'position'  => 'end',


                                ))
    ));

```

These are the only changes I've made to add the accordion, 
once again thank you for your help with this

**Comment by kprovance** [comment]
I REALLY need to see the support URL, as outlined in the contributing docs.  it still works for localhost.  I also need you to turn on dev_mode, because the line you indicated in the javascript is compress, and is useless.

That error means the main redux javscript is not loading, and I cannot reproduce that, and why I need to see the entire config.

Did you make any changes to the the Redux code?

**Comment by distincthq** [comment]
Hi Kprovance, 

really appreciate you taking the time to look into this, and for your replies. 

the extension works on a live server so i think this whole issue is either a wp plugin conflict or something more to do with my code/setup. I won't waste your time further because i don't think this is going to benefit other purchasers of the extension. 

once again thanks for your help, have a nice weekend.

**Comment by kprovance** [comment]
Okay, well, it's nothing something I can even guess at until I see the support URL.  Good luck.
