### ISSUE TITLE
Wordpress Dashicons Broken With 'Editor' field

### ISSUE THREAD

**Issue by coleh33** [reduxframework/redux-extensions#240]
When using the repeater extension and placing a Wordpress editor as one of the arguments for the type it will break the Wordpress dashicons.  I had opened a previous ticket, but hoping this will offer more information as to what is specifically breaking the Wordpress dashicons when using the Wordpress editor as a field type.

  array(
    'id' => 'module-custom-code',
    'type' => 'editor',
    'title' => 'Custom Code',
    'desc' => 'Place any custom code here that you want to appear in the module.',
  ),

Setting editor as the type will break the Wordpress dashicons.

**Comment by kprovance** [comment]
It has something to do with the render via javascript.  I hate to keep passing the buck, but this is Dovy's extension.  I am not at all familiar with how it all comes together on the javascript side, and I can't fix it unless I spend a day or more of my free time learning it, and I just don't have that time to give right now.  Dovy also has a real day job now, so, I can't give you an ETA when it'll get looked into.  If you're good with JS and can figure out, feel free to post back any solutions or suggestions.

**Comment by kprovance** [comment]
Apparently, the editor field was never supported in the repeater extension:  https://docs.reduxframework.com/extensions/repeater
