### ISSUE TITLE
Editor in repeater - is there a solution?

### ISSUE THREAD

**Issue by ismaelyws** [reduxframework/redux-extensions#242]
I know this was posted in a previous thread.

We want to include an editor field type in the repeater.

I wanted to know if anyone has a solution?

I can get my senior dev to code it.

**Comment by kprovance** [comment]
Dovy says it's a CSS thing, somewhere in the jquery UI.  The functionality is there, it simply doesn't look as it should, because of CSS issues.  If you have a guy who's good with that, that's where he should start.  :)

**Comment by ismaelyws** [comment]
go it, thanks. if we figure it out i'll share the code

**Comment by kprovance** [comment]
We've been absolutely appreciative.  :)
