### ISSUE TITLE
Instructions to install Metaboxes - Where are they?

### ISSUE THREAD

**Issue by ericwallen** [reduxframework/redux-extensions#243]
I have downloaded and have installed the theme options through your builder and used "require" so that it prompts to install redux through repository.

Everything is in working order until I try to add metaboxes.

I see a file inside the redux-extensions directory called extensions-init.php

Inside that file it says: All extensions placed within the extensions directory will be auto-loaded for your Redux instance.

So I place my metabox directory inside that folder ignoring the loader.php but I took the config.php and copied it to the directory configs inside redux-extensions directory. A that point I have a php error.

I am sure all of this could be solved if i knew how I am supposed to include extensions when creating a build from the redux builder. You said the builder can do that? How?

I was in my account and see that it says I have metaboxes for a year. Does that mean support expires after a yaer or you guys try to charge my card again? $125 should be good for life, right? It's confusing verbage.

I have still yet to use the metaboxes because I simply can not get it installed.

Can you please give me a clear breakdown of how I am supposed to do this? Everything I see keeps talking about the loader.php such as here https://github.com/ReduxFramework/redux-extensions-loader

Thanks,

Eric

**Comment by kprovance** [comment]
I recall, the last time I dealt with you, you got REALLY crappy with me, after I offered to help you for free.  I went as far as to send you a sample theme with Metaboxes install so that ALL you had to do was unzip it install it watch.  Serious.  If you can;t figure out how to do basic PHP from a fully functional example, then there isn't much else I am willing to do for free.  I spent enough time trying to do the right thing, only to get an attitude in return.  Go back to that file I sent you last time and work it out.

**Comment by ericwallen** [comment]
I purchased the Metaboxes and support. Exactly how is that helping me for FREE? I asked you one simple question. The fact that you are no dumbass makes me think you must be an asshole. I ask again: Where is the documentation? The fact that you are able to create a working file means nothing to me. I need to be able to create one myself. Can you handle that or not? I am pretty tired of your bullshit.

**Comment by ericwallen** [comment]
Actually, I just want a refund. I am tired of dealing with you. What do you need to process that? I purchased the metaboxes and support of which I have received neither.

I know that I am not able to dispute a charge so old but trust me I will file a complaint with the BBB and attorney general.

I have no doubt I can find 20 sites to describe my experience with you guys as well.

**Comment by kprovance** [comment]
It's exactly this kind of attitude that proves my point.
