### ISSUE TITLE
NOT ISSUE: Populate field on another field value

### ISSUE THREAD

**Issue by distincthq** [reduxframework/redux-extensions#246]
Sorry for posting this here, couldn't find a more relevant place to ask. 
what would be the best way to populate one field value base on another nothing complex just standard populate. 

example to clarify: 

field_a : select list with value A, B, C
field_b : text box (shows the value selected in field_a)

**Comment by kprovance** [comment]
There is no 'nothing complex' answer.  You'd need to write and enqueue javascript to react to the select box to populate the text box.  That's that 'what you'd need to do answer'.  Anything moe would require a premium support purchase.
