### ISSUE TITLE
Options not loaded on "Preview Changes"

### ISSUE THREAD

**Issue by mmaedche** [reduxframework/redux-extensions#247]
Hello,

I've installed the metabox extension. It's a great extension and i love it!
But if I set a page as Front page and view it via the "Preview Changes" button, the metabox options won't be loaded. If I run the page via URL or with the "View Page" link in the WP top menu everything works fine. Any idea what can cause this issue? 

Thanks

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
