### ISSUE TITLE
Clearing floats

### ISSUE THREAD

**Issue by ismaelyws** [reduxframework/redux-extensions#251]
Hi,

I don't think this is necessarily a repeater issue, but maybe there is a solution I am not seeing.

We are using repeater for users to add features (icon, title, and text) on the theme we are developing

http://dev.ivgserver.com/integral/

You will see (under the hero section) the "features" I am talking about. I added additional text in the first one and it causes the precedent div's to be off. I have tried adding a "clearfix" fix with Boostrap but no luck. I just want them to clear the float the end end of a row.

In our options, they can choose the size of each div so 1/2, 1/3, 1/4, etc. And the text is dynamic content.

I've tried to add these inside a repeater row, but it doesn't seem I can add a repeater array inside another repeater array.

Any ideas?

**Comment by kprovance** [comment]
It's not a repeater issue.  Sorry.
