### ISSUE TITLE
filtering admin CPT list according to meta query using redux metabox

### ISSUE THREAD

**Issue by danielwebguy** [reduxframework/redux-extensions#252]
Hi, 
I am using metabox for an EVENT CPT.
The event can be on any weekday or more than once.
It is stored in the DB like so:
KEY: opt_event_days
VALUE: a:5:{i:0;s:1:"1";i:1;s:1:"2";i:2;s:1:"3";i:3;s:1:"4";i:4;s:1:"5";}
This shows an array of 1,2,3,4,5 which mean sunday - thursday.

I am trying to filter the event list in the admin using 
add_filter( 'parse_query', array($this, 'show_event_day_filters') );

        public function show_event_day_filters( $query ){
            if( is_admin() AND $query->query['post_type'] == 'event' ) {
                $qv = &$query->query_vars;
                $qv['meta_query'] = array();

                if( !empty( $_GET['eventday'] ) ) {
                  $event_day = (int)$_GET['eventday'];
                  $qv['meta_query'][] = array(
                    'key' => 'opt_event_days',
                    'value' => $event_day,
                    'compare' => 'IN',
                    'type' => 'INTEGER'
                  );

                }
            }             
        }

I have tried many COMPARE options but it does not retrieve any result, it always show it empty.

Before I used redux I use custom box and it worked just fine.

Please advice.

Thanks,
Daniel

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
