### ISSUE TITLE
Accordion Issue 

### ISSUE THREAD

**Issue by pra98935** [reduxframework/redux-extensions#255]
Hello 

1. We are using type 'editor'  for editor. but problem is that if we use editor under accordion and user select visual part so i'm unable to write any text. but if we use editor without accordion then editor in visual mode properly working means we can type

2. Can we categorized google font in drop-down under type of typography if yes then how

3. And how we can add custom font

**Comment by kprovance** [comment]
1) As I explained earlier, this is something that remains on the 'we don't know how to fix' list.

2) No.

3) No.  Someday we hope to have a plugin that will do this.  It's a time/money thing right now; we have neither.
