### ISSUE TITLE
Refound Redux Meta Boxes & WPdemo.io

### ISSUE THREAD

**Issue by mpcreation** [reduxframework/redux-extensions#256]
Hi, I am trying to contact you guys for a refund but no one is responding. My account was billed automatically for another year of Redux Meta Boxes. I have also purchased your wpdemo.io few weeks back and would like to refund it as it does not meet my expectations. The side of wpdemo.io is down a lot and I am not sure who I have to contact to get those refunds. 
Kuba.

**Comment by kprovance** [comment]
Dovy will have to assist you with wpdemo.  As far as our extensions go, they are licensed yearly.  We do not give refunds for those.  You are free to cancel your subscription, but as long as you are in possession of the code, you are obligated to continue your license to use it.

**Comment by mpcreation** [comment]
What do you mean by "not giving refunds for those"? I have purchased your code and I do not use it. I was automatically subscribed for renewal which I didn't know about.  We are supporting you guys for a long time and this is simply not fair. 

Dovy? Could you please provide an email or some other form of contact?

**Comment by mpcreation** [comment]
Hi, could you please respond?

**Comment by dovy** [comment]
So how long ago did you order WPDemo? What didn't work with it?

Are you using Redux in any of your projects? Why buy the metaboxes extension?

**Comment by mpcreation** [comment]
Hi, yeap we are using redux we have also provided $200 for the project that
you tried to found. The customizer extension. We do not use meta boxes
because they haven't worked as we expected. As I see on my paypal account
we purchased the wpdemo on 29th of December.

As for the meta boxes I do not remember what was the issue because we have
tested it almost a year ago, we tried to use it again with the wpdemo but
it also failed.

The wpdemo crashed sometimes (there was a session timeout or something) and
also as described above we wanted to make it work with your meta boxes and
it failed.

We have moved to NinjaDemos and ACF.

Hope that clears things up.

2016-01-21 17:02 GMT+01:00 Dovy Paukstys <notifications@github.com>:

> So how long ago did you order WPDemo? What didn't work with it?
>
> Are you using Redux in any of your projects? Why buy the metaboxes
> extension?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reduxframework/redux-extensions/issues/256#issuecomment-173617232>
> .
>



-- 
regards,
*Kuba *

*Visit me on:*
mpcreation.net
twitter: @mpcreation <http://twitter.com/mpcreation>
ThemeForest <http://themeforest.net/user/mpc/portfolio?ref=mpc> CodeCanyon
<http://codecanyon.net/user/mpc/portfolio?ref=mpc>
Need Support? <http://mpc.ticksy.com>

**Comment by mpcreation** [comment]
Hi, thanks for the wpdemo refund. What is the situation with metaboxes? @kprovance ?

**Comment by kprovance** [comment]
What situation is that?  We don't give refunds for extensions.  We have no guarantee you're still not using the code in any project.  Sorry.

**Comment by mpcreation** [comment]
@kprovance Yeah and if I buy and cancel right away then you have a guarantee that I am not using the code anywhere?! Sorry but this doesn't make sense. Great way to lose paying customers.
So to test your products I should download it from some free service? 

I wish you good luck with such approach towards the client.
Cheers.

**Comment by kprovance** [comment]
<blockquote>
So to test your products I should download it from some free service? 
</blockquote>

Tells me everything I need to know.  Cheers, in fact.
