### ISSUE TITLE
Typekit

### ISSUE THREAD

**Issue by rodrigocreativecode** [reduxframework/redux-extensions#257]
It's possible to integrate Typekit with the framework ?

**Comment by MorenoDiDomenico** [comment]
+1

**Comment by godatinc** [comment]
hello @rodrigocreativecode you solved this?

**Comment by dovy** [comment]
Anyone have a typekit account they want to provide credentials for and I'll build it out?  :)

**Comment by godatinc** [comment]
sure, you can create a account free, This allows you can all access to the api, but I send my access data the typekit via slack
