### ISSUE TITLE
Some doubts about extension Metaboxes

### ISSUE THREAD

**Issue by rflfn** [reduxframework/redux-extensions#258]
Hi, I want to buy [Metaboxes](https://reduxframework.com/extension/metaboxes/) extension, but I need to clear some doubts before...

**1**: I want to buy for use on my theme to sold on ThemeForest, and I want to know if the extension is validated on ThemeCheck and if is totally compatible with latest version of WordPress (4.4.2).

**2**: This extensions are compatible with Posts, Pages and Custom Post Types? or only pages?

**3**: 1 Commercial Product / year
After 1 year, I can continue use this extension without updates? or I need renew license to continue using on my theme?

Thanks.

**Comment by dovy** [comment]
Hey, sorry for the delay! I've been crazy busy.

Anyways, here it goes.

1. Yes, though you often have to have an accompaning plugin as well don't you? You could place it there too.

2. Yes. Just make sure you load your custom post types on the "init" hook.

3. If you're still making money off the product you use Metaboxes in, we ask you to keep the subscription open to keep the project going. If you're not making money, we're not going to ask you to pay.  :P

Hope that makes sense.  :)
