### ISSUE TITLE
Cancel Redux subscription through Stripe

### ISSUE THREAD

**Issue by silviulucian** [reduxframework/redux-extensions#259]
Hi,

I'd like to cancel my subscription for an extension that I don't need anymore but the subscription is through Stripe apparently and the 'Cancel subscription' link in my Redux account leads only to PayPal.

For reference the Redux receipt number is: #2260-6970 and the subscription ID (as it shows up in my Redux account) is #2360

Thank you

**Comment by silviulucian** [comment]
@kprovance , @dovy you guys around?

**Comment by silviulucian** [comment]
@kprovance @dovy I even emailed you guys about this to your billing email address (about 11 days ago and still no reply). If you guys don't have any way for me to cancel the CC subscription through Stripe like you do for PayPal, I'll have to file a complaint with Stripe to get them to cancel it. I don't want to do that because I know stuff like that affects your merchant score but I also don't want to keep a $115 subscription for a license I'm not using.

I'll wait till the end of March to submit a complaint to Stripe.

Please advise.

**Comment by dovy** [comment]
Hey there, life's been a little crazy at my end of the camp. The stripe cancel subscription SHOULD work, I hope I can find out why it isn't. Can you give me until next week to look into this? I've got a big family thing this week. Come Tuesday/Wednesday of next week I can cancel that subscription for you. Is that ok?

**Comment by silviulucian** [comment]
Yep, sure thing. Thank you!

**Comment by dovy** [comment]
@silviulucian were you able to cancel it on the Stripe end? I can take a look at this now if it's still a problem.

**Comment by silviulucian** [comment]
Nope, couldn't figure out anyway to cancel. Stripe is craaazy! :)

**Comment by silviulucian** [comment]
Why did you close the issue if the subscription that I asked you to cancel was still active?

It just charged my CC again:

![screen shot 2017-02-07 at 22 15 11](https://cloud.githubusercontent.com/assets/235876/22709670/42eed6e4-ed83-11e6-8092-df82208a0177.png)

#2360 is the same #7408 which just happened now. There's still no discernible way for me to cancel this thing. This is the second year in a row I bring this up.

Please cancel this right now and refund me the amount it just charged me, otherwise I'll have to resort to filing complaint with both Stripe and the bank to get a forced chargeback.

Thank you
