### ISSUE TITLE
Field Validation in Redux Fram work

### ISSUE THREAD

**Issue by swapnilshetes** [reduxframework/redux-extensions#260]
Hi,

First Please check folder structure : theme name is 'mytheme'

1) mytheme\inc\admin
2) mytheme\inc\admin\redux-extensions
3) mytheme\inc\admin\redux-framework
4) mytheme\inc\admin\options-init.php
5) mytheme\inc\admin\page-template-metabox.php

In 'page-template-metabox.php' we have provided all meta fields for pages and posts 
for example : 
//
$boxSections[] = array(
'title' =>
__('Carousel Images', 'test'),
'icon' => 'el el-briefcase',
'fields' => array(
array(
'id' => CR_POST_EDUC_QUALIF,
'type' => 'textarea',
'title' => __('Educational Qualifications', 'test'),
'width' => '100%',
'placeholder' => __('Please enter educational qualifications', 'test'),
**'validate' => 'not_empty'**
),
array(
'id' => HOME_PAGE_IMAGES_LIST,
'type' => 'repeater',
'title' => __('Add/Edit Carousel Items', 'test'),
'item_name' => __('carousel', 'test'),
'group_values' => true,
'width' => '100%',
'bind_title' => 'opt-carousel-title',
'fields' => array(
array(
'id' => HP_CL_IMAGE_URL,
'type' => 'media',
'preview' => true,
'width' => '100%',
'class' => 'test-social-icons-wrapper',
'url' => false,
'subtitle' => __('Upload only PNG images with (TBD) pixel dimentions', 'test')
),
)
)

        )
    );

    // Declare community metaboxes
    if (!isset($metaboxes) && !is_array($metaboxes)) {
        $metaboxes = array();
    }
    $metaboxes[] = array(
        'id' => 'carousel_category',
        'title' => __('Home Page Carousel', 'test'),
        'post_types' => array(
            'page'
        ),
        'page_template' => array(
            'front-page.php'
        ), // Visibility of box based on page template selector
        //'post_format' => array('image'), // Visibility of box based on post format
        'position' => 'normal', // normal, advanced, side
        'priority' => 'high', // high, core, default, low - Priorities of placement
        'sections' => $boxSections
    );

    return $metaboxes;
}
add_action("redux/metaboxes/{$redux_opt_name}/boxes", "test_add_home_page_carousel_metaboxes");

If we tried to add '**validate' => 'not_empty**' in field array which having type is textarea. 
This is not getting validated at time of publish the page with empty same field in admin side. 

**Please can you assist us how to validate the admin pages in redux framework.**

Also  We have created theme structure from redux website from where we got the above folder structure. 
In **mytheme **(theme folder)  we have '**inc**' folder. In **inc **folder we have '**admin**' folder. 
Admin folder contains **'redux-extensions**' and '**redux-framework**' folders and '**options-init.php**' and '**page-template-metabox.php**' files.

**Please check in detail folder structure : **

inc\admin\redux-extensions

inc\admin\redux-extensions\extensions
-metaboxes (folder)
--metaboxes\extension_metaboxes.css
--metaboxes\extension_metaboxes.js
--metaboxes\extension_metaboxes.min.js
--metaboxes\extension_metaboxes.php
--metaboxes\extension_metaboxes.scss

-inc\admin\redux-extensions\extensions\repeater
-- Contains all Js and extension_repeater.php files in 

inc\admin\redux-extensions\extensions-init.php
inc\admin\redux-extensions\loader.php

inc\admin\redux-framework
-codestyles (folder)
-ReduxCore (folder)
-sample (folder)
-redux-framework.php
-uninstall.php
-bootstrap_tests.php
-class.redux-plugin.php
-index.php

That is all about folder structure which we have downloaded this is not plugin. 

Right now When we tried to create and download new theme we got the different folder structure which is not same as above folder structure.  

**Can anybody explain us what happening here.**

This will very great help us.

Thanks.

**Comment by swapnilshetes** [comment]
Any updated on this? Need assistance on this.

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
