### ISSUE TITLE
Enabling Metabox for a CTP created in child theme

### ISSUE THREAD

**Issue by taksu** [reduxframework/redux-extensions#261]
Hi, 
If I use a child theme and create a CPT there, what is the best procedure to enable the already created Metabox section from a parent theme for this new CPT without modifying the parent theme and adding the CPT manually to 'post_types' array?

**Comment by kprovance** [comment]
This sounds more like a premium support issue.  The amount of time to research this as see if it's even possible is way more than a few minutes, or even an hour.  Maybe @dovy knows?

**Comment by dovy** [comment]
Use a filter on the metaboxes array, iterate over the array, find your declaration, and modify what you need. Make sure the priority is high so it's the last filter run. 

Every time you run the filter you get all of the previous declarations. ;)

**Comment by taksu** [comment]
Works perfectly, thanks!

**Comment by dovy** [comment]
:)
