### ISSUE TITLE
qtip error appears when using Greek language

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-extensions#262]
Redux Framework: 3.9.5.4 (integrated)
WordPress 4.4.2

Support URL: http://support.redux.io/?id=t7DhUgG8%2BJLsb1PNZogCviLo5nk1fcdzIMgBZH3b1pGSI18CXfwbHcohz6yjoUKdQRnX8Wgg2lDd5eVDfE3cXw%3D%3D

I am getting the following error when creating or editing posts/pages in the backend.

Uncaught TypeError: jQuery(...).qtip is not a function
wp-seo-metabox-302.min.js?ver=3.0.7:1 

This only occurs when Yoast SEO and Visual Composer are activated on a theme using the Redux Metaboxes extension (integrated) and when the language is set to Greek. I've tested other languages and this error is not generated. It doesn't occur on the Twenty Sixteen theme with both of these plugins activated - the common link is the Metaboxes extension.

**Comment by kprovance** [comment]
<blockquote>
Uncaught TypeError: jQuery(...).qtip is not a function
wp-seo-metabox-302.min.js?ver=3.0.7:1 
</blockquote>

That's a wp-seo error.  We didn't write that plugin.  You need to contact that author in regard to errors their plugin creates.
