### ISSUE TITLE
Metaboxes: Resetting value - default not used

### ISSUE THREAD

**Issue by Ninos** [reduxframework/redux-extensions#263]
After resetting a field (e.g. removing selection of select-field), the default value will not be used. This is because the value is just checked if its exists, not if it has some content..

I fixed it with following:
In `public function _override_options( $options )` change
```
if ( isset( $meta[ $key ] ) ) {
```
to
```
if ( isset( $meta[ $key ] ) && $meta[ $key ] != '' ) {
```

Redux Metaboxes: v1.3.0
Redux Framework: v3.6.0.2
Wordpress: v4.5.2

**Comment by dovy** [comment]
That's a good find. Does it work against true/false 1/0 as well? Ie, we only want to reset values that are truly an empty string, none of the others.

**Comment by Ninos** [comment]
I'm also using checkboxes (true/false) and for me it works fine :)

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
