### ISSUE TITLE
 Fatal error

### ISSUE THREAD

**Issue by hhbrown123** [reduxframework/redux-extensions#264]
I am receiving the "Fatal error: Call to undefined function menu_page_url() in /home/forthepeople/public_html/wp-content/themes/campaign/framework-customizations/extensions/shortcodes/shortcodes/section/options.php on line 6" after upgrading the extensions.

Can anyone help with resolution? My site is http://www.campaignforpeople.com/

Thanks

**Comment by kprovance** [comment]
Please provide this information:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md

**Comment by dovy** [comment]
See your other post.  ;)
