### ISSUE TITLE
Payment!

### ISSUE THREAD

**Issue by DAVE494949** [reduxframework/redux-extensions#266]
Hi. I've bought Redux Frameword premium extension for my theme (ThemeForest). But reviewers said that I must use it as a plugin and not embed it directly in theme. Can I return the product and give back my money? I haven't used it, as there's no need anymore. Thanks.

**Comment by dovy** [comment]
@DAVE494949, put it inside a feature plugin which is the default method for ThemeForest.

We don't offer refunds for extensions as there's no way to police the use.

If you need help making a feature plugin, ask away. We can help you here.  :)
