### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by ericwallen** [reduxframework/redux-extensions#267]
Guys, I have never used your metaboxes because they never worked. I asked you if they would be billed annually but you never replied to that but instead insisted on insulting me multiple times. Please at minimum refund the last time it renewed. I believe I should be refunded every penny including the first initial charge but am willing to compromise. If you could just refund the 1 year renewal we can part ways. I feel this is really shady that you couldn't answer my question but just ignore me so that it would renew again. Not right guys. 

I want to repeat for clarification. I have never used metaboxes because they never worked. I have opened multiple tickets all of which never got resolved. 

Please issue a refund for the renewal.

**Comment by dovy** [comment]
@ericwallen I'm confused. Who insulted you?

Did you cancel your subscription (on your end) when you didn't want to continue using Metaboxes?

I can assist you to get it working if you'd still like to try. However, this seems rather odd. I don't make a point of insulting people. If I have, I am sorry.  :(

**Comment by ericwallen** [comment]
I simply want a refund for the product that never worked. Can  you do that or do I need to contact the BBB and attorney General? At this point you have left me no choice. THE PRODUCT YOU CHARGED ME FOR DOES NOT WORK. I can't say this any more simply. Refund me ASAP.

**Comment by dovy** [comment]
@ericwallen It does work for hundreds of thousands of sites out there. It's been over a year. Did you ask for support? We'll gladly help you get it working. 

There's no need for your to be in all caps. Let's see if we can get you a functioning setup.  :)

**Comment by ericwallen** [comment]
It has never worked. You guys have closed multiple cases that were not "closed". You need to refund me ASAP. No one wants to deal with you or Kevin...period. REFUND ME RIGHT AWAY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
