### ISSUE TITLE
Repeater Extension - Dependency

### ISSUE THREAD

**Issue by Bluxart** [reduxframework/redux-extensions#268]
Hi, I buy your extension some month ago, it is work fine but the dependency not work, it is possible add this function in the next update?

Or it is possible via custom/paid work?

**Comment by dovy** [comment]
Required you mean? The required argument?

**Comment by Bluxart** [comment]
Yes the required argument-

**Comment by dovy** [comment]
Yes, the repeater does not currently work for the repeater. It's something I would like to remedy, but the complexity is quite huge.  :(

**Comment by Bluxart** [comment]
Hi @dovy if donate 500$ for add this? You can make only for me a custom work for this if you want. Let me know.

Thanks
