### ISSUE TITLE
wrong billing and subscription Cancelation

### ISSUE THREAD

**Issue by somewhatgreen** [reduxframework/redux-extensions#273]
Today i was charged $134 for the yearly subscription of repeater extension while the actual price of this extension is $115, then why this extra $19?

Also i am trying to cancel my subscription by clicking on the "cancel subscription" link in the account dashboard but it is not doing anything, the dashboard gets refresh after clicking on it and does not show any confirmation message also the link is still visible.

I am not sure if my subscription is actually cancelled or not. Can you please confirm if my subscription is cancelled and it is not going to change me for the next extension which is due for renewal on 8th June.

**Comment by somewhatgreen** [comment]
Anybody there?? i wrote an email to you also, can you please reply to that?

**Comment by kprovance** [comment]
Dovy will answer it when he gets back, as he deals with these things.  Be aware, the subscription is good for one year.  If you cancel, then this time next you'll have to stop using our code, and find a replacement.  There will be no updates and no support.

**Comment by somewhatgreen** [comment]
How long is it going to take?? i need an answer, i am feeling trapped by your subscription method. i have no way to cancel it and you guys are not interested to answer me.

**Comment by kprovance** [comment]
Dovy handles all that.  I don;t have access.  What was the name of your theme?

**Comment by somewhatgreen** [comment]
I just purchased your extension but never published a theme using it. the payment ID is 2967 and 3139,
the given link for cancelation does not work, also i don't know how to cancel it from stripe.
the only way for me is to block my credit card so that you guys can not charge me again, as i said the other extension is due for recurring payment on 8th june. and i don't want that to happen.

**Comment by dovy** [comment]
Sorry, holiday over here in the US and had some family things last week.

So the stripe canceling is not working? Let me take a look.

**Comment by somewhatgreen** [comment]
I am glad that you are back, i hope you had very good vacation. now can you please give any updates.

start with the status of cancelation and how about my refund of amount charged on 25th may 2016. i could not stop it from getting renewed.

**Comment by somewhatgreen** [comment]
Are you guys listening?? I don't want to report this issue to the Stripe, please try and understand. co-operate.

**Comment by kprovance** [comment]
Dovy said he was looking into it.  You have to understand, he has a real life and a full time job away from Redux.  No one supports us, which necessitates full time work, plus people who take our code and then demand refunds because they didn't read the fine print and don't feel our code is worth an annual subscription.  Not our fault.  Please be patient.  He one one gut with several demands on his time, and I don't have the access to do anything about it.

**Comment by somewhatgreen** [comment]
I have no complaint against your code. I liked it that's why i purchased your extensions.

1. i am just dropping the subscription because i am not developing themes anymore and thus it does not make any sense to pay for a code i am not going to use.

2. And i am asking for a refund because of two reasons. First - it charged incorrectly ($ 134 while the extension price was $ 115), second - because of your buggy cancelation functionality i could not cancel my subscription and it charged me on my card.

**3. I an looking for a quick solution because the next extension is due for annual subscription on June 8 2016, and don't want that you charge me again against my will.**

Thanks

**Comment by dovy** [comment]
I am trying to fix the stripe cancellation issue. What was your theme called before?  ;)

**Comment by somewhatgreen** [comment]
i guess "BedMart Store" please check with this name.
This is the only live site done by me using redux premium extensions.
url: https://www.bedmartmattresssuperstores.com/

Many Thanks.

**Comment by somewhatgreen** [comment]
Hi there, whats up? I understand that you have a real life but i do have a real credit card which i had to block so that you won't charge it without my concern.
any progress in cancelation process so far?
please inform so that i can leave your site peacefully.

Thanks.

**Comment by dovy** [comment]
@somewhatgreen I just got this email... weird. I'm working on it. It will be resolved shortly.

**Comment by kprovance** [comment]
Not heard anything on this in a while.  Closing.
