### ISSUE TITLE
Metaboxes: url_to_postid() not working on admin post.php (save_post)

### ISSUE THREAD

**Issue by Ninos** [reduxframework/redux-extensions#274]
On /wp-admin/post.php the url_to_postid() is not working fine. The url_to_postid() is not returning an ID.
To solve this, just add following:
```
if ( is_admin() && $pagenow == "post.php" && isset( $_POST['post_ID'] ) && ! empty( $_POST['post_ID'] ) && is_numeric( $_POST['post_ID'] ) ) {
    return $_POST['post_ID'];
}
```
after
`if ( isset( $_GET['post'] ) && ! empty( $_GET['post'] ) && is_numeric( $_GET['post'] ) ) {`

BTW: Clients could easily change the post-ID just by adding ?post=blabla on frontend and backend. I recommend adding some additional checks, also for the other if-statements, e.g.:
`if ( preg_match( '#[?&](p|page_id|attachment_id)=(\d+)#', $url, $values ) ) {`

Redux Metaboxes: v1.3.0
Redux Framework: v3.6.0.2
Wordpress: v4.5.2

**Comment by kprovance** [comment]
It would be VERY helpful to us if you could at least mention the version you are using.  Basic stuff like that.

**Comment by Ninos** [comment]
v1.3.0 with own patch (see following issue #254). Haven't mentioned because I already used latest version :)

The Redux Framework and Wordpress installation are also up2date:
ReduxFramework: v3.6.0.2
Wordpress: v4.5.2

**Comment by kprovance** [comment]
You have to, each time.  My crystal ball stopped working years ago.  People don't understand that.  Did you determine why the post ID returned nothing?  When that happens, there sometimes is a reason.  Sometimes it has to do with custom post types being set too late (init I think, which we tell people not to do).  Is this a CPT situation or a situation where someone messed with the URL?

**Comment by Ninos** [comment]
ATM in `url_to_postid()` you have lots of checks (for frontend and backend). I'm sure you never needed the metabox options on the `save_post` hook and so did not found out that the check above is missing there.

The used post type is the default wp page. On backend you should not have any problems with the post type registrations. As I understood @dovy in past the function `url_to_postid()` was thought for the frontend because the redux framework is loading all options before the post init has finished.

**Comment by dovy** [comment]
@Ninos please give example URLs of where it's failing so we can see what we're up against.

Have to reproduce it here after all.

A support URL too please.

**Comment by Ninos** [comment]
@dovy it's failing in the 'save_post' action hook, so on `/wp-admin/post.php`.
Small example:
```
add_action( 'save_post', 'something_you_need_redux_post_options' );
function something_you_need_redux_post_options( $post_id ) {
    // Here you cannot use the redux post options.
}
```

**Comment by kprovance** [comment]
Again, working site where it fails, and support URL please.  We have to insit on that now, sinc eno one wants to pony up information that would be helpful to us on their own.  Thanks.

**Comment by Ninos** [comment]
Please send me your email addresses. I cannot post credentials on public issue tracker.

BTW: This bug is not site specific. The post options will just not be initialized on post save (/wp-admin/post.php). With my example snippet you can test it out. On my website you would also need file access..

**Comment by kprovance** [comment]
It's not 'credentials'.  It's a hash encoded URL that only we have access to that shows us the Redux config.

**Comment by nuxwin** [comment]
@kprovance

Calm down please. You should really take your drugs. Talking in such way to people is a no-go ;)

**Comment by Ninos** [comment]
Hope this is what you needed @kprovance:
http://support.redux.io/?id=EtlKSJiAPQYgBkvTYjzqQVzya2RGLgpC2wELRZvGeZ3ukORF7R9yLoGhJyTXDFG5fjPxSf8dr5rzINZlbbomUg%3D%3D

My test environment is on WP 4.5.2 with same bug..

**Comment by kprovance** [comment]
@nuxwin Mind your own business, mate.

**Comment by nuxwin** [comment]
@kprovance 

Poor guy ;) You should put your EGO in your ass.

**Comment by dovy** [comment]
Woah woah, come now everyone.  :P

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
