### ISSUE TITLE
Metabox Extension - post type page problem

### ISSUE THREAD

**Issue by KAJOJEK** [reduxframework/redux-extensions#275]
Hello,

Can anyone help me? How to remove metaboxes from pages like: archive, 404, or tags ?
For a normal page everything works great, but when I come to other pages I have a notice:

Notice: Trying to get property of non-object in /.../wp-content/themes/my-theme/admin/redux-extensions/extensions/metaboxes/extension_metaboxes.php on line 1031

thank you.

**Comment by dovy** [comment]
Eww, that's a bug in our code. I'll take a look this week. If you're desperate, just add an if check before that call and return the function if !isset()

**Comment by dovy** [comment]
Also if you're willing to share a test environment I could fix it much faster. Send the info to dovy@reduxframework.com.  :)

**Comment by KAJOJEK** [comment]
I still preparing my theme so I can wait for update. Please let me know when you will fix this.
Thank You.

**Comment by KAJOJEK** [comment]
Hi, any update with this issue ?

**Comment by kprovance** [comment]
@Dovy asked for a test environment.  Did you send that information to him?

**Comment by KAJOJEK** [comment]
I have my theme on local server, but maybe you can help with other problem.How to display options from metaboxes for archive pages. I have archive-portfolio.php and when I will create page portfolio then display all from archive-portfolio.php but meteboxes not working.  I hope that you understand what I mean :)

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!

**Comment by KAJOJEK** [comment]
Hi,

I have a latest version of Metaboxes extension 1.4.1

Redux Framework embedded in theme  v3.6.0.2.

My problem is with "slide" field after import all content to new fresh wordpress installation.

Step 1. have a page with metabox "slide" field and all works fine.
Step 2. make export all content by wordpress to xml file.
Step 3. make import all content to new fresh install wordpress site.
Step 4. checking my page with "slide" metabox all works fine.
Step 5. edit this page and click save.
Steo 6. After refresh page "slide" field is broken, not worked button upload, delete, add slide... etc

I have to go to redux panel and click save settings and repeat this always after edit page.

Please help.

Karol Jarek
