### ISSUE TITLE
Undefined 'post_format' error

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-extensions#277]
Hi there,

Redux 3.6.0.6 (integrated)
Metaboxes extension 1.30.

Some of my users get an undefined index error for 'post_format'.  This looks like it's due to line 179 in extensions/metaboxes/extension_metaboxes.php. This:

    $this->wp_links[ $boxID ]['post_format'] = isset( $this->wp_links[ $boxID ]['post_format'] ) ? wp_parse_args( $this->wp_links['post_format'], $box['post_format'] ) : $box['post_format'];

Should be this:

    $this->wp_links[ $boxID ]['post_format'] = isset( $this->wp_links[ $boxID ]['post_format'] ) ? wp_parse_args( $this->wp_links[ $boxID ]['post_format'], $box['post_format'] ) : $box['post_format'];

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
