### ISSUE TITLE
Use repeater extention in free theme

### ISSUE THREAD

**Issue by iMojtaba** [reduxframework/redux-extensions#279]
Hi,
Do you have any solution to use repeater field extention in free wordpress themes? 
https://reduxframework.com/extension/repeater/

**Comment by kprovance** [comment]
It's a premium extension.  You'd have to buy a copy.  And it won't work in just any theme.  The theme has to be using Redux, the extension installed into the the theme, and code written for the repeater field to display.

**Comment by iMojtaba** [comment]
and if i buy it, can i use it in free theme?

**Comment by dovy** [comment]
In the past I'd say no, but we're changing things. So yes. ;)
