### ISSUE TITLE
Repeater extension problem with icon select extension

### ISSUE THREAD

**Issue by inspiralthemes** [reduxframework/redux-extensions#280]
Hello,

We purchased 2 extensions (Icon select and Repeater) 
Installed them and they are working.

But when we use icon select in repeater only one icon gets output.
See below.

ARRAY ( [0] => 1111111111111 [1] => 222222222222 [2] => 3333333333333333333 )
FA FA-HOME
ARRAY ( [0] => 18 [1] => 19 [2] => 20 )

We need them to work together or else we have no use of the repeater extension.

Please advise

Regards Nasco

![repeater](https://cloud.githubusercontent.com/assets/20194478/16431645/d78ddad2-3d81-11e6-87e8-3aa3a6599461.jpg)

**Comment by kprovance** [comment]
Maybe I don't understand the question, but with the icon select field, only one icon may be selected, and one one will be output?  That's by design and how the icon select field works.  Or am I misunderstanding the issue?

**Comment by inspiralthemes** [comment]
Dear Kevin,

Every repeated field has a icon select. (i use 3 repeated fields)
So there must be for every repeated field a icon to be output.
But that doesn't happen. 

See below!

ARRAY ( [0] => REPEATER FIELD 1 [1] => REPEATER FIELD 2 [2] => REPEATER FIELD 3 )
FA FA-HEART
ARRAY ( [0] => 18 [1] => 19 [2] => 20 )

![repeater2](https://cloud.githubusercontent.com/assets/20194478/16432383/fcaca390-3d84-11e6-9a5a-22257b053363.jpg)

**Comment by kprovance** [comment]
I already found the problem.  Seeing if I can fix it here.  The icon_select field has a small compatibility issue because it was released way before we had a repeater field.

**Comment by kprovance** [comment]
Send me your email:  kevin@reduxframework.com.  I have an update version for you to try.

**Comment by inspiralthemes** [comment]
Please send it to: inspiralthemes@gmail.com

**Comment by inspiralthemes** [comment]
Perfect!

Thank you!

ARRAY ( [0] => REPEATER FIELD 1 [1] => REPEATER FIELD 2 [2] => REPEATER FIELD 3 )
ARRAY ( [0] => FA FA-HEART [1] => FA FA-POWER-OFF [2] => FA FA-TH )
ARRAY ( [0] => 18 [1] => 19 [2] => 20 )

**Comment by dovy** [comment]
Awesome. Glad it worked out. Thanks for supporting Redux.  :)
