### ISSUE TITLE
Amazon S3 changing option values

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-extensions#284]
Hi guys,

Redux Framework 3.6.0.8
Redux Metaboxes Extension

I'm using the Amazon Web Services and WP Offload S3 Lite plugins so I can use Amazon S3 for my site images. The problem is if I upload a logo (a custom media type option I created) it sets all my global theme options to values set for the equivalent individual meta options (those options that share the same names).

To reproduce this issue, install and set up the Amazon Web Services and WP Offload S3 Lite plugins. 

Go to Appearance > Customize and upload a logo.

Refresh the page and all the global option values have changed to those set for the equivalent individual meta options (those that share the same name).

Why is this happening. Does Redux have an issue with the media field using the Amazon URL?

**Comment by ghostpool** [comment]
Hey guys, 

Still no response and it's been nearly 2 weeks. Just, a suggestion as to what the issue maybe would be nice? Does the "media" type work with CDN URLs?

**Comment by kprovance** [comment]
Please upgrade to version 1.4.0 by logging into your account and downloading from there.  If the issue persists, please open a new ticket, including a Support URL (explained here:  https://github.com/reduxframework/redux-framework/blob/master/CONTRIBUTING.md),  Thanks!
