### ISSUE TITLE
Metaboxes: How to temporarily remove action 

### ISSUE THREAD

**Issue by carmoreira** [reduxframework/redux-extensions#288]
I have a function hooked to the 'save_post' to create a new custom post type entry based on data from the metaboxes, but the new custom post type entry is also being populated with the meta data from redux, so I wanted to remove that action while I create my new post. 

What would the correct value for $reduxclass for this to work:

$reduxclass = 'ReduxFramework_Extension_metaboxes';
remove_action( 'save_post', array( $reduxclass, 'meta_boxes_save' ) );
$newid = wp_insert_post( $location_post , $wp_error );
add_action( 'save_post', array( $reduxclass, 'meta_boxes_save' ) );

Another approach would be to edit the save_post hook from metaboxes class to add an extra control, something like 

`if(isset($_POST['post_ID']) && $_POST['post_ID'] != $post_id ) {
                    return $post_id;
                }`

But I don't want to edit the core files.

What would be the best approach?

**Comment by kprovance** [comment]
The class name is 'ReduxFramework_extension_metaboxes' )I don't believe case matters here, but just in case.

You'll have to play around with it and see if it works.

**Comment by carmoreira** [comment]
Thank you for the answer! 
I can't get it to work, I get a couple of errors. For example:

> Strict Standards: call_user_func_array() expects parameter 1 to be a valid callback, non-static method ReduxFramework_extension_metaboxes::meta_boxes_save() should not be called statically in /Applications/MAMP/htdocs/2016/wp-includes/plugin.php on line 524

I will play around a bit to see if there's any combination that would work. 

But would you consider adding the extra isset control I mentioned to the 'meta_boxes_save' function? Seems it would make sense, but not sure I'm forgetting any case where it would cause issues. With the extra $post_id check there I wouldn't need to remove/add the action when I execute the other wp_insert_post.

**Comment by carmoreira** [comment]
Small update on this, I couldn't get it to work with the remove_action action filter so I made a change in the extension file extension_metaboxes.php 
I added the following, on line 1212:
`                if(isset($_POST['post_ID']) && $_POST['post_ID'] != $post_id ) {
                    return $post_id;
                }`

Solves my issue and it wouldn't hurt to have that extra control there.

**Comment by kprovance** [comment]
Added to v1.4.2
