### ISSUE TITLE
Bug on Date/Time Picker: Hour value populating multiple fields

### ISSUE THREAD

**Issue by carmoreira** [reduxframework/redux-extensions#289]
When using
`'split' => true,`

If there are multiple date/time picker fields in the same page, the hour selected  in the picker for one field will populate the other existing hour fields also. 

This behaviour can be seen in the demo page also:
http://demo.redux.io/wp-admin/admin.php?page=redux_extensions&tab=5

**Comment by kprovance** [comment]
Update to version 1.0.6, which should resolve this.
