### ISSUE TITLE
Metaboxes: Display field only for specific post type.

### ISSUE THREAD

**Issue by prafgon** [reduxframework/redux-extensions#290]
Hi there!

Plugin: Redux Metaboxes.

I'd like to ask if there is any way to display certain metabox fields (or a tab/group of fields in a tabbed mode) only for a specific post type? For example, under the "Header" tab I'd like to display an option to control the display of the blog post meta (author, date, categories) and of course would like to hide that field completely on a page post type and/or other custom post types. And creating a different metabox (I know they can be assigned as whole to a specific post type and I use that) just for that option doesn't sound like a great idea. 

I'd for sure work it around by adding some custom CSS for those specific fields but unfortunately table rows of fields do not come with any unique ID whatsoever.

Thank you!

**Comment by kprovance** [comment]
Could you verify your purchase with the order number?  It'll be in the email you received.  I gptta start doing this now, sorry.  :)

**Comment by prafgon** [comment]
Oh, sure. I actually have three purchases: #5570, #5356, #5348. :)

**Comment by kprovance** [comment]
Here is the easy part.  Field array accept an argument called 'hidden'.  So, whenever you'd like to hide or show a field, add the `hidden => true` or `hidden => false` to it's array.

The hard part will be evaluating the post type in code where the metaboxes arrays are set.  $post comes up empty and get_post_type() returns false.  So, if you can find a way to get those to work, you assign a variable to true or false, and use that variable with the 'hidden' arg.
