### ISSUE TITLE
Metaboxes 1.4.1 regression

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-extensions#291]
I just updated from metaboxes extension 1.3.0 to 1.4.1 and have found a regression.

On line 75, the additional if statement `if (defined('DOING_AJAX') && !DOING_AJAX) {` is causing the metabox fields to incorrectly appear on an options page that is a sub-menu under the same CPT.

Here's what my menu looks like:

```
Lodging
  Lodging
  Add New
  Settings
```

The Lodging CPT metabox has several text fields on it while the Settings page just has a js_button field setup in the code.  However when viewing the Settings page, the text fields from the metabox are also visible under the js_button.

I've commented out the if statement for now, as it restores how metaboxes worked in the previous version and I don't use the redux_post_meta().

http://support.redux.io/?id=PD%2BHSQkPqpF%2B7xI9ZzQAinVhUrxasgLyOeLl2BKibh5fa289uAfGhnthPSiALrcGhA3X%2BBvR0fjAFCK9zjFYmg%3D%3D

**Comment by kprovance** [comment]
Well, then any calls to redux_post_meta will fail inside an AJAX call.  I can't take that out, too many people are depending on it now, me included.  Are you registering your CPT on an init hook?

**Comment by Enchiridion** [comment]
I understand, I just commented it out as it was an immediate fix for me.  I'm hoping some additional logic added to that if statement will fulfill both use cases.

Yes, during 'init'.

**Comment by kprovance** [comment]
I'm surprised it works at all then.  I have to run my CPT on after_theme_setup to get required to work.

**Comment by kprovance** [comment]
Please update to v1.4.2 and see if the issue has been resolved.
