### ISSUE TITLE
Metaboxes - field/section 'permissions' option not working

### ISSUE THREAD

**Issue by Enchiridion** [reduxframework/redux-extensions#292]
I'm trying to use the 'permissions' option to control the visibility of certain fields in a metabox, but it isn't working.  Looking through the metabox extension source code, I didn't find any places where it was checking for 'permissions' like the core does.

Is adding this option on the roadmap?

Redux 3.6.2
Metaboxes 1.4.1

**Comment by dovy** [comment]
Good call. It currently isn't on the roadmap, but I'll add it. It needs to be.

**Comment by dovy** [comment]
...and it won't take much to do honestly.

**Comment by Enchiridion** [comment]
Ok, that'd be great if you could add it in!  Let me know if there's anything I can help with.
