### ISSUE TITLE
color scheme is not working

### ISSUE THREAD

**Issue by OliverXie2016** [reduxframework/redux-extensions#293]
Hi All,

I bought the color scheme extension and tried to set up the extension,it is failed.

i put the color_scheme folder in 
![image](https://cloud.githubusercontent.com/assets/20784244/19469534/4fabf070-954e-11e6-817b-4b02b0ea4869.png)

and with below code
![23](https://cloud.githubusercontent.com/assets/20784244/19469490/23dd795a-954e-11e6-821c-add36d15e925.png)
![33](https://cloud.githubusercontent.com/assets/20784244/19469496/26af9eb0-954e-11e6-8599-64d727ab4b1e.png)

please help~
Thanks

**Comment by OliverXie2016** [comment]
no color scheme section...

![3333](https://cloud.githubusercontent.com/assets/20784244/19469597/8e3f9e0e-954e-11e6-90e4-b197352e952a.png)

**Comment by kprovance** [comment]
It's in your config someplace.  You need to first verify your path to the extensions folder is correct.  Second you are calling setExtensions twice.  No need to do that.  Once will suffice, and it must be done after you have loaded your options arrays/configs.

At the very end of my options config, I use this:

```php
Redux::setExtensions( 'your_opt_name_here', dirname (__FILE__) . '/extensions/' );
}

Redux::init ();
```

Loads them all at once.  Also, if this is for ThemeForest, they will ding for dirname in place of available WP API.

**Comment by OliverXie2016** [comment]
i know the theory, but in my case no result come out, i already copyied the color scheme to extensions folder, in the meantime, another extension wbc_importer works

![image](https://cloud.githubusercontent.com/assets/20784244/19471564/6c0ddae6-9556-11e6-93cd-1ea2c024dc0e.png)
![image](https://cloud.githubusercontent.com/assets/20784244/19471572/7584c99a-9556-11e6-9c15-863e8ab1898d.png)

**Comment by OliverXie2016** [comment]
i mean i restored the extensions-init.php to default setting, and put the color_scheme folder in the extensions folder, system cannot recognize the color scheme, is there any seeting need to be configed in extension_color_scheme.php?

Thanks

**Comment by kprovance** [comment]
No.  Don't change any of that code.  I told you how to set it up.  Did you try it yet?

**Comment by OliverXie2016** [comment]
yes... but still the same...
![image](https://cloud.githubusercontent.com/assets/20784244/19472939/e622b676-955b-11e6-9e6f-43205ce283be.png)

so the environment for wbc_importer and color_scheme is the same, what caused this issue...

how about the arrays code? i believe it is correct as i copied it from Redux knowledge base
![image](https://cloud.githubusercontent.com/assets/20784244/19473035/6025ee8e-955c-11e6-8e48-7aaf3b960a81.png)

**Comment by kprovance** [comment]
The array code is fine.  The extension is not loading because it's not being loaded properly.  I told you how I load them in my theme, which I know works.  You are trying to load the extensions before your configs.  I stated setExtension has to be run AFTER config loading.  After.  Not before.

**Comment by OliverXie2016** [comment]
but it is the default setting  and there is no config file loading...

stange...

![image](https://cloud.githubusercontent.com/assets/20784244/19473325/b9983b1a-955d-11e6-8294-2c250456beba.png)

anyway i changed it to your rule... the same...

![image](https://cloud.githubusercontent.com/assets/20784244/19473396/09155d44-955e-11e6-9a83-b658a84e9aeb.png)

**Comment by kprovance** [comment]
Okay, this is becoming incredibly complicated when it doesn't need to be.  I have NO idea what the load order is for any of this.  So take those last two lines that load the extension, and stick them at the bottom of whatever file you have your option arrays in.  I'm not sure where this setup came from, but its causing more issues than solving.  In my theme, I have ONE file, option-config.php.  It's where ALL my option arrays are, and at the bottom, those two lines, and everything loads.  As for that other extension, I can;t speak to it.  We did not write it.

**Comment by OliverXie2016** [comment]
thanks Kevin, 

Hi @dovy , could you help with this?

**Comment by OliverXie2016** [comment]
Now i roll back to extensions loader, it is sill the same .

![image](https://cloud.githubusercontent.com/assets/20784244/19478766/60bb0b80-9576-11e6-8555-8ff12141792f.png)

load.php
![image](https://cloud.githubusercontent.com/assets/20784244/19478855/b3ddefe4-9576-11e6-94db-4eb22ff08666.png)

structure：
![image](https://cloud.githubusercontent.com/assets/20784244/19478893/dd8ab44e-9576-11e6-88ee-afc9c0bb77cd.png)
 
the wbc_importer works but  color_scheme doesn't

![image](https://cloud.githubusercontent.com/assets/20784244/19478941/02bf7682-9577-11e6-87ef-567b9a4ccb48.png)

BTW, my reduxframework version is 3.6.0.2

**Comment by OliverXie2016** [comment]
oooooohps... i found the reason, i missed an array in config file, it works now,  thanks Kevin.


![image](https://cloud.githubusercontent.com/assets/20784244/19481279/f15d478a-957f-11e6-9ff7-d813d422e1b1.png)
