### ISSUE TITLE
color scheme group

### ISSUE THREAD

**Issue by OliverXie2016** [reduxframework/redux-extensions#294]
thanks Kevin for help me solve the first issue, now i meet another one, when i create the color group the option panel doesn't show the accordion and actually i keep the accordion setting to true...

Code:
![image](https://cloud.githubusercontent.com/assets/20784244/19483351/9e357c60-9586-11e6-9590-b96e0f65212c.png)

Option panel:
![image](https://cloud.githubusercontent.com/assets/20784244/19483357/a2ec333e-9586-11e6-94c3-072775d716b6.png)

**Comment by kprovance** [comment]
I need you to post code please, not screenshots of code.  I can't try your code, and I don;t have the time to type it all in based on an image.  Thanks.

**Comment by OliverXie2016** [comment]
Redux::setSection( $opt_name, array(
            'title'  => __( 'Color', YOUYI_THEME_NAME ),
            'id'     => 'Color',
            'desc'   => __( 'Basic field with no subsections.', YOUYI_THEME_NAME ),
            'icon'   => 'el el-brush',
            'fields'           => array(
              array(
                    'id'            => 'opt-color-scheme',
                    'type'          => 'color_scheme',
                    'title'         => 'Color Schemes',
                    'subtitle'      => 'Save and load color schemes',
                    'output'        => true,
                    'compiler'      => true,
                    'simple'        => false,
                    'groups'   => array(
                        'Header' => array(
                            'desc'              => 'Set header and nav colors here. (Group open by default)',
                            'hidden'            => false,
                            'accordion_open'    => true
                        ),
                        'Body'   => 'Set body and content colors here.',
                        'Widget' => '',
                        ''       => 'These colors are not asigned to any group.'
                    ),

                    'default'       => array(
                        array(
                            'id'        => 'body-text', // ID
                            'title'     => 'body text', // Display text
                            'color'     => '#fdfdfd',   // Default colour
                            'alpha'     => 1,           // Default alpha
                            'selector'  => 'body',      // CSS selector
                            'mode'      => 'color',     // CSS mode
                            'important' => true,         // CSS important
                            'group'     =>'Body'
                        ),
                        array(
                            'id'        => 'body-background',
                            'title'     => 'body background',
                            'color'     => '#ededed',
                            'alpha'     => .5,
                            'selector'  => 'body',
                            'mode'      => 'background-color',
                            'important' => false,
                            'group'     =>'Body'

                        ),
                        array(
                            'id'        => '111-text', // ID
                            'title'     => '111 text', // Display text
                            'color'     => '#fdfdfd',   // Default colour
                            'alpha'     => 1,           // Default alpha
                            'selector'  => '111',      // CSS selector
                            'mode'      => 'color',     // CSS mode
                            'important' => true,         // CSS important
                            'group'     =>'Widget'
                        ),
                        array(
                            'id'        => '111-background',
                            'title'     => '111 background',
                            'color'     => '#ededed',
                            'alpha'     => .5,
                            'selector'  => '111',
                            'mode'      => 'background-color',
                            'important' => false,
                            'group'     =>'Widget'

                        ),



                        ),
                    ),

              ),
            )
           );

**Comment by kprovance** [comment]
That code actually works fine.  I'm beginning to think you downloaded the 1.x version of color schemes, which does not have accordion grouping.  I left that up there for legacy reasons.  You need to install the 2.x version.

**Comment by OliverXie2016** [comment]
seems the files i downloaded from account portal is old version... the file name is color_scheme-1.0.3.zip...

sorry, found another Version below.... 
![image](https://cloud.githubusercontent.com/assets/20784244/19505045/c59078bc-95f1-11e6-9b09-399abf248e53.png)

and it works now... thanks again for your patience Kevin!
