### ISSUE TITLE
combine the link color and color scheme group

### ISSUE THREAD

**Issue by OliverXie2016** [reduxframework/redux-extensions#295]
Hi All,

Can we combine the link color and color scheme group so that it is easier for user to manage?

![image](https://cloud.githubusercontent.com/assets/20784244/19511725/099e058c-961b-11e6-9679-8190b5a7e1e5.png)

right now if i put the link array code to color scheme, it only display one color.

![image](https://cloud.githubusercontent.com/assets/20784244/19511640/9e07c254-961a-11e6-873e-bb2ac6d5ff6e.png)

Thanks
Oliver

**Comment by kprovance** [comment]
Sorry, no.  Those fields are independent of one another.
