### ISSUE TITLE
Redux Metaboxes Extension Amazon S3 Issue

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-extensions#296]
Hi there,

Redux Metaboxes Extension

I reported this issue here (https://github.com/reduxframework/redux-extensions/issues/284) and was asked to open a new ticket with a support URL if it wasn't fixed in the update.

This issue is still not fixed but unfortunately I can't generate a support URL, when I click the button the page just hangs. 

A customer of mine has found the issue is fixed if you edit one line of code. In extension_metaboxes.php and line 319 find:

`$options = wp_parse_args( $data, $options );`

Replace with:

`$options = wp_parse_args( $options, $data );`

Is this a viable solution?

**Comment by ghostpool** [comment]
Has anyone had a chance to look at this?

**Comment by dovy** [comment]
@kprovance Did you verify this?

**Comment by kprovance** [comment]
Nope.  Don't know where that plugin can be found, or if it's free, how it's setup, what theme, versions any software involved, etc, etc.  And the support URL is kind of needed, even if it's from the client who has the issue.

**Comment by ghostpool** [comment]
I would have posted a support URL if it were working at the time, but as I explained it wasn't. Here's the support URL now the system is working: http://support.redux.io/?id=K3oM06Q5hZ8f41cNs%2BRfoiY7CMtM8o8UIe4Sp5LIvtazLyf8NKtqaQa6uxtkScpaSCW5Q%2FRstihjtR6wsjBRlg%3D%3D

When you responded to my first ticket you didn't even look at the issue you just pasted a response that this may have been fixed in the plugin update, without any idea if it had because you posted the same response to nearly all open metabox tickets.

I understand you don't have all the information, but you still could have looked into the issue as to whether` $options = wp_parse_args( $data, $options );` is the wrong way round. This could be independent of the CDN plugin conflict.

Anyway here's the links to the plugins:

Amazon Web Services: https://wordpress.org/plugins/amazon-web-services/
WP Offload S3 Lite: https://wordpress.org/plugins/amazon-s3-and-cloudfront/

Follow the plugin instructions for setting them up.

**Comment by kprovance** [comment]
Problem for me is, you also described an issue with the customizer, and that's beyond the scope of my expertise.  @dovy might have to get this one.

**Comment by ghostpool** [comment]
Ok and it's beyond my expertise as well - I'm just a paying customer reporting an issue and hoping the developers would look into it.

**Comment by kprovance** [comment]
@Dovy IS the developer.  I'm just the guy who answers these things.

**Comment by dovy** [comment]
Wow, I haven't looked at this in ages. @ghostpool was this resolved?

**Comment by ghostpool** [comment]
Nope, I'm still having to edit: 

`$options = wp_parse_args( $data, $options );`

**Comment by dovy** [comment]
@ghostpool message me on slack.
