### ISSUE TITLE
Output not working

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-extensions#297]
Hi there,

http://support.redux.io/?id=ID6H5%2F8bVfNvD71lZa9UYi5kXcFxyxc8cDZa2oHdbnTBUz07hxf9Xvu0gkL8qA2SKIlFEC1b4g%2FUuz1Kvt6L5w%3D%3D

The output variable does not work in Metaboxes extension - it does not output any code. It works fine in the Redux framework theme options page. This is an example of the code I'm using:

`
array( 
    'id' => 'post_page_header_height',
    'title' => esc_html__( 'Page Header Height', 'cuckoo-plugin' ),
    'subtitle' => esc_html__( 'A percentage of 48 means the header is almost half the height of the browser window.', 'cuckoo-plugin' ),
    'required' => array( 'post_page_header', '!=', 'gp-standard-page-header' ),
    'output'    => array( '.single-post .gp-page-header .gp-container' ),
    'units' => '%',
    'type' => 'spacing',
    'mode' => 'padding',
    'desc' => esc_html__( 'The height of the page header as a percentage.', 'cuckoo-plugin' ),
    'top' => false,
    'right' => false,
    'left' => false,
    'default'       => array(
        'padding-bottom'    => '48%', 
    )       
 ),
`

**Comment by kprovance** [comment]
Please update to v1.4.2 and see if the issue has been resolved.
