### ISSUE TITLE
Reduxt Metabox extension not working properly

### ISSUE THREAD

**Issue by manikbajaj** [reduxframework/redux-extensions#298]
Dear Team,

We are using redux Metabox extension. Suddenly we have noticed that it overwrites the value with my default page meta values. We have created a static page and we have set a meta for example "custom title" then we have configured this newly static page as front-page from reading so what i have seen is on archive pages I can see that meta value in my global option variable. 

Thanks

**Comment by manikbajaj** [comment]
I am unable to generate the support URL as well, it a WPMU installation and using redux version 	3.6.0.2

**Comment by kprovance** [comment]
Please update to v1.4.2 and see if the issue has been resolved.
