### ISSUE TITLE
Metaboxes with slide field not working after import

### ISSUE THREAD

**Issue by KAJOJEK** [reduxframework/redux-extensions#300]
Hi,

I have a latest version of Metaboxes extension 1.4.1

My problem is with "slide" field after import all content to new fresh wordpress installation.

Step 1. have a page with metabox "slide" field and all works fine.
Step 2. make export all content by wordpress to xml file.
Step 3. make import all content to new fresh install wordpress site.
Step 4. checking my page with "slide" metabox all works fine.
Step 5. edit this page and click save.
Steo 6. After refresh page "slide" field is broken, not worked button upload, delete, add slide... etc

Can anyone had a similar problem and can help me with this?

**Comment by kprovance** [comment]
Please upgrade to v1.4.2 and see if the issue is resolved.

**Comment by KAJOJEK** [comment]
Hello,

I have a redux version 3.6.0.2
metabox extension version 1.4.2 / Purchase Key af7cb8e7accbb1b778fc8deddedb766b

and I have a little problem with google fonts.

I’ve created metabox typography field for post type „page” and „post”.

In pages all working fine and google fonts are added to redux google css, but problem is in post type „post”.

I’ve choose google font, click update post and this font is added but not rendering in browser.
I’ve check file:
<link rel='stylesheet' id='redux-google-fonts-dts_option-css' href='http://fonts.googleapis.com/css?family=Source+Sans+Pro%3A200%2C300%2C400%2C600%2C700%2C900%2C200italic%2C300italic%2C400italic%2C600italic%2C700italic%2C900italic%7CArial%7CKhula%3A300%2C400%2C600%2C700%2C800%7CCabin+Sketch%3A400%2C700%7COpen+Sans%3A300%2C400%2C600%2C700%2C800%2C300italic%2C400italic%2C600italic%2C700italic%2C800italic&#038;amp&#038;subset=latin&#038;ver=4.7.3' type='text/css' media='all' />


and there is no this font.

In the pages I do the same and all works fine. Can you help me with this??

Best Regards
Karol Jarek
