### ISSUE TITLE
Redux Metabox Extension: Category/Taxonomies Extra Fields

### ISSUE THREAD

**Issue by fabeluna** [reduxframework/redux-extensions#301]
Hello,

one short question:
I think it isn't possible to add custom meta fields to "add/edit Taxonomy" page
 with Redux Metabox Extension, right?

![bildschirmfoto 2016-10-27 um 09 56 13](https://cloud.githubusercontent.com/assets/18407540/19759119/c30a9a4c-9c2b-11e6-8565-8318d5afe76e.png)

Thanks,
Leonie

**Comment by kprovance** [comment]
Forthcoming in a new extension, available soon.  You might consider our extension bundle, all of our extensions for one price (which I believes comes close to 45% off what they would all cost individually.)  This also will include new extensions.
