### ISSUE TITLE
redux notice

### ISSUE THREAD

**Issue by OliverXie2016** [reduxframework/redux-extensions#302]
Hi All,

I bought the ad remover and put it in extensions folder, but when i installed on another computer, the notice still come out... 

![image](https://cloud.githubusercontent.com/assets/20784244/19847239/7027fa92-9f80-11e6-8aea-c53717288218.png)

## The notice:
![image](https://cloud.githubusercontent.com/assets/20784244/19847178/fd404750-9f7f-11e6-8a45-cc47bfe2bec2.png)

## The code in config file is as below:

    // SOCIAL ICONS -> Setup custom links in the footer for quick links in your panel footer icons.
    $args['share_icons'][] = array(
        'url' => 'http://www.baidu.com',
        'title' => 'Visit Official Support Site',
        'icon' => 'el el-star-alt',
    );

    Redux::setArgs($opt_name, $args);

    /*
     * ---> END ARGUMENTS
     */

How can i fix this?

Thanks
Oliver

**Comment by kprovance** [comment]
Chances are it's not configured correctly.  The code you provided doesnt really say how you have extensions configured.  There doesn't seem to be a setExtensions call in there.

**Comment by OliverXie2016** [comment]
extensions are loaded automatically and no need to be configured i guess, that's why another 3 extensions are working fine. 

![image](https://cloud.githubusercontent.com/assets/20784244/19882061/bc23ffd4-a045-11e6-9ca1-20f96bc7f384.png)

or maybe the ad remover needs extra configration?

**Comment by kprovance** [comment]
Support URL, please.

**Comment by OliverXie2016** [comment]
sorry, we are working on local environment... finally i use CSS to hide this notice ...
