### ISSUE TITLE
redux welcome page

### ISSUE THREAD

**Issue by OliverXie2016** [reduxframework/redux-extensions#303]
Hi All,

As another case i mentioned, i bought the ad remover,  how can i also remove the Redux welcome page?

![image](https://cloud.githubusercontent.com/assets/20784244/19856082/ee617d48-9fb2-11e6-8f3f-df08a9ac3c62.png)

Thanks
Oliver

**Comment by kprovance** [comment]
Ad remover does not remove that page.  There is no way to remove it as we rely on the support system it offers
