### ISSUE TITLE
Color Schemes muliple modes possible?

### ISSUE THREAD

**Issue by fabeluna** [reduxframework/redux-extensions#305]
Hello,

I have a question to your Color Schemes Extension:
Is there a way to compile more than one css modes for one color value? I tried the output argument and two string values, but no success:

					array(
						'id'        => 'primary',
						'title'     => 'Primary Color', // Display text
						'color'     => '#fdfdfd',   // Default colour
						'alpha'     => 1,           // Default alpha
						'selector'  => '.ad-primary-color',     
						'mode'      => 'background-color, color',     // CSS mode
						'important' => true,         // CSS important
						'group'     => 'Theme Colors'       // Optional group name
					),

Is it possible to realize this with the color schemes extension or have I to go with the normal color field and output argument?

Thanks,
Leonie

**Comment by kprovance** [comment]
I need your purchase code and a support URL please.

**Comment by fabeluna** [comment]
Hello,

I can’t generate support link, the message appears "There was an error. Please try again later."
The wordpress Installation is not public, It is protected by htaccess rules. So I think that is the reaeon, why I can't generate a Support link? I can send you credentials for wordpres ftp, htacces protection. Or is there another way to proceed?

Thank you very much,
Leonie

**Comment by kprovance** [comment]
I really need version info for Reux, and versions of all extensions you are using, and your purchase code.

**Comment by fabeluna** [comment]
Hello Kevin,

Sorry, this is probably a stupid question, but how can I send you my purchase codes without being visible for the public?

**Comment by kprovance** [comment]
The four digit code you received with the purchase?  You can safely post it.  It's not data that can be used to 'steal' your purchase.  Either way, making the assumption you using the 2.x version of color schemes (this WILL NOT work with version 1.x) you can use arrays to specify multiple selectors.  Here is an example (and it's just an example, if you cut and paste this, you need to change the arguments to reflect your themes settings).

```php
    array(
        'id'        => 'main_accent',
        'title'     => esc_html__( 'Accent (Primary Color)', 'theme' ),
        'color'     => '#000000',
        'alpha'     => 1,
        'group'     => esc_html__( 'Main', 'theme' ),
        'selector'  => array(
            'color'             => '.color-class',
            'border-color'      => '.border-color-class',
            'background-color'  => '.bg-color-class',
        ),
    ),
```
Make sure you omit the `mode` argument when doing so, as it won't be needed.
