### ISSUE TITLE
Metabox extension: Metabox fields displaying also on options panel after update to 1.4

### ISSUE THREAD

**Issue by carmoreira** [reduxframework/redux-extensions#309]
Hi! 
After updating to 1.4.1 I am now seeing the fields created for metaboxes displaying on my options panel. Seems the first metabox fields array created is being added to the section created by last of my options panel. 

I was using 1.3 before where this is was not happening.

http://support.redux.io/?id=zdXpk9zpvSDmPNGhkep%2F0mU3BFIA1TNK9mDeGKhxshsZdhBFCZ5hgb%2FNtziIO0VGscf71vrX4P3orPLPSMCfcQ%3D%3D

I can provide a copy of my project via PM. 
Greetings, Carlos

**Comment by kprovance** [comment]
Been fixed in v1.4.2.  :)
