### ISSUE TITLE
Metabox use only without Redux-Menu in Backend

### ISSUE THREAD

**Issue by Stefan39** [reduxframework/redux-extensions#310]
Hi,

exists any possibility to use the metabox extension only without showing a redux menu into the backend?

I have try in the config param "menu_type" => "hidden" but not works.

**Comment by dovy** [comment]
@Stefan39 Yes... hmmm. How did we do that? It's entirely possible.

You could use `'customizer_only' => 'false'` I suppose.

**Comment by Stefan39** [comment]
Into the sample-config.php this not exists into the args arguments. If i use it in my config with redux framework as plugin (currently 3.6.2 with no updates) the admin menu also exists.

I use in my config:

	'menu_type'            => 'hidden',
	//Specify if the admin menu should appear or not. Options: menu or submenu (Under appearance only)
	'customizer'           => false,
	// Enable basic customizer support
	//'open_expanded'     => true,                    // Allow you to start the panel in an expanded way initially.
	//'disable_save_warn' => true,                    // Disable the save warning when a user changes a field
	'customizer_only'      => false,

Have no effects

**Comment by dovy** [comment]
Ha, I meant, set it to true.  ;)

**Comment by Stefan39** [comment]
'customizer'           => false,
	// Enable basic customizer support
	//'open_expanded'     => true,                    // Allow you to start the panel in an expanded way initially.
	//'disable_save_warn' => true,                    // Disable the save warning when a user changes a field
	'customizer_only'      => true,

The same result... no effect ;)

**Comment by dovy** [comment]
**sigh** It's in the docs of which I first referred: https://docs.reduxframework.com/core/arguments/#menu_type

```
Redux::setArgs( $opt_name, array(
    'menu_type'=>'hidden'
));
```

Also if you set `'customizer_only' => true` it's the same effect.

Best of luck!

**Comment by Stefan39** [comment]
Yepp i know it and i have set it both to true, but the menu point always shows into the admin menü (on the left, not the admin bar). So this argument have no effect!

**Comment by carmoreira** [comment]
I'm having a similar issue. Might create a different issue entry if it's better.
I'm trying to create a settings page that is accessible only via URL. Meaning I don't want it on the customizer, not as a menu/submenu and not in the admin bar. These are the settings I have:

<pre>
$args = array(
        'opt_name' => 'evslayout',
        'display_name' => __('My title','myplugin'),
        'page_slug' => 'evslayout',
        'page_title' => __('My title','myplugin'),
        'menu_type' => 'hidden',
        'menu_title' => __('My title','myplugin'),
        'page_parent' => 'edit.php?post_type=mycpt',
        'admin_bar' => false,
        'customizer' => false,
        'page_permissions' => 'manage_options',
    );
</pre>

If I go to the expected URL 
`/edit.php?post_type=mycpt&page=evslayout`
It displays the WP message
`Sorry, you are not allowed to access this page.`

If I change
<pre>
 'menu_type' => 'hidden',
</pre>
to
<pre>
 'menu_type' => 'submenu',
</pre>
The URL works, but this way I see the Link in the submenu of my Custom Post Type which I don't want. So it seems that somehow the 'hidden' value is not working properly? Or would there be a combination of settings that would allow for this? 

Thank you :)

**Comment by Stefan39** [comment]
I don't understand, why this ticket are closed. The problem always exist and this methods not works with the current redux version!

**Comment by kprovance** [comment]
It can't be done using hidden.  The panel urls will not be created then.  You can use cds to hide it.

**Comment by kprovance** [comment]
Css

**Comment by Stefan39** [comment]
Thanks kprovance, good idea!
