### ISSUE TITLE
Multiple css_layout border radius not working correct

### ISSUE THREAD

**Issue by udarts** [reduxframework/redux-extensions#315]
I am using the latest css_layout version (1.0.1) and notice a issue.
When I use 2 border radius elements on a same tab page, 1 I only use % as unit and the other rem as unit. When I try to change the one with the %, the field value changes to 40undefined, instead of 40%.

When I do some research and the console.log, I notice that it uses the second element with the rem as mainID (very weird), and it doesn't return the % as that mainID data-unit doesn't have the %, but the rem instead.

For the css_layouts I only have the border-radius set to true, the rest set to false.

So something is wrong in the code, but I can't put my finger on it.

Is someone able to reproduce it?

Cheers,
Stephan

**Comment by kprovance** [comment]
I need your support URL to reproduce it, otherwise it's all guesswork, and that'll take forever.

**Comment by udarts** [comment]
I have it on my local computer, so providing a link is kinda difficult.

**Comment by kprovance** [comment]
No:  This:  https://docs.reduxframework.com/core/generating-a-support-hash  It works on a local.

**Comment by udarts** [comment]
Ah, then here you go: http://support.redux.io/?id=UjV9ODXIxYtjb5MwhmWAqCFAbOCp9SeEuLYJ1WqtAEnOr4ZPEzmpddexrIIjoY2hspl0sJOVvf20tUd1u%2FvdSA%3D%3D

**Comment by kprovance** [comment]
Updated to v.1.0.2.  That should do it.  You'll have to log on to your account to get the update.
