### ISSUE TITLE
Can't make a purchase

### ISSUE THREAD

**Issue by shnjawee** [reduxframework/redux-extensions#316]
Hi,

As this is the only place where I can access support, I can't seem to make a purchase of any extension from your website.

Steps: 

1. Add items to chart
2. Fill in card details (card works and is in use)
3. Fill in billing details
4. Click on Purchase button
5. This error occurs:

`Error: There was an error processing your order. Please contact support.`

<img width="1081" alt="screen shot 2017-01-17 at 16 36 49" src="https://cloud.githubusercontent.com/assets/3066750/22029708/4c2394ea-dcd3-11e6-9742-4e6e65c5a9c1.png">

**Comment by kprovance** [comment]
What is your username on the site, let me see if I can dig into it.

**Comment by shnjawee** [comment]
@kprovance the username is visnjamvf

thank you

**Comment by kprovance** [comment]
Looks like there is an issue with our Paypal account.  I'll let you know when it's been resolved.  I do apologize.  It couldn't be helped.

**Comment by shnjawee** [comment]
@kprovance thank you for a prompt reply.

Is there another way to purchase these addons, while we're waiting for that Paypal fix?

**Comment by dovy** [comment]
@shnjawee send the total directly to billing@reduxframework.com via paypal, and then send me an email at support@reduxframework.com with your confirmation code and I will make a manual purchase.  :)

**Comment by kprovance** [comment]
It's been 48 hours.  Try again.  If you still get an error message, I'll use my PayPal account and be done with this this foolishness.

**Comment by shnjawee** [comment]
Hi @kprovance tried but error still persist. it seems like payment-method=stripe is not working for you. sorry but I need to be able to pay for this with my company's credit card, and can not use my personal card nor paypal to make a purchase.

is there any way you can fix this?

**Comment by shnjawee** [comment]
@kprovance any progress on this? Are other people able to make a purchase from your website or am I the only one?

note: I need to pay this by card, not paypal

thanks

**Comment by dovy** [comment]
Visnja/Helena:
```
Stripe risk evaluation: high
Primary risk factor: This card (4047) has been linked to a history of fraudulent activity. Learn more about risk evaluations.
```

Best to fix your credit problems first or contact Stripe. It's out of my hands. Your card has been flagged.

**Comment by shnjawee** [comment]
@dovy thanks for this. 

It is a company's card, so I asked them for another one, and finally was able to make a purchase. However, after clicking on purchase button, it took ages to finish, and I got 504!

![screen-shot-2017-01-27-at-09 52 56](https://cloud.githubusercontent.com/assets/3066750/22367209/4254638e-e478-11e6-903f-003da5cd03cc.png)

However, the payment went through.

Cheers
