### ISSUE TITLE
[SOLVED] Very slow admin-part when Redux is active

### ISSUE THREAD

**Issue by MaximOrlovsky** [reduxframework/redux-extensions#317]
Very slow admin-part when Redux is active
WP - v4.7.1
Redux - v3.6.0.2

**Comment by MaximOrlovsky** [comment]
When I turned developer mode off it works fine. Close the issue please.

**Comment by kprovance** [comment]
You also may want to update.  I think that was fixed already  v3.6.3.4 is the current one.
