### ISSUE TITLE
what is services licensing metabox extention

### ISSUE THREAD

**Issue by looking3** [reduxframework/redux-extensions#318]
Hello, dear. 

I want to use metabox extention to my wordpress themes.  
And I will sell the themes at themeforest.  

So, I want to know can I need for services licensing metabox extention or just buy the metabox extention at REDUX site?

If I have to need services licensing metabox extention for selling, how can get the services license and how much the services license cost.

Please, let me know what should I doto use the metabox extension and how can get the metabox extension. 

I look forward to your reply.

Thank you.

**Comment by kprovance** [comment]
The license for all extensions is yearly.  We expect you to keep your subscription active while the product in which you are using the extension is active.  The license is per product.
