### ISSUE TITLE
Metaboxes 1.1.8: PHP Notice: Undefined variable 'rewrite'

### ISSUE THREAD

**Issue by qwertydude** [ReduxFramework/redux-extensions#32]
Getting this notice in PHP:

PHP Notice: Undefined variable: rewrite
wp-content/plugins/pizazzwp-architect/application/includes/external/php/redux-extensions/extensions/metaboxes/extension_metaboxes.php:521

Does seem like a bug too.

**Comment by kprovance** [comment]
Metaboxes has been updates to ver 1.3.0.  Please upgrade and see if the issue persists.  If so, please open a new issue with the required information.  Thanks!
