### ISSUE TITLE
Date field does not work on posts

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-extensions#321]
URL: http://support.redux.io/?id=CzmK%2F8xzN9jC%2Fl%2Bj5cOu2rYjHe9n8L187f5gFWYCWc8%2FfgMQOlTdDonq6BRE5fy68ym8x9%2BGyPiN31CCl%2FzZDfVOxFhbSWNUPG23QzedxykoqT2XwLo%2BlJIBpVjMkuJa

Redux: 3.6.3.5
Metaboxes: 1.4.2
WordPress 4.7.2

The date field does not work on posts, it does however work on pages.

**Comment by ghostpool** [comment]
It's been over a month and no response?

**Comment by kprovance** [comment]
The date field is not an extension.  Also,big have no idea how such a thing would apply to the front end.  No code, example or workable scenario was provided.  ""

**Comment by ghostpool** [comment]
Add a custom field to a "post" post type using the Metaboxes Extension and set it to "date" field type. The calendar doesn't work. Do the same on a "page" post type the calendar does work.
			
```
array( 
	'id' => 'release_date',		
	'title' => esc_html__( 'Release Date', 'huber-plugin' ),
	'type' => 'date',
	'desc' => esc_html__( 'The release date of this item using the format yyyy/mm/dd e.g. 2017/03/31.', 'huber-plugin' ),
),

```

**Comment by kprovance** [comment]
Can't replicate.  Date fields open on both pages and posts. Did you try upgrading to the latest version?

**Comment by ghostpool** [comment]
The problem is I have another metabox panel on the page that is only shown when the Audio post format is selected. The calendar HTML is being added to this panel on the page which is hidden until the Audio format is selected. Once I selected the Audio format to display the audio panel the calendar is displayed when clicking inside the date field.

It seems the calendar needs to be added to the panel the date field is in and not the first panel on the page.

**Comment by kprovance** [comment]
Last time  I checked - and I'll do so again - jQuery renders that calendar HTML:  Redux does not do that part.

**Comment by ghostpool** [comment]
Yes jQuery renders the calendar, but you should have control over where the calendar is generated.

**Comment by kprovance** [comment]
The docs for datepicker don't show any type of argument that allows control over where the HTML is rendered.  It allows for the popup locatio, which is set at:

```
                              popover.position({
                                    my: 'left top',
                                    at: 'left bottom',
                                    collision: 'none',
                                    of: input
                                });
```

**Comment by ghostpool** [comment]
Redux appends the calendar to the first occurrence of ".redux-container" with this code:

`el.find( '.redux-datepicker' ).each( function() {
	$( this ).datepicker({
		"dateFormat":"mm/dd/yy",
		beforeShow: function(input, instance){
			var el = $('#ui-datepicker-div');
			//$.datepicker._pos = $.datepicker._findPos(input); //this is the default position
			var popover = instance.dpDiv;
			$('.redux-container:first').append(el);
			$('#ui-datepicker-div').hide();
			setTimeout(function() {
				popover.position({
					my: 'left top',
					at: 'left bottom',
					collision: 'none',
					of: input
				});
			}, 1);`

 If you change the line:

`$('.redux-container:first').append(el);`

To:

`$(this).parent().append(el);`

The calendar displays. I've not tested it under all circumstances but it seems to work.
