### ISSUE TITLE
Extentions load (step by step) ?

### ISSUE THREAD

**Issue by Roman1636** [reduxframework/redux-extensions#322]
Please, tell me how to load extentions step by step. I've tried many things before, I've read about it and it doesn't work. Thanks in advance! 
http://prntscr.com/eekq8j
http://prntscr.com/eekq8j
http://prntscr.com/eekq8j

**Comment by kprovance** [comment]
I would skip the antiquated loader and just go with the Redux API

https://docs.reduxframework.com/core/redux-api/

I cite the setExtensions API.  Just add it to the bottom of your option panel config file.
