### ISSUE TITLE
Metabox Plugin: Want to know if Metabox field has different value than Theme Options

### ISSUE THREAD

**Issue by ashffaq** [reduxframework/redux-extensions#323]
Hello There,

I have purchased Redux Metabox plugin and it's working great, Thanks for a brilliant piece of code.

I am just have a small issue.

I have created some theme options for single post, and then later, in single post created metabox from those theme options to update settings for individual post.

Now I want to know how can i get if option value is different than theme option. I know it updates global variable, but i want to do some conditional work based on if value is different then theme option.

Thanks.

**Comment by dovy** [comment]
We chatting in Slack, but here are the results of the conversation.

To disable the Redux Metaboxes override all together, run:
```
$redux     = ReduxFrameworkInstances::get_instance( $opt_name );
$metaboxes = $redux->extensions['metaboxes'];
remove_filter("redux/options/$opt_name/options", array($metaboxes,'_override_options') );
```
