### ISSUE TITLE
Widget Areas Extension issue

### ISSUE THREAD

**Issue by shnjawee** [reduxframework/redux-extensions#324]
Hi,

I have one registered sidebar in my theme's functions file called **Sidebar** with the id of **sidebar-1**.

Created a few widgetized areas via Appearance -> Widgets -> Create Widget Area (Redux Extension). But when using this in metaboxes:

`$box_sections[] = array(`
`                'title'   => __('Sidebar', 'demo'),`
`                'fields'  => array(`
`                    array(`
`                        'id'      => 'sidebar',`
`                        'title'   => __( 'Sidebar', 'demo' ),`
`                        'type'    => 'select',`
`                        'data'    => 'sidebars',`
`                        'default' => 'sidebar-1',`
`                    ),`
`                ),`
` );`

It only displays one, registered **Sidebar** from my theme. I created 5 new widgetized areas via redux extension.

**Note**: In front end I do get the full list of registered sidebars: 

`global $wp_registered_sidebars;`
`var_dump($wp_registered_sidebars);`

This returns the correct array of all 6 widgetized areas.

Am I doing something wrong? Or am I assuming wrong and expecting to have all registered AND redux registered widgetized areas in my `'data' => 'sidebars'` argument?

Any info is much appreciated.

Thanks,

V.

**Comment by shnjawee** [comment]
Figured it out.

Data parameter should read **sidebar** NOT **sidebars**.

`'data' => 'sidebar',`

Please update documentation as I've noticed in quite a few places that it's out of date.

Thanks

**Comment by kprovance** [comment]
Should not make a difference.

Line 1063 of the Redux core:
```php
} else if ( $type == "sidebars" || $type == "sidebar" ) {
```

However, without a support hash or more specific information regarding the dev environment, including version information...there is nothing more to speculate with.  Good luck.
