### ISSUE TITLE
[Metaboxes] Output argument on "index" pages

### ISSUE THREAD

**Issue by filip-jk** [reduxframework/redux-extensions#325]
Hello guys!

My metabox purchase ID is: #5356.

I'm having a little issue with the "output" argument not working properly with metaboxes options like colors etc on "archives" type pages like WooCommerce products archive. Even though I can edit the page (it exists in my Pages), Wordpress doesn't seem to treat it as a regular page because I always have to grab it's ID using get_option( 'woocommerce_shop_page_id' ) to get the page title and other metabox values.

So, is there any way of going around this so I can use the "output" argument for pages like that? Thanks!

**Comment by KAJOJEK** [comment]
in woocommerce.php you can use:
if( is_shop() ) {
    $page_id = wc_get_page_id( 'shop' );
}
$something = redux_post_meta( "your_option", $page_id, 'fieldID' );
