### ISSUE TITLE
Problem with google font in metabox extension

### ISSUE THREAD

**Issue by KAJOJEK** [reduxframework/redux-extensions#326]
Hello,
Purchase ID:  #6436
I have a redux version 3.6.0.2
metabox extension version 1.4.2 
wordpress version 4.7.3

and I have a little problem with google fonts.

I’ve created metabox typography field for post type „page” and „post”.

In pages all working fine and google fonts are added to redux google css, but problem is in post type „post”.

I’ve choose google font, click update post and this font is added but not rendering in browser.
I’ve check css file: id='redux-google-fonts-***-css' ... type='text/css' ...
and there is no this font.

In the pages I do the same and all works fine. Can you help me with this??

Thank You

**Comment by KAJOJEK** [comment]
I've tried to generate support URL, but I got an error message.

**Comment by KAJOJEK** [comment]
and idea ?? @dovy

**Comment by dovy** [comment]
@KAJOJEK if you can't generate a support URL, you have an error in your code somewhere. Turn on WP_DEBUG or look at the network activity when trying to generate the support URL. Something is really off there.

**Comment by KAJOJEK** [comment]
ok, I will check but I'm much interested the problem with google fonts in post type "post"
can  you check it?

**Comment by kprovance** [comment]
He needs the support url to do so.

**Comment by KAJOJEK** [comment]
I heve embedded version of redux, so where I can find any settings of url support? I have a debug set to true

**Comment by kprovance** [comment]
Here:  https://docs.reduxframework.com/core/generating-a-support-hash/

If you are talking about manually reporting back everything we need, it would take too long as there is too much of it...and at this point, I'm not sure how much of it would be accurate.  I'm almost will to be you have a PHP error log chock full of information you are not seeing because your PHP settings, which i why Dovy suggested you turn on WP_DEBUG so those messages will appear.  You have to understand, it's difficult to look into something when we cannot reproduce it.  I have my metabox demo, and my theme, which uses Redux and metaboxes, and I see output on pages, posts, products, every CPT there is.  There is something off your your system or your config and we need the support URL to make that determination.

If you are getting an error trying to generate one, open the javascript console log and see what message is provided.  There should be one, otherwise, please enable WP_DUB to see PHP error output, or check your PHP error logs for anything that might be pertaining to Redux.

**Comment by KAJOJEK** [comment]
Hi, thank you for your answer, that is log from my console:

`Object {readyState: 4, getResponseHeader: function, getAllResponseHeaders: function, setRequestHeader: function, overrideMimeType: function…}abort: function (a)always: function ()complete: function ()done: function ()error: function ()fail: function ()getAllResponseHeaders: function ()getResponseHeader: function (a)overrideMimeType: function (a)pipe: function ()progress: function ()promise: function (a)readyState: 4responseText: "4.7.44.7.4{"status":"success","identifier":"YVIObg1wqSNo7%2BsqPHZnGzmxYXOTbYs8L94ItkuFdR6ukyI4J5uAQrjasbW7dAlCjgJD9vLlgBIT%2B2d3jzYQBg%3D%3D"}"setRequestHeader: function (a,b)state: function ()status: 200statusCode: function (a)statusText: "OK"success: function ()then: function ()__proto__: Object`

**Comment by KAJOJEK** [comment]
@kprovance Can you help me with this ?

**Comment by kprovance** [comment]
ALl that console stuff tells me nothing.  Again, you need to activate WP_DEBUG (make sure your PHP.INI is set to show errors) and see what error output is causing all these issues.  Or, you could pull your PHP error logs and look for Redux related error messages.  This is not something I can do for you, I'm sorry.

**Comment by KAJOJEK** [comment]
can you contact me on email jojsonn@gmail.com. I will get you access to my wordpress??

**Comment by KAJOJEK** [comment]
@kprovance Hi, something is wrong with the redux builder. When I click generate admin folder I have the only loader and not get download file. I've tried to download new version because I still have a problem with generating support URL. I have debug set to true and don't have any PHP errors. 
Only like in the screenshot:
![screenshot](https://user-images.githubusercontent.com/11868435/27080867-287bb142-503e-11e7-9e4a-d31d54bf3a2c.png)

**Comment by KAJOJEK** [comment]
@kprovance , @dovy Problem with support URL resolved after update redux framework. So now maybe you can help me with google fonts in posts.

my support URL: http://support.redux.io/?id=1oTNy6jWfwpnR%2FHgtIEN2JrL2vvjvvFn4UE6J3ctL3ObuTYfVfM57cW0%2B5Ag38%2Fgy8tD9dVSVW46HQQ2OgJzSQ%3D%3D

**Comment by kprovance** [comment]
I ran your config.  I am unable to recreate the issue.  However, I am seeing multiple ids in your metabox config that are repeated.  Each one must be unique.  They only time they may be duplicated if they match up with an id in the option panel to inherit the global default.

You'll need to do some additional debugging.  Comment out the metabox option arrays for every post but BUT _post, so that only _post is loaded.  See if the issue continues.

**Comment by KAJOJEK** [comment]
Hello, thank you for your email. I've changed all duplicate id's and still have a problem with google fonts. When I choose google font in single post or single custom post type "portfolio" this font is available when I use echo 'font-famliy' but is not added to the stylesheet redux-google-fonts-dts_option-css. On pages everything is ok. 

http://support.redux.io/?id=1oTNy6jWfwpnR%2FHgtIEN2JrL2vvjvvFn4UE6J3ctL3ObuTYfVfM57cW0%2B5Ag38%2Fgy8tD9dVSVW46HQQ2OgJzSQ%3D%3D

**Comment by kprovance** [comment]
I asked you to comment out ALL metabox configs EXCEPT _POST.  Pages and portfolio should not even come up.  I want to focuc on _POST only with no other metabox optopns loading.  As portfolio was mentioned, I have to assume my words were misread or I was not clear  Please do this and see if the problem exists.  I loaded your config with all three metabox configs loaded, could not reproduce.  I loaded with JUST _POST, could not reproduce.  You have to understand, I cannot fix what I cannot break.

**Comment by kprovance** [comment]
Also, please check your PHP error logs for ANYTHING pertaining to Redux.  I need that information too, if any.

**Comment by KAJOJEK** [comment]
@kprovance ok, now I comment out all other metaboxes. Available are only for post and I don't see any php errors. Typography field still do not add google font family to google stylesheet.

**Comment by kprovance** [comment]
I'm at a loss now.  I can;t duplicate this in any way shape or form.

**Comment by KAJOJEK** [comment]
@kprovance can I give you access to my wp-admin ??

**Comment by kprovance** [comment]
It's @dovy 's extension.  If he wants to do that, it's up to him.  Otherwise, I need a subscription for premium support to do that kind of work.

**Comment by KAJOJEK** [comment]
@dovy Can you help me with this? It looks like extension issue.

**Comment by dovy** [comment]
@KAJOJEK I feel bad saying this, but it seems like an isolated issue. If we can't duplicate it anywhere, are you sure you're not doing anything off? Are you sure you are not delaying the load of metaboxes until too late? Look at when you're initing your Redux panel.

This really seems like an odd case in your environment as we haven't seen this before and can't duplicate it. In this case we would still need premium support to log into your panel. We're too hard at work on the next version of Redux to log into everyone's site. Sorry.

So let's break this down. The issue is that the font is not dynamically outputting to the website, correct? It's selected in the metabox, but you can't see it on the site.

Again sounds like you're loading Redux metaboxes too late and it can't load the CSS on the frontend. So delay the loading of your Redux panel, or init the loading of your metaboxes sooner.  :)

**Comment by KAJOJEK** [comment]
Thank you @dovy for your answer. 

I will show you how I init redux framework and extensions:

in functions.php in my theme:

`require_once(TEMPLATEPATH . '/admin/admin-init.php');`

in admin-init.php:
```

    // Load the TGM init if it exists
    if ( file_exists( dirname( __FILE__ ) . '/tgm/tgm-init.php' ) ) {
        require_once dirname( __FILE__ ) . '/tgm/tgm-init.php';
    }

    // Load the embedded Redux Framework
    if ( file_exists( dirname( __FILE__ ).'/redux-framework/framework.php' ) ) {
        require_once dirname(__FILE__).'/redux-framework/framework.php';
    }

    // Load the theme/plugin options
    if ( file_exists( dirname( __FILE__ ) . '/options-init.php' ) ) {
        require_once dirname( __FILE__ ) . '/options-init.php';
    }

    // Load Redux extensions
    if ( file_exists( dirname( __FILE__ ) . '/redux-extensions/extensions-init.php' ) ) {
        require_once dirname( __FILE__ ) . '/redux-extensions/extensions-init.php';
    }

    // Load Redux extensions
    if ( file_exists( dirname( __FILE__ ) . '/redux-extensions/loader.php' ) ) {
        require_once dirname( __FILE__ ) . '/redux-extensions/loader.php';
    }

    // Load Redux extensions
    if ( file_exists( dirname( __FILE__ ) . '/redux-extensions/config.php' ) ) {
        require_once dirname( __FILE__ ) . '/redux-extensions/config.php';
    }

```

and in config.php:
        
```
// INCLUDE THIS BEFORE you load your ReduxFramework object config file.


// You may replace $redux_opt_name with a string if you wish. If you do so, change loader.php
// as well as all the instances below.
$redux_opt_name = "dts_option";



if ( !function_exists( "rvolt_add_metaboxes" ) ):
    function rvolt_add_metaboxes($metaboxes) {
    

$postSections[] = array(
        'title' => __('Typography', 'my-theme'),
        'icon' => 'rvoltico-a-page-blog-transparent-menu',
        'subsection' => true,
        'fields' => array(  
            
            
            array(
                'id'            => 'post-header-typography',
                'type'          => 'typography',
                'title'         => __('Title font', 'my-theme'),
                'compiler'      => true,  // Use if you want to hook in your own CSS compiler
                'google'        => true,    // Disable google fonts. Won't work if you haven't defined your google api key
                'font-backup'   => false,    // Select a backup non-google font in addition to a google font
                'font-style'    => true, // Includes font-style and weight. Can use font-style or font-weight to declare
                'subsets'       => true, // Only appears if google is true and subsets not set to false
                'font-size'     => true,
                'text-transform'=> true,
                'text-align'    => false,
                'line-height'   => true,
                'word-spacing'  => false,  // Defaults to false
                'letter-spacing'=> true,  // Defaults to false
                'color'         => true,
                'preview'       => true, // Disable the previewer
                'all_styles'    => true,    // Enable all Google Font style/weight variations to be added to the page
                'output'        => '', // An array of CSS selectors to apply this font style to dynamically
                'compiler'      => '', // An array of CSS selectors to apply this font style to dynamically
                'units'         => 'px', // Defaults to px
            ),
            
            array(
                'id'            => 'subtitle-typography',
                'type'          => 'typography',
                'title'         => __('Sub-title font', 'my-theme'),
                'compiler'      => true,  // Use if you want to hook in your own CSS compiler
                'google'        => true,    // Disable google fonts. Won't work if you haven't defined your google api key
                'font-backup'   => false,    // Select a backup non-google font in addition to a google font
                'font-style'    => true, // Includes font-style and weight. Can use font-style or font-weight to declare
                'subsets'       => false, // Only appears if google is true and subsets not set to false
                'font-size'     => true,
                'text-transform'=> true,
                'text-align'    => false,
                'line-height'   => true,
                'word-spacing'  => false,  // Defaults to false
                'letter-spacing'=> true,  // Defaults to false
                'color'         => true,
                'preview'       => true, // Disable the previewer
                'all_styles'    => true,    // Enable all Google Font style/weight variations to be added to the page
                'output'        => '', // An array of CSS selectors to apply this font style to dynamically
                'compiler'      => '', // An array of CSS selectors to apply this font style to dynamically
                'units'         => 'px', // Defaults to px
                'default'       => '',
            ),
                                                               
        ),
    );

$metaboxes = array();

    $metaboxes[] = array(
        'id' => 'post-options',
        'title' => __('Post Options', 'my-theme'),
        'post_types' => array('post'),
        'position' => 'normal', // normal, advanced, side
        'priority' => 'default', // high, core, default, low
        
        'sections' => $postSections
    );

return $metaboxes;

  }
  add_action('redux/metaboxes/'.$redux_opt_name.'/boxes', 'rvolt_add_metaboxes');
endif;

// The loader will load all of the extensions automatically based on your $redux_opt_name
require_once(dirname(__FILE__).'/loader.php');


```
in single.php:

```
$page_id = $wp_query->get_queried_object_id();
$post_header_font = redux_post_meta( "dts_option", $page_id, 'post-header-typography' );
$subheader_font = redux_post_meta( "dts_option", $page_id, 'subtitle-typography' );

<?php 
               echo '<h1 class="custom-header-title" style="';
               if (!empty($post_header_font['color'])) {
                   echo 'color:'.$post_header_font['color'].'; ';
               }
               if (!empty($post_header_font['font-family'])) {
                   echo 'font-family:'.$post_header_font['font-family'].'; ';
               }
               if (!empty($post_header_font['font-size'])) {
                   echo 'font-size:'.$post_header_font['font-size'].'; ';
               }
               if (!empty($post_header_font['font-style'])) {
                   echo 'font-style:'.$post_header_font['font-style'].'; ';
               }
               if (!empty($post_header_font['font-weight'])) {
                   echo 'font-weight:'.$post_header_font['font-weight'].'; ';
               }
               if (!empty($post_header_font['letter-spacing'])) {
                   echo 'letter-spacing:'.$post_header_font['letter-spacing'].'; ';
               echo '">SAMPLE TEXT</h1>'; 
?>

```
In post it looks like this:

![screenshot at cze 19 11-14-54](https://user-images.githubusercontent.com/11868435/27278055-911700b6-54e0-11e7-9f2d-03de34952b12.png)

but font is not rendered.

If I do the same but only change to: 'post_types' => array('page'), google font are added to the stylesheet redux-google-fonts-dts_option-css.

Please check and let me know what I made wrong.

Thank You.

**Comment by KAJOJEK** [comment]
@dovy Please let me know if there is something wrong or I should buy premium support.

**Comment by KAJOJEK** [comment]
@dovy ok, I've bought a premium support with purchase id #8532. How can we contact to send you access to my WordPress??

**Comment by KAJOJEK** [comment]
@kprovance @dovy  What I should do with my Premium Support ????? I've paid $100 and what next ?????

**Comment by kprovance** [comment]
Issue has been resolved.
