### ISSUE TITLE
[Metaboxes] Problem after woocommerce update

### ISSUE THREAD

**Issue by KAJOJEK** [reduxframework/redux-extensions#327]
Hello,
Purchase ID:  #6436
I have a redux version 3.6.0.2
metabox extension version 1.4.2 
wordpress version 4.7.3
woocommerce 3.0

After update to woocommerce 3.0 I have a problem with my metaboxes in post type 'product'.

I've copied this from browser console:

```
select2.js?ver=3.5.2:930 Uncaught Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.
    at String.<anonymous> (select2.js?ver=3.5.2:930)
    at Function.each (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2)
    at constructor.prepareOpts (select2.js?ver=3.5.2:928)
    at constructor.prepareOpts (select2.js?ver=3.5.2:2601)
    at constructor.init (select2.js?ver=3.5.2:690)
    at HTMLSelectElement.<anonymous> (select2.js?ver=3.5.2:3391)
    at Function.each (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2)
    at a.fn.init.each (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,jquery-ui-core,jquery-ui-widget,jquery-ui-mo…:2)
    at a.fn.init.$.fn.select2 (select2.js?ver=3.5.2:3378)
    at HTMLSelectElement.<anonymous> (wc-enhanced-select.min.js?ver=3.0.0:1)
```

**Comment by dovy** [comment]
What that means is they didn't bind their select2 within their classes, but rather made it universal. Gah. Wish they hadn't done that. Hmm.

Thoughts @kprovance

**Comment by kprovance** [comment]
I tried it on my theme, which uses Redux and WooCommerce.  It sucks that they are using their 'enhanced' version to override all other instances of select2, especially the older version Woo is using.  I suppose someone ought to report this to them.  <sigh>  

I see the console error, but the select2 fields still render in metaboxes.  Are your select boxes still rendering properly?  If so, it's more of a WooCommerce issue as in this case, I don't see any references to objects used by Redux in the error trace.  At least not here, which is why I ask if your selects are properly rendering.  Let us know.

**Comment by KAJOJEK** [comment]
Thank you for your answer. I only use these fields in my products:

```
$productSections[] = array(
        'title' => __('MP3 Demo', 'my-theme'),
        'icon' => 'rvoltico-a-play-fill',
        'fields' => array( 
            
            
            
            array(
                'id'        => 'mp3-demo',
                'type'      => 'text',
                'title'     => __('Add mp3 URL (with http://)', 'my-theme'),
                'default'   => '',
                
            ), 
            array(
                'id'        => 'download-demo',
                'type'      => 'text',
                'title'     => __('Add external download URL (with http://)', 'my-theme'),
                'default'   => '',
                
            ),     
            
                                                               
        ),                                                          
        
    );

    $productSections[] = array(
        'title' => __('Hover image', 'rvolt-theme'),
        'icon' => 'rvoltico-a-blog-featured-image',
        'fields' => array(   
            
            array(
                'id'        => 'product-hover-image',
                'type'      => 'media',
                'url'       => true,
                'title'     => __('Hover image', 'my-theme'),
                'compiler'  => 'true',
                'mode'      => false, // Can be set to false to allow any media type, or can also be set to any mime type.
                'default'   => array('url' => '')
                
            ),  
            
                                                               
        ),                                                          
        
    );


```
and my fields looks like this:
![metabox-enable](https://cloud.githubusercontent.com/assets/11868435/25062577/d40fbe52-21ce-11e7-982c-e2ecbac0ffd6.png)

Additionally not working any tabs in product data.

When I remove my redux fields everything is ok.

I found similar problem here with ACS plugin:

https://imagewize.com/woocommerce-2-7-0-test-drive/

Backend Product Editing Issues

What I currently do have is working on the product details does not go well. It seems I cannot switch tabs to let’s say inventory or shipping.  But that seems to be an Advanced Custom Fields issue as I found this JavaScript error:

**Comment by KAJOJEK** [comment]
maybe that is problem with selec2.js version.
Woocommerce use version 4.0.3

/*!
 * Select2 4.0.3
 * https://select2.github.io
 *
 * Released under the MIT license
 * https://github.com/select2/select2/blob/master/LICENSE.md
 */

**Comment by ghostpool** [comment]
Isn't the solution to target a hidden input field rather than a select field? Is this not something you could fix on your end?

**Comment by dovy** [comment]
So you're asking us to add a hidden input field for woo? Doesn't that seem a little odd? We'd have to change our JavaScript too.

**Comment by ghostpool** [comment]
No I'm not asking you to do that. I was asking if the solution would be to add a hidden input for the selection fields generated by your framework. It was just a question, as I'm not clear what is causing the issue.

**Comment by kprovance** [comment]
I can't recreate it, at all.  I see the exact same messages and stack trace in the console, but my metabox renders and the tabs work fine.  All the tabs in the woo metaboxes work fine although I'm not sure if their select boxes are rendering.  Doesn't look like it looking at the HTML.

**Comment by ghostpool** [comment]
You should be able to replicate this issue on a WooCommerce products page (needs to be a variations product) and then click on the Variations tab which just keeps loading.

**Comment by kprovance** [comment]
So, we have to accommodate Woo by changing our product?  That sucks.  They chose to go the route of this enhanced select2 and now EVERYONE uses uses select2 must be on the same page?  Sorry, but I call bullshit on that one.  Woo need to be a little more considerate of other developers.

**Comment by KAJOJEK** [comment]
I've updated woocommerce to 3.0.3 and everything working now.

**Comment by dovy** [comment]
@KAJOJEK awesome. Good to know.

**Comment by monaye** [comment]
I've updated to WC 3.0.4 and still seeing the error when trying to change variations.

**Comment by kprovance** [comment]
Might need to click that link to the WC git and voice a complaint.  They claimed they 'fixed' it.  It's not something we can fix without rewriting parts of our core, which isn't likely to happen with this version.

**Comment by ghostpool** [comment]
It doesn't look like WooCommerce will be issuing a fix. Redux and WooCommerce are using two different versions of select2. WooCommerce says they won't be downgrading to v3 and don't see anyway to fix the conflict and Redux seem reluctant to upgrade to v4 so we're kind of at a stalemate. My solution currently is just to add a conditional check so the select2 files from Redux are not loaded on WC product pages:

Open core/enqueue.php and find:

```
wp_register_script(
    'redux-select2-sortable-js',
    ReduxFramework::$_url . 'assets/js/vendor/redux.select2.sortable' . $this->min . '.js',
    array( 'jquery' ),
    $this->timestamp,
    true
);
```

Replace with:

```
if ( get_post_type() != 'product'  ) {
    wp_register_script(
        'redux-select2-sortable-js',
        ReduxFramework::$_url . 'assets/js/vendor/redux.select2.sortable' . $this->min . '.js',
        array( 'jquery' ),
        $this->timestamp,
        true
    );
}
```

**Comment by kprovance** [comment]
It'll be fixed in the next major version, the Pro version.

**Comment by ghostpool** [comment]
The pro version of what? The metaboxes extension? The metaboxes extension is already a premium extension, is the pro version something new on top of this?

**Comment by kprovance** [comment]
As, shit.  Kinda let that slip.  I have been working (well, Dovy and I) on a premium version of Redux that is basically a complete rewrite that fixes everything, ever, that we are NOT giving away for free.  The core 3.x will always be free, but everything new and all the awesome new stuff will be Pro only.  It's the only way we are going to keep this project running since 99.9 percent of the devs who take our code and run never give back.

**Comment by dovy** [comment]
@ghostpool Don't worry. We'll find a solution. We may just prefix select2 for use in the core to avoid this pain. oy.

**Comment by kprovance** [comment]
Tried that already.  Woo overrides us and breaks our panel.

**Comment by dovy** [comment]
Meaning we rename select2 completely and make a redux version and then there will be no overriding.

**Comment by kprovance** [comment]
Off a cdn?  Changing the handle in the enqueue doesn't work.  Select v3 was made a cdn coz it was big

**Comment by kprovance** [comment]
Off a cdn?  Changing the handle in the enqueue doesn't work.  Select v3 was made a cdn coz it was big
