### ISSUE TITLE
[Metaboxes] Default field values are not saved when creating a post.

### ISSUE THREAD

**Issue by ghustavosm** [reduxframework/redux-extensions#328]
Default field values are not saved when creating a post.
But when the post is updated, the default values are saved.
Test: var_dump( get_post_meta( $ id ) );

**Comment by kprovance** [comment]
Please post your purchase code and your support hash:  https://docs.reduxframework.com/core/generating-a-support-hash/

**Comment by kprovance** [comment]
Well, maybe not.  get_post_meta will not pull the default.  You need to use redux_post_meta as described here:  https://docs.reduxframework.com/extensions/metaboxes/

**Comment by ghustavosm** [comment]
It would also be necessary to update update_post_meta() to be able to perform custom queries using meta values in posts.

**Comment by kprovance** [comment]
Well, that's up to the developer.  I'm simply telling you how put the default properly.  ;-)

**Comment by ghustavosm** [comment]
I see no difficulty for the Metaboxes Extension to update the meta values with the default values of the fields when creating a post, so I think it's a bug. Updating the meta post is essential to accomplish custom queries using meta keys.

**Comment by kprovance** [comment]
@dovy had a reason for not doing this.  He'll have to explain why, as I do not remember.  It was years ago.

**Comment by ghustavosm** [comment]
I found the part of the code that disables the saving of the default values:

extension_metaboxes.php
Line: 1160
if ( isset( $this->options_defaults[ $key ] ) && $value == $this->options_defaults[ $key ] ) {
	$save = false;
}

Would I have problems if that part of the code is removed?

**Comment by kprovance** [comment]
Still waiting on that purchase code, sir.

**Comment by ghustavosm** [comment]
I sent to email info@reduxframework.com

**Comment by dovy** [comment]
Default values were NEVER saved to the database to reduce on DB bloat. Why? Because we prefered not to pollute the database unnecessarily. ;)

But, I just added it to Metaboxes 1.4.3. You can now use the `metaboxes_save_defaults` in your global arguments to allow defaults saving to the database.  ;)

**Comment by dovy** [comment]
IE, go download the newest version to get what you want.  ;)

**Comment by ghustavosm** [comment]
Thank you! This is the best framework for Wordpress. 🥇

**Comment by ghustavosm** [comment]
Did't work.

I think you should remove the "!" From line 1190 (!$DontSaveDefaultsToDB):

$DontSaveDefaultsToDB = true; //default value

$save = true; // Save Defaults To DB

if ( !$DontSaveDefaultsToDB && isset( $this->options_defaults[ $key ] ) && $value == $this->options_defaults[ $key ] ) {
	$save = false; // Don't Save Defaults To DB
}

**Comment by dovy** [comment]
Ha, you're right. oops.

**Comment by dovy** [comment]
Please just make the change. It should work. I'll re-release it shortly.
