### ISSUE TITLE
Redux Framework Warning

### ISSUE THREAD

**Issue by webflux3007** [reduxframework/redux-extensions#332]
select2-js CDN unavailable. Some controls may not render properly. Please wait a few minutes, then try refreshing the page. Unable to load some remotely hosted scripts..

**Comment by kprovance** [comment]
Wait a few minutes and see if the server comes back up, or you have no valid connection to the internet (should you be working locally).  If the issue persists, you can always install the vendor support plugin, bypassing the CDN:  https://github.com/reduxframework/redux-vendor-support
