### ISSUE TITLE
Live Search

### ISSUE THREAD

**Issue by ACODA-LTD** [reduxframework/redux-extensions#335]
Hi,
When searching, the correct results show, however it seems to display all of the Section H2 tags too?

![screen shot 2017-05-02 at 12 21 55](https://cloud.githubusercontent.com/assets/4103430/25619842/3a0de814-2f44-11e7-968e-7e32b56c6672.png)

**Comment by dovy** [comment]
Is this from within metaboxes then? P.S. Glad you're liking Redux.  ;)

**Comment by ACODA-LTD** [comment]
Thanks for the reply @dovy :) 

No, this is just the main admin panel. Search from within the Metaboxes functions perfectly fine. 

For some reason the script is adding "display:block" to all the sections. See below: 

![screen shot 2017-05-02 at 19 45 21](https://cloud.githubusercontent.com/assets/4103430/25633701/f48a3974-2f6f-11e7-810a-b4bf409efbef.png)
