### ISSUE TITLE
[Repeater] Validation does't work

### ISSUE THREAD

**Issue by ghustavosm** [reduxframework/redux-extensions#336]
Hello! The validation for the premium repeater extension is not working.

**Comment by kprovance** [comment]
Purchase code and support URL/hash please.

**Comment by ghustavosm** [comment]
Do I write this information right here?

**Comment by dovy** [comment]
Yup. It's encrypted so no one will know.  ;)

**Comment by ghustavosm** [comment]
http://support.redux.io/?id=5RRSprGYeq4HrxC0D5lR8TFJZSt0vWQs92px3%2BnhxHIdHlPC3qkXW8XH0kS4MeYgEmg3z%2Bil7B3ea64GmIClsA%3D%3D

Invoice ID #7904
Purchase Key cfa821574c2388427f89be5163a6c7cc
Payment Status Complete
Payment Method PayPal Standard

**Comment by kprovance** [comment]
I don't believe validation has ever worked in the repeater.  @Dovy, was that the case?

**Comment by dovy** [comment]
Correct. Validation does not work in the repeater at this time. We haven't built it in yet.
