### ISSUE TITLE
[Repeater] "Button Set" field crashes

### ISSUE THREAD

**Issue by ghustavosm** [reduxframework/redux-extensions#337]
The "Button Set" field inside one repeater does not work if there is another repeater with another "Button Set" with the same ID. Other fields accept the same ID in different repeaters. This is important for code standardization. It's probably a javascript problem.

**Comment by kprovance** [comment]
Purchase code and support URL/hash please.

**Comment by ghustavosm** [comment]
http://support.redux.io/?id=5RRSprGYeq4HrxC0D5lR8TFJZSt0vWQs92px3%2BnhxHIdHlPC3qkXW8XH0kS4MeYgEmg3z%2Bil7B3ea64GmIClsA%3D%3D

Invoice ID #7904
Purchase Key cfa821574c2388427f89be5163a6c7cc
Payment Status Complete
Payment Method PayPal Standard

**Comment by kprovance** [comment]
Now I need to know what 'crash' means.  If it's an error, I need the specific error.  If you have stack trace data, that would also be helpful.

**Comment by ghustavosm** [comment]
There are two subsections, with a repeater in each of them with different IDs, but with the same fields, which have the same IDs. All other fields work correctly, but the "Button Set" does not work. The field is displayed, but clicking a button does not work correctly. The button is clicked, but the other button is not unchecked. And the values are also not saved.

The field that does not work is that of the second section, which is below the first section. What's in the first section works.

I've attached an image of what happens before and after clicking on the "button_set" buttons in the second section.

No errors are displayed on the console.

![button_set](https://cloud.githubusercontent.com/assets/2565300/25641614/6caabd34-2f6b-11e7-826f-dd4c9353a684.jpg)

**Comment by ghustavosm** [comment]
When you click a button marked it is not cleared.

**Comment by kprovance** [comment]
I see absolutely nothing in your config code that looks like that.  We're having a communication problem now.  I tried your repeater field with this section
```
                        array(
                            'id' => 'background-type',
                            'type' => 'button_set',
                            'title' => 'Tipo de background da seção',
                            'options' => array(
                                'normal' => 'Normal',
                                'parallax' => 'Parallax',
                            ),
                            'default' => 'normal',
                        ),
```
And it worked without error.

if you want me to try something, you need to be SUPER specific.  This section after that section means I have to go hunting, and I'd rather you just tell me the id I should be looking for, since I see nothing with Test1, Test 2, etc

**Comment by ghustavosm** [comment]
I did not know you could see my code. Then I will reproduce the error and send you the link again.

**Comment by ghustavosm** [comment]
http://support.redux.io/?id=5RRSprGYeq4HrxC0D5lR8TFJZSt0vWQs92px3%2BnhxHIdHlPC3qkXW8XH0kS4MeYgEmg3z%2Bil7B3ea64GmIClsA%3D%3D

Reload the page on the "Subsection 2" tab and try clicking on the buttons.

`Redux::setSection('test_opt', array(
	'id'     => 'test-section',
	'title'  => 'Test Section',
));

Redux::setSection('test_opt', array(
	'id'     => 'subsection-1',
	'title'  => 'Subsection 1',
	'subsection' => true,
	'fields' => array(
		array(
			'id'         => 'repeater-1',
			'type'       => 'repeater',
			'title' => 'Test Repeater',
			'group_values' => true,
			'fields'     => array(
				array(
					'id' => 'id',
					'type' => 'text',
					'title' => 'ID',
				),
				array(
					'id'       => 'button_set_test',
					'type'     => 'button_set',
					'title'    => 'Test',
					'options' => array(
						'test1' => 'Test 1',
						'test2' => 'Test 2',
						'test3' => 'Test 3',
						'test4' => 'Test 4', 
					 ), 
					'default' => 'test1',
				),
            ),
        ),
    ),
));

Redux::setSection('test_opt', array(
	'id'     => 'subsection-2',
	'title'  => 'Subsection 2',
	'subsection' => true,
	'fields' => array(
		array(
			'id'         => 'repeater-2',
			'type'       => 'repeater',
			'title' => 'Test Repeater',
			'group_values' => true,
			'fields'     => array(
				array(
					'id' => 'id',
					'type' => 'text',
					'title' => 'ID',
				),
				array(
					'id'       => 'button_set_test',
					'type'     => 'button_set',
					'title'    => 'Test',
					'options' => array(
						'test1' => 'Test 1',
						'test2' => 'Test 2',
						'test3' => 'Test 3',
						'test4' => 'Test 4', 
					 ), 
					'default' => 'test1',
				),
            ),
        ),
    ),
));`

**Comment by kprovance** [comment]
Try using different ids for the button_set.  Each one must be unique.  No two in the same project may be the same, or stuff like this can happen.

**Comment by kprovance** [comment]
Making issue as closed.
