### ISSUE TITLE
Metaboxs for terms

### ISSUE THREAD

**Issue by gonzela2006** [reduxframework/redux-extensions#338]
Hi,

Can I use metaboxs for term pages like category, tag,...?

Thanks

**Comment by BassemN** [comment]
Any help, please

**Comment by dovy** [comment]
We have a taxonomy extension we're finishing off shortly. It's production ready, but we're working on a new version of Redux that enhances it.  :)

**Comment by gonzela2006** [comment]
Is the taxonomy extension ready?

**Comment by kprovance** [comment]
No.
