### ISSUE TITLE
Social Profiles Extension - Background Clear Issue

### ISSUE THREAD

**Issue by ay-uk** [reduxframework/redux-extensions#340]
When trying to set the Background to transparent using the X (Clear Color Selection) button, I click on Choose. This sets all options to Transparent but the Social Icon Background is not transparent.
![social-profiles](https://cloud.githubusercontent.com/assets/16934421/26523538/ae98c0ec-4311-11e7-899c-80c8afdf48bc.jpg)

**Comment by kprovance** [comment]
I will need to see your purchase code and a support URL/hash, please.

**Comment by ay-uk** [comment]
http://support.redux.io/?id=ad9AkHt%2BgGk9QA3LzdCrO3bWQsLsLpZA4xYkrBEKdK86Pqi%2FaCj54RjbD2s0HsJlkGo%2FidcPIrqea1dU1bCllg%3D%3D

**Comment by kprovance** [comment]
It's a 4 digit code

**Comment by ay-uk** [comment]
4468

**Comment by kprovance** [comment]
Okay, I have verified the issue.  I'll get to it later this week after the holiday.

**Comment by ay-uk** [comment]
ok thank you.

**Comment by kprovance** [comment]
Social Profiles updated to v1.0.8.  You will need to log into your account to download the update.
