### ISSUE TITLE
Show section option icon in customizer

### ISSUE THREAD

**Issue by savanipriyank** [reduxframework/redux-extensions#341]
i am already using redux framework, in options page i have set icons with option label, 
check screenshot: http://prntscr.com/fhoonv

How can I show same option page icon in customizer with options, 
Need to show icon with screenshot: http://prntscr.com/fhooeg

Please provide me guide line for this.

**Comment by kprovance** [comment]
https://docs.reduxframework.com/core/sections/getting-started-with-sections/

icon argument.

**Comment by savanipriyank** [comment]
In this link show option work for only in options page.
Where is the option for show icon in theme customizer?

**Comment by kprovance** [comment]
That same argument handles the icon for both, there is no separate icon argument specifically for the customizer.

**Comment by savanipriyank** [comment]
Ok thank you

**Comment by savanipriyank** [comment]
should I need to add any other hook or filter for this?

**Comment by pjdemo** [comment]
Sample option page show Icons but not in customizer
http://screencast-o-matic.com/watch/cb1QQaXLyO
