### ISSUE TITLE
metabox call on frontend

### ISSUE THREAD

**Issue by hozyali** [reduxframework/redux-extensions#345]
I am using metabox on custom post-type. I am creating that custom post-type to be submitted from frontend as well. 

Wanted to check what is the best possible way to call redux metabox on frontend with my custom post submission.

Thanks

**Comment by kprovance** [comment]
First, we will need a valid purchase ID order (four numbers) to insure a valid subscription.

Second, you will need to be WAY more specific about your issue.  The only way to really cuse the Metabox API to retrieve settings ont he frontewnd is redux_post_meta.  Otherwise, I have no idea what you are talking about.  Specifically will be needed here, along with a support hash, if possible.

**Comment by hozyali** [comment]
Sure, it is 8427.

**Comment by hozyali** [comment]
Let me explain more.

I have created metabox for a post-type. let's call the post type to be LOAN. When an admin submits the LOAN post from the backend, he is able to enter the details in metabox as well. (metabox is woking for LOAN in admin).

Now I am creating this LOAN submission from the frontend of the website. So I need that metabox to be available in frontend as well. 

Let me know if you get it now.

Btw, how do I find the support hash?

Thanks

**Comment by kprovance** [comment]
One cannot show the actual metaboxes on the front end.  It's impossible.  All you can do it dsiplay the data entered on the backend via redux_post_meta:  https://docs.reduxframework.com/extensions/metaboxes/

**Comment by hozyali** [comment]
Do you recommend any other solution for frontend submission? Or I have to build the forms on frontend to allow the submission of those values?

**Comment by kprovance** [comment]
Something to enter information on the front end to save to get_user_meta?  I have no idea.  Maybe this: https://wordpress.stackexchange.com/questions/163530/how-to-save-selection-meta-data-in-user-profile-on-frontend

**Comment by hozyali** [comment]
Thank you

**Comment by kprovance** [comment]
Something with a shortcode to render an input array to save to get_user_meta.  Not impossible, but not easily done.  I don;t know if such a thing exists.
