### ISSUE TITLE
Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 262400 bytes)

### ISSUE THREAD

**Issue by otvitor** [reduxframework/redux-extensions#348]
"Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 262400 bytes) in /home/lungames/public_html/webteste/wp-content/themes/lunaticosgames/lib/redux-extensions/config.php on line 1864"

im getting this error, how do i solve this? 

website url: http://news.wellplayedteam.com.br/

**Comment by kprovance** [comment]
You need to adjust the memory setting in your PHP.INI.  As this is not a Redux issue, we are unable to assist with it.  Please contact your hosts for help.  Or, Google the issue, there are many, many articles about it.

**Comment by otvitor** [comment]
@kprovance already tried this and didnt solve the problem.

**Comment by kprovance** [comment]
Well, sorry, but it's not a redux issue.  Settings have to be changed.  Contact your server host for help.

**Comment by kprovance** [comment]
Or the theme author, since you paid him for support.  He should walk you through this.  We do not offer support to theme users.
