### ISSUE TITLE
unable to add Custom Metabox to Custom Post type

### ISSUE THREAD

**Issue by Abul4u** [reduxframework/redux-extensions#349]
Hi, I go through this doc https://docs.reduxframework.com/extensions/metaboxes/, and I tried all probability to load the custom metabox to custom post type but every time I fail.

there is extension-init.php file which says all custom metabox file should be in configs folder but it fails to load.

can you explain me why this long string "redux/metaboxes/{$redux_opt_name}/boxes"?

I knew {$redux_opt_name} will replace with my option "redux/metaboxes/$redux_data/boxes".

**Comment by kprovance** [comment]
Have you actually purchased the metabox extension?  It is NOT part of the Redux core.  If so, please provide us with your four digit purchase code.  Thanks.
