### ISSUE TITLE
Media type not inheriting parent option. 

### ISSUE THREAD

**Issue by ACODA-LTD** [reduxframework/redux-extensions#350]
Support Hash

http://support.redux.io/?id=7%2FCO6TTfpjbrvsaFbVKlchmq8GJVGMBXVbepTnv3rS9%2Bh%2B22gK4DmQkIgoMnnDIRNivkgvlIjnFj%2BAG7KhVqmg%3D%3D

Steps to reproduce

Set a background image via Theme Options > Header > Header Styling > Background Image. The Page or Post will not inherit this option. Instead, it's blank. Suggesting it's taking the blank field value within the Page or Post.

I'm dumping the header_image variable for reference.

Expected Behavior

When saving the Background Image theme option, it should update the Pages and Posts. Like with other options, such as the Header Background Color.

However, even with this, I seem to have to double save the Theme Options in order for it to take affect.

Actual Behavior

It appears the Post / Page Metabox option overrides the Theme Option, even though it's blank.

Any Error Details (PHP/JavaScript)

None

**Comment by ACODA-LTD** [comment]
This is what is set for the Theme option and correlating metabox option: 

Theme Option:

			array(
				'id'       => 'header_image',
				'type'     => 'media', 
				'url'      => true,
				'title'    => __('Background Image', 'dynamix'),
				'subtitle' => __('Set a Background Image.', 'dynamix'),
			),	

Metabox Option:

			array(
				'id'       => 'header_image',
				'type'     => 'media', 
				'url'      => true,
				'title'    => __('Background Image', 'dynamix'),
				'subtitle' => __('Set a Background Image.', 'dynamix'),
				'default'   =>  '',
			),

**Comment by kprovance** [comment]
When you specify a default in the metabox option array, it overrides the default.  But since no default is specified in the default, it will be blank anyway.  So, what exactly is the issue.  No default = blank.  Seems everything it working as intended?  Remove the default argument from the metaboxes array and then set something via the option panel.  Should work then.

**Comment by kprovance** [comment]
Rest your option panel, just to be sure.  If this is a database issue, that will nuke that problem.  In fact, I would even go as far as creating a new page AFTER you remove the metabox default.

**Comment by ACODA-LTD** [comment]
I've with and without a default and the same issue occurs. Other options are fine, including the Header Background Color. It's just media for some reason.

**Comment by kprovance** [comment]
I've done all I can.  If @Dovy wants to chime in, since it's his extension, he can.  I know it works, I use it in my own theme.  You just have to follow my instructions.  Good luck.

**Comment by ACODA-LTD** [comment]
Thanks Kevin. I've just tried the following again:
1. Removing the default value from the metabox. 
2. Created a new page, which inherited the Background Image fine. 
3. Changed the Theme Options Background Image, but the page did not inherit the new value, instead it displays the previously saved value. 

Thanks in advanced for your help!

**Comment by kprovance** [comment]
Unless you are willing to pay for my time via Premium Support. it's @dovy 's issue now.

**Comment by ACODA-LTD** [comment]
I wouldn't mind paying if it was for something custom Kevin, but I've paid $124 for this extension and it's not working properly.

**Comment by kprovance** [comment]
I am assuming your subscription is current, that you've not cancelled (if you have, it's another thing entirely).  Do you have your purchase code?  Problem is, Dovy gets that money.  I do not.  For me to go onto your server and debug this whole thing is my time.  The alternative is to wait for Dovy to do it.  I tagged him in.  Best I can do.

**Comment by ACODA-LTD** [comment]
Understood. Yes, all purchases are current, I started this project using Redux only a few months ago. 

I would login to grab the purchase code, but I think a plugin maybe deactivated for the the login form ;) 

https://reduxframework.com/account/

**Comment by ACODA-LTD** [comment]
Any ideas what this might be @dovy, it's the last part of finishing the theme, but I can't release it without it? Thank you.

**Comment by ACODA-LTD** [comment]
Any news on this? I'm having issues in general with Metabox options overriding the Global option set. It's becoming frustrating, is there a way to reset the metabox options?

**Comment by dovy** [comment]
Make sure your priorities are correct. Meaning don't load your panel before your metaboxes are called. Most people try to run the metaboxes on init because that's how the WP documentation says to do it. DO NOT run it at Init, because Redux loads on init.  ;)

**Comment by ACODA-LTD** [comment]
I'm just defining the metabox options within the options-init.php file ( below the main options ) with the following line.

add_action('redux/metaboxes/'.$opt_name.'/boxes', 'redux_add_metaboxes');

Is that not correct, if not how do you recommend initiating the metaboxes?

**Comment by dovy** [comment]
I'm talking about your custom post type. When are you loading it? The WP.org codex says to load at init. I say, take off the hook and just run it instantly.

**Comment by ACODA-LTD** [comment]
It's happening on Posts & Pages, not a custom post type.

**Comment by kprovance** [comment]
Also, be aware, you MUST load your metabox config BEFORE you load your options config, and then call the action hook stuff.

**Comment by dovy** [comment]
Yes. Make sure you're running it before.
