### ISSUE TITLE
Redux - Visual Composer Front-End editor

### ISSUE THREAD

**Issue by visualmodo** [reduxframework/redux-extensions#352]
Hello Redux Team! how are you?
I'm a very happy user of your framework for a long time and would like to say that your team did an amazing job!

Newsdays i'm having an error between the redux metaboxes
I use the redux to add meta information in my pages, add images on header for example however when I try to load the **Visual Composer Front-End editor** the meta information disappear. I'm using an old version of the **Redux add-ons metaboxes (1.3.0)**, is there a fix for this error in the latest version? or a way to work around? maybe an add-ons? if so, I would be very happy in purchase the framework again but I would like a discount once I'm a long-time client and fan of your work and donate as well.

Any feedback would be much appreciated

Have a great day
thank you for any help.
All the best

**Comment by kprovance** [comment]
You need to upgrade to the latest version of Metaboxes, in which this was fixed.  You subscription needs to be current to download that update.  if it is, log into your account and grab the update.  If not, you will need to repurchase your subscription and keep it current.

Thanks!

**Comment by visualmodo** [comment]
Ok,

We intend to buy, but login does not work, your plugin is disabled.

https://reduxframework.com/account/

**Comment by dovy** [comment]
Whoops. Back up.  ;)
