### ISSUE TITLE
Framework Comeback to Default Value

### ISSUE THREAD

**Issue by amirulfarhann** [reduxframework/redux-extensions#353]
Hello.

Recently, I've purchased a Wordpress theme from a theme developer. They use Visual Composer for page builder, The redux framework is being used under the 'package options'. The development started from backend editor in which I will set up the page layout, tags, and the 'packages option'. Then, I will go to the VC front-end editor to insert the content and images. Next, I will click the update button and usually if I close or go back to the backend editor, the settings on the layout and "package options" will be set to back default.

 It is like they forgot the settings and return to the default value. Here's the situation:

![capture1](https://user-images.githubusercontent.com/23257547/31875696-d1815cee-b801-11e7-820c-ae9f130362a3.PNG)
--Above: This the package options that I've set up on the backend editor. After setting it up, I go to front-end editor and add content, etc.--

![capture](https://user-images.githubusercontent.com/23257547/31875512-1216fb98-b801-11e7-89fa-25da7d14c653.PNG)
--Above: This is what happens after I went from front editor to backend editor. The data is gone and return to the default value or zero.--

I've contacted the theme developer but they never responded. I have to solve this as soon as possible due to my client's demand.

Please help me. Thank you.

**Comment by kprovance** [comment]
You need to contact your theme author for support in this matter.  We have no way of knowing how they used hook or filters to modify Redux.  Sorry.  Good luck.

**Comment by kprovance** [comment]
Give me theme theme devs user name on Theme-Forest.  I'll get him to reply.  Nobody likes bad review.

**Comment by amirulfarhann** [comment]
The theme developer's name is **nicdark**. The theme that I've bought is Love Travel theme.

Here's their profile on themeforest: https://themeforest.net/item/love-travel-creative-travel-agency-wordpress/7704831?ref=nicdark

**Comment by kprovance** [comment]
Message sent:  https://themeforest.net/item/love-travel-creative-travel-agency-wordpress/7704831/comments?page=75&filter=all#comment_17823937

**Comment by amirulfarhann** [comment]
Thank you very much! Can you update to me if they ever respond to you?

**Comment by kprovance** [comment]
Sure thing.  Being a theme author myself on TF, there is one thing I despise, and that's people dissing on me.  So, I expect he;ll see your issue here on TF and be amicable.  If there is seriously an issue with Redux, then he needs to do the work to see what it is and report it to us, and then we see about what the issue is.  ;-)

**Comment by dovy** [comment]
Looks like they responded with a blanket response. Hopefully they get back to you!

**Comment by amirulfarhann** [comment]
They didn't solve the problem. It is really hard for the support team to respond. I'm really rushing to solve the issue since my client demanded me to solve it ASAP. Hmm

**Comment by dovy** [comment]
We offer premium support, but really it's hard for us to support a product we've never seen.

**Comment by kprovance** [comment]
I hate to tell you to go this route, but you need to go to the review page of that theme, leave a one star review and the reason why.  Trust me, that will get their attention

**Comment by amirulfarhann** [comment]
I had reviewed them in themeforest. Not sure they will respond or not. On your site, is there any occasion that people stumbled upon the similar issue as I am?

**Comment by kprovance** [comment]
No.  As said. We have no way to know how the author is using redux.  It's why it's easier for him to investigate this.  You might consider asking theme forest for a refund for non support and unfixed issues.

**Comment by kprovance** [comment]
I left him another message, in mostly nice terms to get off his ass and support you.

**Comment by amirulfarhann** [comment]
I found something as I googled random keyword to search for the solution. Here's your conversation at 2015: https://github.com/reduxframework/redux-framework/issues/2288

Is this issue has been solved? I think it is a similar issue to mine. Thanks.

**Comment by amirulfarhann** [comment]
Also this: https://github.com/reduxframework/redux-extensions/issues/183

Where can I edit the functions as you explained?

**Comment by kprovance** [comment]
That was fixced.  But, ONCE again, the theme author has to look into this, keep Redux up to date, and Metaboxes and its subscription up to date.  We cannot do these things for him.  I'm sorry its not the answer you want to hear.  But the them author has to investigate, and if he can reproduce, come to us with his findings.  We cannot update his theme, only he can.

**Comment by amirulfarhann** [comment]
The current version of my website as I check is  3.5.8.10. Is this version covered the solution of the framework as per discussed?
--

**Comment by kprovance** [comment]
The author needs to upgrade, badly.  Also, it's a metabox issue, and I'm guessing it too is outdated.

**Comment by amirulfarhann** [comment]
Yayy! I found the file in which I need to add few lines that causing the issue, exactly as you solved it before. The theme developer until now is completely silent and not responded anything. Lucky enough that I got the solution just before meeting with my client.

Thanks to you guys!! Best support service ever!

**Comment by kprovance** [comment]
Yeah, then he also had an old version of Metaboxes.  It's unfortunate.  Folks need to keep their vendor code current.  Glad it worked out.  Be warned however, if you or the client updated the theme, when updated are available, doing so will cause those changes to be lost.  I did get another reply from the author will some BS which is don;t even believe.  I guess he wants people to pay for additional support plans?  Bad business.  Client are supposed to get obligatory support for at least the first six months.  TF policy.  If he violated that, I would seriously consider sending TF a complaint via their help forum and let them know they have another deadbeat on their hands.  Good luck!
