### ISSUE TITLE
Not Able To Renew Subscription To Download Updates

### ISSUE THREAD

**Issue by manikbajaj** [reduxframework/redux-extensions#354]
Hey!! 
On your website, I am not able to renew my subscription to download the most recent version of the extensions we have purchased previously. 

I see the download button on the Extensions page and then there is this error. There is no way I can click on renew my subscription. Please see the screenshots.

![screen shot 2017-10-24 at 8 08 21 pm](https://user-images.githubusercontent.com/3671946/31949575-4ca8f346-b8f7-11e7-8901-9ad3a15a0d75.png)
![screen shot 2017-10-24 at 8 08 36 pm](https://user-images.githubusercontent.com/3671946/31949576-4cf86bb0-b8f7-11e7-9b97-7a7679f96e49.png)

**Comment by kprovance** [comment]
It means at some point you opted to cancel your subscription.

**Comment by manikbajaj** [comment]
Hey didn't even realize that 😄 . Can you tell me a way ahead now? I can renew the subscription.

**Comment by dovy** [comment]
If you cancelled a subscription, the only way to is to re-order. To keep with updates, it's best not to cancel the subscription.  ;)

**Comment by manikbajaj** [comment]
That's what I am saying I am unable to reorder from the website. Do I need to create a new account now just to renew my subscription ?

**Comment by dovy** [comment]
@manikbajaj get on slack  http://slack.redux.io. We can do this in real-time.
