### ISSUE TITLE
Metaboxes & Custom Post Types

### ISSUE THREAD

**Issue by ACODA-LTD** [reduxframework/redux-extensions#356]
Hi, 

I'm still experiencing some issues with Metaboxes. The latest issue is that it's inheriting the options set on the Home page on Custom Post Types, including WooCommerce. Setting any new options on a CPT do not work. 

Normal Posts work as expected, it's just CPT. 

## Support Hash
http://support.redux.io/?id=yiDJntMtOXoq%2FutLZTHHJu7AOZGmPka0yEN7o3S3ZoPOAbby3o%2BNdljvlyC5lxvXKqOcwBJHPtYJqXOse5JCDA%3D%3D

## Steps to reproduce
Set any Metabox option on a CPT or simply create and save a new CPT post. 

## Expected Behavior
To override the global options, like with normal Posts. 

## Actual Behavior
It inherits the settings from the Home page and setting any new on option on the CPT doesn't work. 

## Any Error Details (PHP/JavaScript)
Doesn't appear to display any issues.

**Comment by ACODA-LTD** [comment]
Update: 

I've set the "Portfolio" CPT to query_var => false and this now appears to work. 

However, this isn't a solution for custom post types that I don't have control over. I.e. WooCommerce. 

I don't have any Metaboxes setup for WooCommerce Products, but it inherits the Metabox options that are set on the Home Page... not sure how that works?

**Comment by ACODA-LTD** [comment]
Ok, looks like I've resolved the issue. 

Changing the following line in extension_metaboxes.php resolves the issue: 

$this->post_id = $this->url_to_postid( ( is_ssl() ? 'https://' : 'http://' ) . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] );

to this instead:

				$url = explode('?', ( is_ssl() ? 'https://' : 'http://' ) . esc_url( $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"] ) );
				$this->post_id = ( isset($_GET['page_id'] ) ? esc_attr( $_GET['page_id'] ) : url_to_postid( esc_url( $url[0] ) ) );

**Comment by ACODA-LTD** [comment]
Just wanted to mention that I am using Metaboxes 1.4.4, I see from the Change Log you've done some work on this in the past.

**Comment by kprovance** [comment]
Your proposed change does not work under all scenarios  It returns zero when used with bbPress.  When you make a core change, you must test it with every possible mix of software, or at least the popular ones.  As you want this change, it's your job yo do it.  You might also try NOT loading your CPT on Init.  I know WP says that's the right way, but for this purpose, you need to load it on php page load (or in __construct is you are using OOP).

**Comment by ACODA-LTD** [comment]
Hi Kevin, 

That's why I removed it, I tested with a couple of other plugins and it failed. Changing the query_var on my plugin is fine, that works. 

However, the issue still stands with WooCommerce. It's not returning 0 ( or the Shop ID as you'd expect ), it's returning the home page ID and inheriting those metabox options. Any ideas?

**Comment by mzrahmani** [comment]
Hi Kavin,  @kprovance I am having the same issues using metabox with CPT, Redux js and css files are not being loaded on CPT, I can see the metabox on CPT edit page but not styled, any idea ?

**Comment by mzrahmani** [comment]
Here is how I fixed the issue:

`add_action('wp_loaded', function(){
    global $pagenow;

    if($pagenow == 'post.php'){
        $redux_en = new Redux_Enqueue(Redux::instance('RIAO_settings'));
        $redux_en->init();
    }
});`
