### ISSUE TITLE
Metaboxes & Output Argument

### ISSUE THREAD

**Issue by ZoOmArts** [reduxframework/redux-extensions#360]
Hello guys!

I have a question about Metaboxes extension before the buying.
Is it possible to use the 'output' argument?

Regards!

**Comment by dovy** [comment]
Yes actually. CSS output properly gets appended the the pages provided you're on the proper page. On archives it can get more tricky.  ;)

**Comment by dovy** [comment]
P.S. Sorry about the late response. Didn't see this.
