### ISSUE TITLE
extension-boilerplate Saving Pblm

### ISSUE THREAD

**Issue by niraj547** [reduxframework/redux-extensions#361]
Hi thr,
I stuck in really silly pblm, I tried to create a website_loader extension using extension-boilerplate.
Everything was working fine like I can see all the website_loader gif etc. I can select it too but when ever I tried to save, It won't save 
`echo '<input data-id="' . $this->field['id'] . '" name="'.$this->field['id'].'" id="'.$this->field['id'].'" type="hidden" value="'.$this->field['default'].'" /><div class="loaders-container">';`

i don't know why it's not working 

thanks

**Comment by kprovance** [comment]
This issue tracker is for registered users of our extensions and no for development of them.  That is a premium service.  I'd be happy to help if compensated for my time.
