### ISSUE TITLE
javascript:void(0)

### ISSUE THREAD

**Issue by Dimeba** [reduxframework/redux-extensions#362]
Hi guys, i' m trying to upload an image to the gallery and i buttons won't work, i just get a notification javascript:void(0) at the bottom.

It statred today after the last plugin update.

![capture](https://user-images.githubusercontent.com/8440186/41877065-3dcb0bcc-78d0-11e8-893f-0eef812aca77.PNG)

**Comment by kprovance** [comment]
Wrong issue tracker.  Also, if you are the user of a theme, you need to contact the theme author.  We did not author any theme.
