### ISSUE TITLE
Little help

### ISSUE THREAD

**Issue by ionut2014** [reduxframework/redux-extensions#364]
I need some little help because i dont understand something.
I made my WP theme with underscore and Redux. All ok, done

Problem is when i install my theme , activate it and i go to my page i can’t see some features.
if i go to theme options, and just hit SAVE, and go to home all are ok.

Problem is because i have in theme options some features like change color, choose top bar to be hidden or not. so all this are in first hidden and visible on hit save.

Can someone offer some ideeas to fix this?

in sections for theme option i have

https://www.writeurl.com/publish/pvbbz9ebnl736i8rqfhn
link with code as example

So all my options that i have in theme options, i need first to save settinhs the will be shown in page.

How can i make that they to vosoble as default like: header to be shown, top bar,  footer, colors ?

**Comment by kprovance** [comment]
The kind of help you are looking for is premium.  This issue tracker is for bug reporting.  If you wish to book us at $100.00 per hour to review your theme, we would be happy to.  Please contact kevin@reduxframework.com for more info.  Good luck.
