### ISSUE TITLE
It redirects to redux.

### ISSUE THREAD

**Issue by panyachuaipun** [reduxframework/redux-extensions#366]
Hello reduk Team
I use the redux plugin. Then it put me in front of the plugin.
It redirects to redux.
Tell me how to fix it.
https://youtu.be/1SLmYD3ZNXc
Please Help 
Thank

**Comment by kprovance** [comment]
This issue tracker is for our extensions.  Please post to our core issue tracker here: https://github.com/reduxframework/redux-framework/issues

Also, please take the time to read the text provided in the new issue window so you know what information we require.

Thanks.
