### ISSUE TITLE
CSS Layout issue

### ISSUE THREAD

**Issue by zacholas** [reduxframework/redux-extensions#367]
Not sure how to submit a proper pull request, so am posting here.

For the CSS Layout extension, if you set "compiler" to "true" rather than an array, there's an error thrown from css_layout/field_css_layout.php on line 635 because it's trying to implode something that's not an array.

I changed the "if" to check and make sure it's an array before imploding and that fixed it:

```// Compile, um...compiler data
if (!empty($this->field['compiler']) && (true == $this->field['compiler']) && is_array($this->field['compiler'])) {
    $css = $this->getCSS();
    $keys = implode( ",", $this->field['compiler'] );
    $this->parent->compilerCSS .= $keys . "{" . $css . '}';
}
```

**Comment by kprovance** [comment]
Oh lordy...I wrote that so long ago.  Ya, that would be an issue.  Thanks for the catch.  I will update this.
