### ISSUE TITLE
Metaboxes and sorter error

### ISSUE THREAD

**Issue by Ryu-k** [reduxframework/redux-extensions#368]
I just noticed today, it is maybe since the new WordPress update but when I try to move the sorter in the page metabox I got this error :  

Uncaught TypeError: Cannot read property 'limits' of undefined
https://themecheck.wpengine.com/wp-content/themes/cesis/admin/redux-framework/inc/fields/sorter/field_sorter.min.js?ver=1533814795 line 1

Support URL

http://support.redux.io/?id=ElVMjS4FzcFGNq4tlzDd3lDu%2F%2F4oKgupXqZHcKJHTDbLT1UB9PHEqdJJXUrMzx0DWs92QrbrfbbF8URySlM0rw%3D%3D

Kind regards

PS : In the theme panel it works fine, disabled all the plugins only the theme is activated.

**Comment by kprovance** [comment]
Well, first, that's a min file, so there is only one line there.  No way to parse that out.

I cannot reproduce this here, so I suppose I am going to have to login to your site and see what's going on.  I'll need a few things.  First, please enable dev_mode to true so there are no min JS files loaded.  Second, I'll need temp admin backend access and FTP access in case I have to debug code.  You can email that to kevin@reduxframework.com as not to post sensitive info here.

**Comment by Ryu-k** [comment]
I sent you an email.

Thanks for the prompt reply, really appreciate it.

Kind regards

**Comment by kprovance** [comment]
Resolved.  More or less.  ;-)
