### ISSUE TITLE
unsave fields when page refresged

### ISSUE THREAD

**Issue by aicul2018** [reduxframework/redux-extensions#371]
hello,

when I click on button add to shopping cart and don´t fill one of the required fields, the page will reload with a message “this field is required” but all the fields I filled out did not save.. and I have to fill them again 🙁

can u help me pls?

http://support.redux.io/?id=cmi6bHdm2SGpNKNZCK6yDAiPLoo2I2gbfDDvQhc7%2BSbQ2%2F2mqjxpkyA6YjwDt107RXThK4NZUpNPiS%2FSOmQUEw%3D%3D

**Comment by kprovance** [comment]
Please contact the author of the theme for support as we do not support actual theme users. We have no way to know how theme authors implement our code. Good luck.
