### ISSUE TITLE
Adding additional metabox to existing array via child theme

### ISSUE THREAD

**Issue by shnjawee** [reduxframework/redux-extensions#373]
Hi @dovy,

Hope you are well.

I'm struggling to add a new metabox to an existing array of metaboxes via Child Theme? - hope this makes sense. Overwriting metabox-init.php in child theme does not do the trick.

Take for example this one: [https://docs.reduxframework.com/extensions/metaboxes/](https://docs.reduxframework.com/extensions/metaboxes/)

How do you add a new metabox to `$boxSections[]` in this case - via child theme please?

Thank you.

**Comment by kprovance** [comment]
I'm not showing a current subscription for this extension.  Subscriptions must be current before we are able to offer updates or support.
