### ISSUE TITLE
Initiate metabox through plugin

### ISSUE THREAD

**Issue by zacholas** [reduxframework/redux-extensions#374]
Hi guys, I haven't been able to find anything on this, so sorry to bother you with it. Let me know if this Q is covered with my purchase or if you'd like me to pay for some sort of support subscription if it's not.

The Q:

I'm using Redux in a child theme I start with for client sites that has PUC on it, so for any customizations beyond my base theme, I'm doing those via plugin, as any direct customizations to the theme will get overwritten whenever an update is pushed.

I am trying to add one additional metabox via plugin for a client site and can't find a good way to do it. I've tried adding an apply_filters/do_action to the code in the metaboxes config file, but no luck. Is there any way you can think of to hook in additional metaboxes via external plugin?

Thanks,

Zach

**Comment by kprovance** [comment]
Please provide your four digit purchase code.  Subscriptions must be current.

**Comment by zacholas** [comment]
9048

**Comment by zacholas** [comment]
And actually, as it turns out, I made a silly mistake. Forgot to set the var to the apply_filters. I was able to get it working with the following line:

``$metaboxes = apply_filters('mytheme_metaboxes', $metaboxes);``

right before the 

``return $metaboxes;``

Sorry bout that.
