### ISSUE TITLE
Multi Media cannot remove items you just added

### ISSUE THREAD

**Issue by zacholas** [reduxframework/redux-extensions#375]
Pretty simple bug to reproduce:

1. Create a multi-media option
2. Choose some items for it from the media library
3. Immediately after choosing the items, try to remove one with the minus sign next to it
4. It will **_not_** be removed.

If you save your options and refresh the page, however, you can remove them. So maybe just a js selector issue, not being aware of DOM updates or something like that.

**Comment by kprovance** [comment]
Hey!  I'm sorry it took this long to reply.  Somehow this issue went right over my head (I got caught up in another one, so I apologize).  Usually I am on top of the premium stuff.  Give me some time to dig into this and I will get back to you.  I am sure it's something simple I overlooked.  Will let you know!

**Comment by zacholas** [comment]
No worries; will watch this thread. :) Thanks Kev

**Comment by kprovance** [comment]
Sorry about the wait.  Holidays and a huge code audit I've been obsessed with.

I got this issue fixed.  While I was in there I audited that code too and fixed a bunch of potential security risks.  Eventually I will do it for all the extensions, but this one is ready to go.  Getting it on the site may take some time, so I can either email it to you (you can ping me at kevin@reduxframework.com) or if you are on our Slack channel, my nick is @Kev and I can DM it to you there.

Let me know!

**Comment by zacholas** [comment]
Cool, thanks a lot Kevin. No worries on the wait. I'll shoot you an email now.

**Comment by kprovance** [comment]
Sent.  :)

Cheers.

**Comment by zacholas** [comment]
Hmm, still haven't gotten it. (Checked spam as well)

Thanks,

Zach

**Comment by kprovance** [comment]
Google based email?  Sometimes they get weird with ZIP files.  I am going to resend it with the file extension .rename.  Obviously, rename it to zip after you get it.  Let me know.  Sending now.
