### ISSUE TITLE
warning messages    

### ISSUE THREAD

**Issue by vollmerag** [reduxframework/redux-extensions#376]
I am receiving the following error messages as my site loads. What is causing this and how can it be fixed? Help!

Warning: Invalid argument supplied for foreach() in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 930

Warning: array_change_key_case() expects parameter 1 to be array, string given in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 824

Warning: Invalid argument supplied for foreach() in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 825

Warning: array_change_key_case() expects parameter 1 to be array, string given in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 824

Warning: Invalid argument supplied for foreach() in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 825

Warning: array_change_key_case() expects parameter 1 to be array, string given in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 824

Warning: Invalid argument supplied for foreach() in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 825

Warning: array_change_key_case() expects parameter 1 to be array, string given in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 824

Warning: Invalid argument supplied for foreach() in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 825

Warning: array_change_key_case() expects parameter 1 to be array, string given in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 824

Warning: Invalid argument supplied for foreach() in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 825

Warning: array_change_key_case() expects parameter 1 to be array, string given in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 824

Warning: Invalid argument supplied for foreach() in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 825

Warning: array_change_key_case() expects parameter 1 to be array, string given in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 824

Warning: Invalid argument supplied for foreach() in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 825

Warning: array_change_key_case() expects parameter 1 to be array, string given in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 824

Warning: Invalid argument supplied for foreach() in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 825

Warning: array_change_key_case() expects parameter 1 to be array, string given in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 824

Warning: Invalid argument supplied for foreach() in /home/vollmera/public_html/wp-content/plugins/redux-framework/ReduxCore/inc/fields/typography/field_typography.php on line 825

**Comment by kprovance** [comment]
Please note, if you are the USER of a theme, that is you purchased a theme that is giving you errors, you must contact the theme author for support, as we have no way of knowing how they implemented Redux.  As I see it's embedded, there is no way for me to fix his code.  Otherwise, if you are the author of the theme, this needs to be posted here:   https://github.com/reduxframework/redux-framework.  Please read this carefully, because it's important:  When you open the new issue window, there will be a black text there detailing what information we require for free support.  Please read that entire block of text and post back that information.  Sending me a list PHP warnings doesn't tell me a whole lot.  Thanks!
