### ISSUE TITLE
Gutenberg incompatibility

### ISSUE THREAD

**Issue by ghostpool** [reduxframework/redux-extensions#377]
Hi there,

Are there any plans to update the metaboxes extension to work Gutenberg? Currently all the metaboxes are shown ignoring page template/post format conditions and all the JS functionality (select2 dropdowns etc.) do not work. Would like to know before I purchase a new license for it?

**Comment by dovy** [comment]
We are indeed working on a new version. We are also baking a lite version into Redux 4 basic.  ;)

**Comment by ghostpool** [comment]
Sounds good Do you have ETA on the standalone version update?

**Comment by kprovance** [comment]
You have to have a current subscription to get any updates.  You cancelled yours a while ago.

**Comment by ghostpool** [comment]
I know I need to renew my license to get the updated files - I mention that in first post. I was asking when the new update may be released - unless you’re saying I need to renew my subscription just to get this information? In which case that isn’t going to happen, why would anyone do that?

**Comment by kprovance** [comment]
Uh.  No, that's not what I was saying.  I have no idea when.

**Comment by ghostpool** [comment]
Ok I’ll probably move to platform that is already Gutenberg compatible then. It’ll also be nice to not have to deal with your passive aggressive responses. Dovy manages to be polite, you should try it sometime as well.

**Comment by dovy** [comment]
@ghostpool we’ve already fixed it. But it’s tied to Redux 4. We’re getting close to a release on that. We’ll be sorry to see you go.

**Comment by ghostpool** [comment]
Thanks for the response Dovy. 

Oh ok, so will there be an updated standard alone version anymore and if so will this be compatible with Redux v3?

**Comment by kprovance** [comment]
Nope.  Sorry.  Redux Pro only, for v4.
