### ISSUE TITLE
Featured Post option 

### ISSUE THREAD

**Issue by niraj547** [reduxframework/redux-extensions#378]
Hi
Is thr a way to add feature post checkbox in post type meta box option?

**Comment by kprovance** [comment]
There is.  I did it for my theme years ago.  I'm technically on vacation and dont have my code assets with me so I dont have a specific example handy.  That said, read this:  https://smallenvelop.com/how-to-create-featured-posts-in-wordpress/

So basically, create a checkbox on your metabox options array and make its ID "meta-checkbox"  The data will save to the page post meta.  As an aside, WP does not automatically apply some magic code to display featured posts.  You'll have to do your own front end code, as suggested by the provided article.  Good luck!

**Comment by niraj547** [comment]
OK thanks for the response... I already tried that approach just wanted to know if thr is anything i can do that in redux option. Just wanted to save time.. thanks anyways
