### ISSUE TITLE
submenu not show in admin side

### ISSUE THREAD

**Issue by Jasmeen1347** [reduxframework/redux-extensions#383]
I was installed reduxframework and add two submenus in basic field but that not show on the admin side  
here is my code and screen shot of admin side
`Redux::setSection( $opt_name, array(
        'title' => __( 'Basic Fields', 'redux-framework-demo' ),
        'id'    => 'basic',
        'desc'  => __( 'Basic fields as subsections.', 'redux-framework-demo' ),
        'icon'  => 'el el-home'
    ) );

    Redux::setSection( $opt_name, array(
        'title'      => __( 'Heder', 'redux-framework-demo' ),
        'desc'       => __( 'Custom Logo' ),
        'id'         => 'Header-setting',
        'subsection' => true,
        'fields'     => array(
            array(
                'id'       => 'logo',
                'type'     => 'media',
                'url'      =>true,
                'title'    => __( 'Custom Logo', 'redux-framework-demo' ),
                'desc'     => __( 'Field Description', 'redux-framework-demo'),
                'default'  => 'Your Logo',
                
            ),
        )
    ) );
    Redux::setSection( $opt_name, array(
        'title'      => __( 'Footer', 'redux-framework-demo' ),
        'desc'       => __( 'Footer copyright' ),
        'id'         => 'footer-setting',
        'subsection' => true,
        'fields'     => array(
            array(
                'id'       => 'copyright-footer',
                'type'     => 'textarea',
                'title'    => __( 'footer copyright', 'redux-framework-demo'),
                'desc'     => __( 'footer copyright', 'redux-framework-demo'),
                'default'  => 'Site is copyright by technocomet',
                
            ),
        )
    ) );
   i was also add two submenu in body menu but it is not show here is code
   Redux::setSection( $opt_name, array(
        'title' => __( 'Body', 'redux-framework-demo' ),
        'id'    => 'Body',
        'desc'  => __( 'Body.', 'redux-framework-demo' ),
        'icon'  => 'el el-home'
    ) );
    Redux::setSection( $opt_name, array(
        'title'      => __( 'bg-color', 'redux-framework-demo' ),
        'desc'       => __( 'bg-color customizer' ),
        'id'         => 'bg-color',
        'subsection' => true,
        'fields'     => array(
            array(
                'id'       => 'body-bg-color',
                'type'     => 'color',
                'title'    => __('Body Background Color','redux-framework-demo'), 
                'subtitle' => __('Pick a background color for the theme','redux-framework-demo'),
                'default'  => '#FFFFFF',
                'validate' => 'color',
            ),
        )
    ) );
     Redux::setSection( $opt_name, array(
        'title'      => __( 'font-color', 'redux-framework-demo' ),
        'desc'       => __( 'font-color customizer' ),
        'id'         => 'font-color',
        'subsection' => true,
        'fields'     => array(
            array(
                'id'       => 'body-font-color',
                'type'     => 'color',
                'title'    => __('Body font Color','redux-framework-demo'), 
                'subtitle' => __('Pick a font color for the theme'),
                'default'  => '#000000',
                'validate' => 'color',
            ),
        )
    ) );`

the screen shot is here
![redux](https://user-images.githubusercontent.com/46520962/50948616-154f2080-14c9-11e9-8255-dcb89813cb8c.png)

**Comment by kprovance** [comment]
Sorry, but...

1) This is not an extension issue.
2) Our support form is not filled out properly.  For free support, you must go here and submit ALL required information.
3) Your last issue was closed because of 2.

https://github.com/reduxframework/redux-framework

Thanks

**Comment by Jasmeen1347** [comment]
I can't understand what is an issue
