### ISSUE TITLE
Redux spam without redux extensions?

### ISSUE THREAD

**Issue by michaldybczak** [reduxframework/redux-extensions#384]
Since some time I started to see some redux framework notifications. I had no idea what it is and where did it come from. I disabled the notification but I noticed today redux framework news... What the hell?

I found the website, checked extensions and... nothing clicks, meaning I don't recognize anything. Some extension must have added redux but there is no clear branding on it so redux framework brand shows as something unrelated and surprising like... malware. It does create unwanted advertisements but since I have no clue what it is it's only aggravating me.

So if I have some extensions adding it, it's adding redux framework covertly and that is a problem because it doesn't serve your business at all and looks more like a malware behavior (unwanted adds).

There are many extensions which are upfront about the brand and the company that is making them, advertising other extensions from them. I can understand that. But this covert behavior is super bad for everyone.

Is there a list of FREE extensions associated with Redux Framework spamming with your advertisements? I only found this list:
https://reduxframework.com/extensions/

But it shows only premium, paid extensions that I don't have.

**Comment by dovy** [comment]
@michaldybczak The ads only appear in these circumstances:
- WP_DEBUG = true
- dev_mode = true
- The site is running locally

The extensions built into Redux core (free) are:
- import/export
- customizer lite
- options object

The rest of our extensions add extra functionality and are premium.

We do, however, have over 36 fields that are free and give most users what they want. And later this year, after Redux 4 is released, we'll be releasing Redux Pro that will incorporate all of the extensions.

Hope this answers your questions.

**Comment by michaldybczak** [comment]
Ah, in my case WP_DEBUG=true is set and I do have customizer lite. Thanks for the explanation.

However it still weird that Customizer isn't showing clearly it's under Redux agenda. You would be also surprised in a bad way and confused when you would start to see some advertisements for an unknown company and didn't know where does it come from.

**Comment by dovy** [comment]
Remember Redux can run in customizer_only mode. Hence why we do the same thing as we do in the panel.  ;)

**Comment by michaldybczak** [comment]
I literally have no idea what you just have said. What is "customizer_only mode"?  The same thing as in the panel? What things, what panel?

**Comment by kprovance** [comment]
https://docs.reduxframework.com  i'd begin there.
