### ISSUE TITLE
Social Profiles Extenion Redux Wordpress

### ISSUE THREAD

**Issue by maheraldous** [reduxframework/redux-extensions#385]
Hello Thank you for the great work. I was wondering where I can download the Social Profiles to the Redux. I have redux as a addons plugin in my theme. I read this article https://docs.reduxframework.com/extensions/social-profiles/ and this https://github.com/ReduxFramework/redux-extensions-loader but no help. I understood how to setup the extensions in Redux from this article https://github.com/reduxframework/redux-extensions/issues/197 but I don't know how to get the Social Profiles extension. The extension is not exciting here https://redux.io/extensions/. How to get the Social Profile Folder ?

**Comment by maheraldous** [comment]
Please need help @kprovance and @dovy

**Comment by dovy** [comment]
@maheraldous This extension has been discontinued from the Redux marketplace. You can interact with Kevin directly via kevin.provance@gmail.com. Thank you.

**Comment by maheraldous** [comment]
So there is no Social Profile any more?

**Comment by maheraldous** [comment]
Is there another code to use instead of Social Profiles

**Comment by dovy** [comment]
There is a social profiles extension that @kprovance built. He will have to arrange for you to get it. We are no longer selling his extensions through our marketplace. I am sure Kevin will be more than willing to assist.

**Comment by maheraldous** [comment]
Thank you for the informations I will contact him.

**Comment by dovy** [comment]
He'll take good care of you.  ;)
