### ISSUE TITLE
Get a link to the page or the post from 'type' => 'select' option

### ISSUE THREAD

**Issue by maheraldous** [reduxframework/redux-extensions#386]
Hello
@dovy 
Can anyone help me with 'type' => 'select' option.
I created a select option and made it displaying pages only, but the thing is I can't figure out how to get the url of the selected page. if I use this method $test['opt-select-pages'] I get only the index number of the selected page
Best Regards
Maher Aldous

**Comment by dovy** [comment]
Gladly. You can refer to this page for mapping to the WordPress functions.

https://docs.redux.io/configuration/argument-data.html#built-in-values

We only store the ID because it is sure to never be "stale" since you always fetch the updated info using one of the WordPress functions.

**Comment by maheraldous** [comment]
Thank you :)

**Comment by dovy** [comment]
You're so very welcome.
