### ISSUE TITLE
NEED to Cancel Subscription / Refund 

### ISSUE THREAD

**Issue by prionkor** [reduxframework/redux-extensions#387]
Last year I purchased the extension repeater. It had the old redux freamwork code, the extension wasn't updated for ages. Your site has no support system instead of github issues.

When I want to cancel the subscription there was no option. I coudn't ask for a refund as well. Few days ago I have charged again. When I go to view invoice nothing opened up. 

Please someone respond to this ticket and tell me what I have been missing or I will have to file a chargeback.

**Comment by prionkor** [comment]
I have asked for refund last year but no one responded. I am taking appropriate actions for chargeback.

https://github.com/reduxframework/redux-extensions/issues/365

**Comment by dovy** [comment]
@prionkor I am sorry there was no response. We most recently changed management of refunds. If you can supply me the product(s) you used the extension in, as well as if it’s PayPal or Stripe I will look into it.

**Comment by dovy** [comment]
And that ticket seems like there very much was a response. Did you ever get it running?

**Comment by prionkor** [comment]
I was trying to use it for a project but wasn't able to integrate later didn't used it. I used debit card for purchase so I think it is stripe. I can not provide further payment details here in public ticketing system. Please advice how to proceed.

**Comment by dovy** [comment]
Email dovy@redux.io. ;)
