### ISSUE TITLE
Google map extension

### ISSUE THREAD

**Issue by Jinjacko** [reduxframework/redux-extensions#388]
Hello
I 'm using wilcity theme
I want to create departure and arrival fields based on google adderss autocomplete
So that the entered locations selected when creating listings could be searchanble
Can this extension do that ?

https://redux.io/extension/google-maps/

Regards
Jinjacko

**Comment by dovy** [comment]
Jinjacko:

Indeed it can, but you do have to provide a Google API key. That's the only
limitation. You can find more details here:
https://docs.redux.io/premium/google-maps.html

--
Dovy Paukstys
SimpleRain Studios
801.706.4076

**Comment by Jinjacko** [comment]
Dovy

Thanks a lot for your prompt reply, I appreciate
I read documentation and as I'm not confortable with php, I wonder whether the extension will work out of the box so I can create custom fields based on google address or not
Do you offer such a service ? If i purchase this extension, can support help me do it with included support or at an additional cost ?
Thanks again 

Jinjacko
