### ISSUE TITLE
Color schemes extension not working right

### ISSUE THREAD

**Issue by khanna12** [reduxframework/redux-extensions#389]
We have created 10 color schemes in our wordpress theme and all works fine but after some time the default color scheme gets active and what ever color scheme we select, it makes no impact. Please help.
![color-scheme](https://user-images.githubusercontent.com/55926606/65820734-44b9df00-e24a-11e9-9209-b481401e6fec.png)

**Comment by khanna12** [comment]
Anybody there?

**Comment by dovy** [comment]
Sorry yes, my apologies. That seems like a corruption in the data. Is anything else modifying the Redux options data? Also, have you seen any issues with JSON save issues?

**Comment by khanna12** [comment]
Thank you for the response. Sorry to say but I didn't get your below question:
"That seems like a corruption in the data. Is anything else modifying the Redux options data"

We are not facing any JSON issue while saving.

**Comment by dovy** [comment]
Please follow these instructions so we can better serve you: https://docs.redux.io/guides/basics/generating-a-support-hash.html

**Comment by dovy** [comment]
P.S. Are you a developer or a user? If you are using a product, you need to contact your author.

**Comment by khanna12** [comment]
Yes, we are developer and building the product. I have submitted the support url as per your instructions.
