### ISSUE TITLE
Unable to communicate back with site to check for fatal errors, so the PHP change was reverted. You will need to upload your PHP file change by some other means, such as by using SFTP. and more

### ISSUE THREAD

**Issue by malickhuda** [reduxframework/redux-extensions#390]
Unable to communicate back with site to check for fatal errors, so the PHP change was reverted. You will need to upload your PHP file change by some other means, such as by using SFTP.

Fatal error: Uncaught Error: Call to private Browser::__construct() from context 'Redux_Helpers' in 
/home/m2qxpul59miv/public_html/propertyfiesta.com/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_helpers.php:430 

Stack trace: 
#0 /home/m2qxpul59miv/public_html/propertyfiesta.com/wp-content/plugins/redux-framework/ReduxCore/inc/welcome/views/status_report.php(21): Redux_Helpers::compileSystemStatus(false, true) 

#1 /home/m2qxpul59miv/public_html/propertyfiesta.com/wp-content/plugins/redux-framework/ReduxCore/inc/welcome/welcome.php(452): require_once('/home/m2qxpul59...') 

#2 /home/m2qxpul59miv/public_html/propertyfiesta.com/wp-includes/class-wp-hook.php(286): Redux_Welcome->status_screen('') 

#3 /home/m2qxpul59miv/public_html/propertyfiesta.com/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) 

#4 /home/m2qxpul59miv/public_html/propertyfiesta.com/wp-includes/plugin.php(465): WP_Hook->do_action(Array) 

#5 /home/m2qxpul59miv/public_html/propertyfiesta.com/wp-admin/admin.php(253): do_action('tools in /home/m2qxpul59miv/public_html/propertyfiesta.com/wp-content/plugins/redux-framework/ReduxCore/inc/class.redux_helpers.php on line 430

The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.

**Comment by dovy** [comment]
Thanks for the error. Can you share more details about your site or version of WordPress or anything else? A support url would really help.

**Comment by FeerLaas** [comment]
hi, i have same problem... My wp version is 5.4.1 and my site, when i enabled redux framework really slow... and when switch off redux get speed..

**Comment by dovy** [comment]
So very odd. We're going to be removing the redirect completely, so that will go away soon. You're welcome to install Redux 4.0 and test: http://wordpress.org/plugins/redux-framework-4.  This problem should be gone.
