### ISSUE TITLE
Refund Request

### ISSUE THREAD

**Issue by mediumred** [reduxframework/redux-extensions#392]
Hello,

On the 3rd of January you automatically renewed my subscription for "Icon Select" and "Repeater". I would like a refund please because I was not able to access the user dashboard before January 3rd in order to cancel my subscription. I did not receive an email from you 2 weeks before the subscription renewal, I did not receive an email confirming the payment I automatically did for you. You even took the money from an expired credit card I had registered with you. 

I hope you will be able to help me
Thank you!

**Comment by dovy** [comment]
@mediumred please email support@redux.io and include more details such as account username, order numbers, email, etc.
