### ISSUE TITLE
metaboxes-1.4.2 / metaboxes-1.4.4 and validation (Working only with the last box)

### ISSUE THREAD

**Issue by Graphicfort** [reduxframework/redux-extensions#394]
WordPress Version 5.4

Code:

<pre>
Redux_Metaboxes::setBox( $opt_name, array(
	'id'                      => 'test-validation-1',
	'title'                   => 'validation 1',
	'post_types'              => array( 'post', ),
	'position'                => 'normal',
	'priority'                => 'high',
	'metaboxes_save_defaults' => true,
	'sections'                => array(

		array(
			'id'     => 'redux-test-validation-1',
			'icon'   => 'dashicons dashicons-admin-generic',
			'title'  => 'Test validation',
			'fields' => array(

				array(
					'id'       => 'test_validation_1',
					'type'     => 'text',
					'title'    => 'Title',
					'validate' => 'no_html',
				),

			),
		),

	),
) );

Redux_Metaboxes::setBox( $opt_name, array(
	'id'                      => 'test-validation-2',
	'title'                   => 'validation 2',
	'post_types'              => array( 'page', ),
	'position'                => 'normal',
	'priority'                => 'high',
	'metaboxes_save_defaults' => true,
	'sections'                => array(

		array(
			'id'     => 'redux-test-validation-2',
			'icon'   => 'dashicons dashicons-admin-generic',
			'title'  => 'Test validation',
			'fields' => array(

				array(
					'id'       => 'test_validation_2',
					'type'     => 'text',
					'title'    => 'Title',
					'validate' => 'no_html',
				),

			),
		),

	),
) );
</pre>

i'm trying to make a validation in metaboxes (tried both versions 1.4.2 and 1.4.4) and the result is the same the validation only working with the last box

in the previous code the validation will work on test-validation-2 fields (Whatever the number of the fields) and it will ignore test-validation-1

by swapping the boxes order the validation will work on test-validation-1 and it will ignore test-validation-2

i have tried adding the code from Theme and a Plugin the result is the same

**Comment by mrjk990** [comment]
same problem !
how you fixed ?

**Comment by Graphicfort** [comment]
> same problem ! how you fixed ?

No, switched to https://metabox.io/
