### ISSUE TITLE
How can I purchase?

### ISSUE THREAD

**Issue by ZoOmArts** [reduxframework/redux-extensions#395]
Hi there,

I have a question about metaboxes and repeater addons, I'm gonna create premium wordpress theme that contain redux plugin, I want to use theses addons in my theme but now I don't see these extensions available at this time!! How can I purchase please?
Have a nice day.

Thanks!

**Comment by dillix** [comment]
+1

**Comment by dovy** [comment]
Redux Pro contains all the extensions. You have one price now for everything. Buy the Elite license and then you can bundle Redux Pro inside your premium products.

The only limitation is users will have to have their own license key to get unlimited access to the templates.
