### ISSUE TITLE
Conditional Field Visibility Issue in Repeater Field on Initial Page Load

### ISSUE THREAD

**Issue by zohrabi71** [reduxframework/redux-extensions#399]
Description:

I am experiencing a bug with conditional visibility in the Redux Framework specifically when using the repeater field type. The issue arises when a field (view) is conditionally displayed based on another field's (component) value within a repeater. On the initial page load, the conditional logic does not apply correctly. However, the visibility toggles correctly once the component field's value is changed.

Steps to Reproduce:

    Define a repeater field with a radio field named component and another radio field named view that should be conditionally displayed.
    Configure the view field to be visible only when the component field is set to card2.
    Load the page or settings panel for the first time.

Expected Behavior:

    The view field should be visible only when the component field is set to card2.
    If the component field is set to any other value, the view field should be hidden.
    This conditional logic should be correctly applied during the initial page load.

Actual Behavior:

    The view field does not correctly hide or show based on the component field's value when the page initially loads.
    The conditional logic works as expected only after changing the value of the component field.

Code Example:

Here is the configuration I am using:
```
$section = array(
    'title'      => 'title',
    'id'         => 'example',
    'icon'      => '',
    'subsection' => true,
    'fields' => array(
        array(
            'id'       => 'example_items',
            'type'   => 'repeater',
            'title'    => 'example title',
            'group_values' => true,
            'bind_title'   => 'heading',
            'fields'    => array(
                array(
                    'id'       => 'heading',
                    'type'   => 'text',
                    'title'    => 'Heading',
                ),
                array(
                    'id'      => 'component',
                    'type'  => 'radio',
                    'title'   => 'Component',
                    'data'  => array(
                        'card'   => 'Card 1',
                        'card2' => 'Card 2'
                    ),
                    'default' => 'card'
                ),
                array(
                    'id'      => 'view',
                    'type'  => 'radio',
                    'title'   => 'View',
                    'data'  => array(
                        'grid'        => 'Grid',
                        'carousel'  => 'Carousel'
                    ),
                    'default'   => 'grid',
                    'required' => array('component', '=', 'card2')
                )
            )
        )
    )
);
```

**Comment by kprovance** [comment]
Hi,

First, Repeater is no longer an extension. It's part of the Redux core. Thus, issues should be posted here: https://github.com/reduxframework/redux-framework/issues. (When posting there, please read all the instructions provided, include ALL the requested information, and do NOT skip over any section or not fill it out).

Second, I don't have enough information about your setup to make a guess, except to say if you're using an older version of Redux with the old repeater extension, that's likely the problem.  I ran your config with the current version of Redux and I didn't see any conditional logic issue.

**Comment by zohrabi71** [comment]
Thank you, 
"Choose Card 2 and save, then reload the page. The 'View' field should be visible, but it is not."
