### ISSUE TITLE
Custom Fonts Extension

### ISSUE THREAD

**Issue by pseudonymus** [ReduxFramework/redux-extensions#48]
Hey guys,

I just downloaded and connected the custom fonts extension to my theme options framework(v3.2.8.15). Uploaded a zip archive of a Bebas Neue font(which contained an .otf and a .txt file), taken from FontSquirrel. Firstly I got the "Please Wait" message, which didn`t close until I refreshed the page. After the page refresh, the font was listed in the panel. 

Secondly, the font appeared fine, in the typography field list, among the others, but after selecting it as the active font, the frontend didn't get it. Do I have to use a specific argument? Here`s how the typography field is created in config.php:

<pre>
                    array(
                        'id'        => 'body_font_typo',
                        'type'      => 'typography',
                        'output'    => array('html body'),
                        'title'     => __('Body Font Options', 'redux-framework-demo'),
                        'subtitle'  => __('Select font options for the body', 'redux-framework-demo'),
                        'google'    => true,
                        'text-align'=> false,
                        'subsets'   => true,
                        'font-weight' => false,
                        'default'   => array(
                            'google'      => true,
                            'color'         => '#686868',
                            'font-size'     => '15px',
                            'font-family'   => 'Open Sans',
                            'line-height'   => '24px',
                            'font-weight'   => '300',
                        ),
                    ),
</pre>

Thirdly, which is quite weird, after removing the font from the list, I can`t see the upload button anymore: http://awesomescreenshot.com/04d2sntb9a

Any thoughts?

Localhost environment
Wordpress 3.9.1
Redux framework - v3.2.8.15 
Tried it in both standard and dev_mode

Thanks!

**Comment by anikitas** [comment]
Just trying to include Custom Fonts in my Theme for a first time :)
Awesome concept great job.

Have similar problems even with latest WordPress 4.1 + Redux v3.4.0.
Trying first on local host with WAMP.

I get a javascript error:
<pre>
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
http://localhost/dummy/wp-admin/load-scripts.php?c=1&load%5B%5D=jquery-core,jquery-migrate,utils,plupload,json2,farbtastic&ver=4.1
Line 4
</pre>

Maybe i'm doing something wrong with the configuration.
I will try to debug. I'll let you know.

**Comment by anikitas** [comment]
Ok,
I think i fixed it:
getMissingFiles was missing one last parameter in php file Line 407

From:
<pre>
$this->getMissingFiles($name, $fontname, $missing, $output);
</pre>

To
<pre>
$this->getMissingFiles($name, $fontname, $missing, $output, $subfolder);
</pre>

Not 100% sure!

@Kevin: can you verify that?

**Comment by anikitas** [comment]
I think this fixes only if you have the complete set of fonts ( .eot, .woff, svg, .ttf )

**Comment by dovy** [comment]
Actually you should have an email now. The API we used before to convert the fonts now requires secure URLs only. Check your email and thanks for the bug report!

**Comment by dovy** [comment]
And a new release has been uploaded.  :)
