### ISSUE TITLE
Redux Metaboxes Breaking Custom Selects in Insert Media

### ISSUE THREAD

**Issue by wpexplorer** [ReduxFramework/redux-extensions#86]
Example: http://cl.ly/image/3N0V0g3K0b3B

This is using the JW Player plugin - https://wordpress.org/plugins/jw-player-plugin-for-wordpress/

**Comment by kprovance** [comment]
Closing due to the age of the ticket, and no reply.  AJ, if you're still seeing this, try updating to the latest Metabox v1.3.0.
