### ISSUE TITLE
Problem using metaboxes extension in two (or more) different plugins.

### ISSUE THREAD

**Issue by peterkaer** [ReduxFramework/redux-extensions#91]
Hi

If you use the metaboxes extension in two (or more) different plugins, with different opt_name, one of the plug-ins won't work. It seems to come down to how the "redux/extensions/[opt_name]/before" event is fired, but I'm not sure.

Thanks

**Comment by kprovance** [comment]
First, please update to the latest versions of Redux and Metaboxes.  Lots o fixes since this ticket was opened.  If the issue still persists, please open a new issue, supplying the required information as specified here: https://github.com/ReduxFramework/redux-framework/issues/1975
