### ISSUE TITLE
Redux Metaboxes Incompatible with WPML

### ISSUE THREAD

**Issue by wpexplorer** [ReduxFramework/redux-extensions#93]
It always pulls the meta values of the main language page so it's not possible to alter meta options on a per language basis :(

Do you have WPML or do I need to send it to you?

Thanks!

**Comment by kprovance** [comment]
AJ, would this be of any help?  http://docs.reduxframework.com/core/advanced/wpml-integration/

**Comment by wpexplorer** [comment]
Hey Kevin, thanks but I actually coded my own metaboxes class (Redux is just too advanced for my needs) ;)

http://cl.ly/image/2q3g2s3i2w21

**Comment by kprovance** [comment]
Nice design.  Does that mean you moved away from Redux as a whole, or just the metabox?  I'd hate to see one of the few guys knows his stuff leave us.  ;-)
